/**
 * Rooted Reset Fuel Pattern Assessment, Build 3 — the meal library.
 *
 * =====================================================================
 * WHY THIS IS A TYPED CONSTANT AND NOT A SET OF ROWS.
 * =====================================================================
 *
 * Everything here is copy a member reads, and copy a member reads is
 * guarded at the source: the em dash guard, the prescriptive vocabulary
 * guard and the no-digit rule all walk source files with the TypeScript
 * compiler and none of them can see inside a database. Stored coaching
 * content has already been the one place a banned character survived a
 * sweep (CLAUDE.md, the 2026-08-27 rules), so the seventy two meals live
 * where the guards can read them. It is the same decision the Health and
 * Lifestyle Intake made about its own questions.
 *
 * It also makes a correction a content only edit, which is what a coach
 * reviewing this library after the fact will actually want.
 *
 * =====================================================================
 * WHAT THE SETS ARE REQUIRED TO CONTAIN.
 * =====================================================================
 *
 * Three patterns by four meal types by six meals. Inside every set of
 * six, and enforced by tests/fuel-pattern-meal-library.test.ts rather
 * than by a promise in a comment:
 *
 *   at least two vegetarian, at least two dairy free, at least two egg
 *   free, at least four pork free, and fish in no more than two.
 *
 * One more rule lives only here, and it exists so that the rotation
 * engine can keep its promise never to hand her something she has told
 * it she does not eat: EVERY SET OF SIX HOLDS AT LEAST ONE MEAL THAT
 * CARRIES ALL FIVE FLAGS AT ONCE. Without it a member who is vegetarian
 * and avoids dairy and eggs could empty a slot, and the only honest
 * things left to do would both be bad ones.
 *
 * =====================================================================
 * THE COMPOSITION IS REAL.
 * =====================================================================
 *
 * Protein-Supportive leads with protein and vegetables and keeps the
 * starch portion smaller. Balanced Fuel splits the plate evenly.
 * Carb-Supportive gives whole food carbohydrate a little more room with
 * protein alongside. Snacks are the same logic at a smaller scale. The
 * three range words on each meal say which of those it is, and they are
 * words rather than numbers everywhere.
 */

import type { FpaMeal } from './types';

/** Protein-Supportive: protein and vegetables lead, the starch portion stays smaller. */
const PROTEIN_SUPPORTIVE: FpaMeal[] = [
  // ---------------- breakfast ----------------
  {
    id: 'ps-breakfast-1',
    name: 'Eggs with Sauteed Greens and Sweet Potato',
    type: 'breakfast',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Eggs', 'Spinach', 'Sweet potato', 'Olive oil', 'Black pepper'],
    summary: 'Eggs, spinach and a small portion of sweet potato',
    whyItFits:
      'Protein and healthy fat carry most of this plate while the sweet potato stays a small portion, which is the shape your responses leaned toward. It is built to hold a morning without leaning on starch to do it.',
    flags: ['vegetarian', 'dairy_free', 'fish_free', 'pork_free'],
    allergens: ['eggs'],
    prepMinutes: 20,
    image: null,
  },
  {
    id: 'ps-breakfast-2',
    name: 'Smoked Salmon with Scrambled Eggs and Avocado',
    type: 'breakfast',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Higher',
    ingredients: ['Smoked salmon', 'Eggs', 'Avocado', 'Lemon', 'Chives'],
    summary: 'Salmon, eggs and avocado, no starch alongside',
    whyItFits:
      'Two protein sources and the fat in the avocado do the work here, with nothing starchy beside them. That combination is designed to support a long, steady stretch before hunger arrives again.',
    flags: ['dairy_free', 'pork_free'],
    allergens: ['eggs', 'fish'],
    prepMinutes: 15,
    image: 'ps-breakfast-2.jpg',
  },
  {
    id: 'ps-breakfast-3',
    name: 'Greek Yogurt with Walnuts and Berries',
    type: 'breakfast',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Plain Greek yogurt', 'Walnuts', 'Blueberries', 'Cinnamon'],
    summary: 'Thick yogurt, walnuts and a handful of berries',
    whyItFits:
      'The yogurt brings the protein, the walnuts bring the fat, and the berries keep the carbohydrate light rather than absent. A quiet way to start a day that wants protein early.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'nuts'],
    prepMinutes: 5,
    image: 'ps-breakfast-3.jpg',
  },
  {
    id: 'ps-breakfast-4',
    name: 'Turkey and Vegetable Breakfast Skillet',
    type: 'breakfast',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Ground turkey', 'Red pepper', 'Onion', 'New potatoes', 'Olive oil', 'Paprika'],
    summary: 'Turkey, peppers and onion with a few new potatoes',
    whyItFits:
      'A savory start for a morning that does not want anything sweet. The turkey and vegetables fill the pan and the potato is there in a smaller amount, which is the balance your answers pointed at.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 20,
    image: null,
  },
  {
    id: 'ps-breakfast-5',
    name: 'Black Bean and Roasted Pepper Breakfast Bowl',
    type: 'breakfast',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Black beans', 'Roasted red peppers', 'Avocado', 'Lime', 'Coriander', 'Olive oil'],
    summary: 'Black beans, roasted peppers and avocado',
    whyItFits:
      'Beans give this bowl its protein and its staying power at the same time, and the avocado adds the fat that makes a plant plate satisfying. Nothing here relies on an animal food to hold you.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 15,
    image: 'ps-breakfast-5.jpg',
  },
  {
    id: 'ps-breakfast-6',
    name: 'Steak and Eggs with Wilted Spinach',
    type: 'breakfast',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Sirloin steak', 'Eggs', 'Spinach', 'Garlic', 'Olive oil'],
    summary: 'Steak, eggs and a pile of wilted spinach',
    whyItFits:
      'This is the most protein forward breakfast in the set, with vegetables rather than starch alongside it. When answers lean strongly the way yours did, a morning like this one tends to hold for a long time.',
    flags: ['dairy_free', 'fish_free', 'pork_free'],
    allergens: ['eggs'],
    prepMinutes: 20,
    image: 'ps-breakfast-6.jpg',
  },

  // ---------------- lunch ----------------
  {
    id: 'ps-lunch-1',
    name: 'Grilled Chicken Salad with Avocado and Quinoa',
    type: 'lunch',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Chicken breast', 'Mixed leaves', 'Avocado', 'Quinoa', 'Olive oil', 'Lemon'],
    summary: 'Chicken over leaves with avocado and a little quinoa',
    whyItFits:
      'The chicken and the avocado carry this plate and the quinoa stays a small spoonful rather than the base. It is a midday meal designed to support an afternoon that does not dip.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 20,
    image: 'ps-lunch-1.jpg',
  },
  {
    id: 'ps-lunch-2',
    name: 'Tuna and White Bean Salad with Lemon',
    type: 'lunch',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Tinned tuna', 'Cannellini beans', 'Red onion', 'Parsley', 'Olive oil', 'Lemon'],
    summary: 'Tuna and white beans dressed with lemon and olive oil',
    whyItFits:
      'Two protein sources sit together here, one from the sea and one from the beans, so the plate is filling without needing bread beside it. It comes together in the time it takes to open a tin.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish'],
    prepMinutes: 10,
    image: 'ps-lunch-2.jpg',
  },
  {
    id: 'ps-lunch-3',
    name: 'Lentil and Roasted Vegetable Bowl with Lemon',
    type: 'lunch',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Green lentils', 'Courgette', 'Aubergine', 'Cherry tomatoes', 'Olive oil', 'Lemon'],
    summary: 'Lentils with roasted vegetables and a lemon dressing',
    whyItFits:
      'Lentils are the protein and the vegetables are most of the volume, which keeps the balance where your responses put it. A plant plate that behaves like a substantial one.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 25,
    image: null,
  },
  {
    id: 'ps-lunch-4',
    name: 'Beef and Broccoli Stir Fry over Cauliflower Rice',
    type: 'lunch',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Beef strips', 'Broccoli', 'Ginger', 'Garlic', 'Soy sauce', 'Cauliflower rice', 'Sesame oil'],
    summary: 'Beef and broccoli over cauliflower rice',
    whyItFits:
      'Swapping the rice for cauliflower keeps the carbohydrate light while the beef and broccoli stay generous. Fast enough for a weekday and savory enough to feel like a proper meal.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['soy', 'gluten'],
    prepMinutes: 20,
    image: 'ps-lunch-4.jpg',
  },
  {
    id: 'ps-lunch-5',
    name: 'Cottage Cheese with Cucumber, Tomato and Olives',
    type: 'lunch',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Cottage cheese', 'Cucumber', 'Tomatoes', 'Black olives', 'Olive oil', 'Oregano'],
    summary: 'Cottage cheese with chopped salad and olives',
    whyItFits:
      'Almost no preparation and a lot of protein, with the olives and the olive oil supplying the fat that makes it satisfying. Useful on a day when lunch has to happen at a desk.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy'],
    prepMinutes: 5,
    image: 'ps-lunch-5.jpg',
  },
  {
    id: 'ps-lunch-6',
    name: 'Turkey Lettuce Wraps with Herbs and Lime',
    type: 'lunch',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Ground turkey', 'Little gem lettuce', 'Spring onion', 'Mint', 'Lime', 'Olive oil'],
    summary: 'Seasoned turkey spooned into crisp lettuce leaves',
    whyItFits:
      'The lettuce does the job bread usually does, so the protein leads without anything heavy beside it. Light on the stomach and still substantial, which is a combination your answers seemed to want.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 15,
    image: null,
  },

  // ---------------- dinner ----------------
  {
    id: 'ps-dinner-1',
    name: 'Roast Chicken Thighs with Green Beans and Sweet Potato',
    type: 'dinner',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Chicken thighs', 'Green beans', 'Sweet potato', 'Rosemary', 'Olive oil', 'Garlic'],
    summary: 'Roast chicken with green beans and a small sweet potato',
    whyItFits:
      'One tray, protein at the centre, vegetables filling most of the plate and the sweet potato present in a modest portion. That arrangement is what the evening version of your pattern tends to look like.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 35,
    image: null,
  },
  {
    id: 'ps-dinner-2',
    name: 'Baked Salmon with Asparagus and Lemon',
    type: 'dinner',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Higher',
    ingredients: ['Salmon fillet', 'Asparagus', 'Lemon', 'Olive oil', 'Dill'],
    summary: 'Salmon and asparagus baked together with lemon',
    whyItFits:
      'Salmon brings protein and its own fat in the same bite, which is why this plate feels complete without a starch beside it. It is also one of the least demanding dinners in the set.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish'],
    prepMinutes: 25,
    image: 'ps-dinner-2.jpg',
  },
  {
    id: 'ps-dinner-3',
    name: 'Chickpea and Spinach Curry with Cauliflower Rice',
    type: 'dinner',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Chickpeas', 'Spinach', 'Coconut milk', 'Tomatoes', 'Onion', 'Ginger', 'Cumin', 'Cauliflower rice'],
    summary: 'Chickpea curry served over cauliflower rice',
    whyItFits:
      'Chickpeas and coconut milk give this the protein and fat that keep a curry from fading quickly, and the cauliflower keeps the carbohydrate light. Warming food that still sits where your pattern sits.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 25,
    image: 'ps-dinner-3.jpg',
  },
  {
    id: 'ps-dinner-4',
    name: 'Pork Tenderloin with Braised Red Cabbage and Apple',
    type: 'dinner',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Pork tenderloin', 'Red cabbage', 'Apple', 'Onion', 'Olive oil', 'Thyme'],
    summary: 'Sliced pork with slow braised cabbage and apple',
    whyItFits:
      'The pork holds the centre of the plate and the cabbage and apple bring sweetness without a starch. It reads like a Sunday dinner and still keeps the carbohydrate on the lighter side.',
    flags: ['dairy_free', 'egg_free', 'fish_free'],
    allergens: [],
    prepMinutes: 30,
    image: null,
  },
  {
    id: 'ps-dinner-5',
    name: 'Baked Eggs in Tomato and Pepper Sauce with Wilted Greens',
    type: 'dinner',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Eggs', 'Tomatoes', 'Red pepper', 'Onion', 'Kale', 'Olive oil', 'Smoked paprika'],
    summary: 'Eggs baked into a tomato and pepper sauce with greens',
    whyItFits:
      'Eggs cooked into the sauce make this a protein dinner that costs almost nothing and takes one pan. The greens fill the plate out so nothing starchy has to.',
    flags: ['vegetarian', 'dairy_free', 'fish_free', 'pork_free'],
    allergens: ['eggs'],
    prepMinutes: 20,
    image: 'ps-dinner-5.jpg',
  },
  {
    id: 'ps-dinner-6',
    name: 'Herb Baked Cod with Roasted Broccoli and White Beans',
    type: 'dinner',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Cod fillet', 'Broccoli', 'Cannellini beans', 'Parsley', 'Olive oil', 'Lemon'],
    summary: 'Baked cod with roasted broccoli and warm white beans',
    whyItFits:
      'Cod is lean, so the beans and the olive oil are what give this plate its weight. Two protein sources and a lot of vegetable, which is the arrangement your responses favoured.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish'],
    prepMinutes: 25,
    image: null,
  },

  // ---------------- snack ----------------
  {
    id: 'ps-snack-1',
    name: 'Hard Boiled Eggs with Cherry Tomatoes',
    type: 'snack',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Eggs', 'Cherry tomatoes', 'Sea salt', 'Black pepper'],
    summary: 'Boiled eggs and tomatoes, salted',
    whyItFits:
      'Protein and fat in one portable package, with nothing sweet attached. The kind of snack designed to close a gap rather than open an appetite.',
    flags: ['vegetarian', 'dairy_free', 'fish_free', 'pork_free'],
    allergens: ['eggs'],
    prepMinutes: 10,
    image: null,
  },
  {
    id: 'ps-snack-2',
    name: 'Greek Yogurt with Almonds',
    type: 'snack',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Plain Greek yogurt', 'Almonds', 'Cinnamon'],
    summary: 'Thick yogurt with a scattering of almonds',
    whyItFits:
      'Thick yogurt and nuts put protein and fat together with very little carbohydrate, which tends to be the version of a snack that actually lasts. Ready in the time it takes to find a spoon.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'nuts'],
    prepMinutes: 3,
    image: null,
  },
  {
    id: 'ps-snack-3',
    name: 'Turkey Slices with Cucumber and Olives',
    type: 'snack',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Roast turkey', 'Cucumber', 'Green olives'],
    summary: 'Cold turkey with cucumber and a few olives',
    whyItFits:
      'Savory rather than sweet, and built almost entirely from protein and fat. Worth keeping in mind for the late afternoon, which is where snacks usually get decided.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 5,
    image: null,
  },
  {
    id: 'ps-snack-4',
    name: 'Spiced Chickpeas with Lemon',
    type: 'snack',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Moderate',
    fat: 'Lighter',
    ingredients: ['Chickpeas', 'Olive oil', 'Cumin', 'Paprika', 'Lemon', 'Sea salt'],
    summary: 'Warm spiced chickpeas with a squeeze of lemon',
    whyItFits:
      'Chickpeas carry both the protein and the crunch here, so a snack that looks like a treat behaves like a small meal. Nothing in it is out of the ordinary cupboard.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 8,
    image: 'ps-snack-4.jpg',
  },
  {
    id: 'ps-snack-5',
    name: 'Sardines on Cucumber Rounds',
    type: 'snack',
    pattern: 'protein_supportive',
    protein: 'Higher',
    carbohydrate: 'Lighter',
    fat: 'Higher',
    ingredients: ['Tinned sardines', 'Cucumber', 'Lemon', 'Black pepper'],
    summary: 'Sardines spooned onto thick cucumber slices',
    whyItFits:
      'Sardines bring protein and fat together and the cucumber replaces the cracker, which keeps the carbohydrate out of it altogether. A small savory thing that holds more than its size suggests.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish'],
    prepMinutes: 5,
    image: null,
  },
  {
    id: 'ps-snack-6',
    name: 'Cheese and Walnuts with Apple Slices',
    type: 'snack',
    pattern: 'protein_supportive',
    protein: 'Moderate',
    carbohydrate: 'Lighter',
    fat: 'Higher',
    ingredients: ['Mature cheddar', 'Walnuts', 'Apple'],
    summary: 'Cheese, walnuts and a sliced apple',
    whyItFits:
      'Cheese and walnuts supply the protein and fat, and the apple keeps a little fruit in the picture without taking it over. Three things, no preparation, no packet.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'nuts'],
    prepMinutes: 3,
    image: null,
  },
];

/** Balanced Fuel: protein, carbohydrate and fat share the plate evenly. Flexible Fuel reads this set too. */
const BALANCED_FUEL: FpaMeal[] = [
  // ---------------- breakfast ----------------
  {
    id: 'bf-breakfast-1',
    name: 'Oats with Greek Yogurt, Berries and Almonds',
    type: 'breakfast',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Rolled oats', 'Plain Greek yogurt', 'Raspberries', 'Almonds', 'Cinnamon'],
    summary: 'Oats stirred through yogurt with berries and almonds',
    whyItFits:
      'The oats bring the carbohydrate, the yogurt brings the protein and the almonds bring the fat, in roughly equal measure. That even three way split is the shape your responses settled on.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'nuts', 'gluten'],
    prepMinutes: 10,
    image: 'bf-breakfast-1.jpg',
  },
  {
    id: 'bf-breakfast-2',
    name: 'Eggs on Whole Grain Toast with Avocado',
    type: 'breakfast',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Eggs', 'Whole grain bread', 'Avocado', 'Lemon', 'Chilli flakes'],
    summary: 'Eggs and smashed avocado on whole grain toast',
    whyItFits:
      'Three components, one from each side of the plate, which is why this breakfast has stayed popular. It is built to support steadier energy without asking you to think about it.',
    flags: ['vegetarian', 'dairy_free', 'fish_free', 'pork_free'],
    allergens: ['eggs', 'gluten'],
    prepMinutes: 12,
    image: 'bf-breakfast-2.jpg',
  },
  {
    id: 'bf-breakfast-3',
    name: 'Turkey Sausage with Scrambled Eggs and Roasted Potatoes',
    type: 'breakfast',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Turkey sausage', 'Eggs', 'New potatoes', 'Olive oil', 'Chives'],
    summary: 'Turkey sausage, eggs and roasted new potatoes',
    whyItFits:
      'A cooked breakfast that keeps its three parts in proportion rather than letting one of them take over. Good for a slower morning or a day that starts early.',
    flags: ['dairy_free', 'fish_free', 'pork_free'],
    allergens: ['eggs'],
    prepMinutes: 25,
    image: null,
  },
  {
    id: 'bf-breakfast-4',
    name: 'Banana Oat Pancakes with Almond Butter',
    type: 'breakfast',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Rolled oats', 'Banana', 'Eggs', 'Almond butter', 'Cinnamon'],
    summary: 'Oat and banana pancakes spread with almond butter',
    whyItFits:
      'Eggs and almond butter keep this from being a sweet breakfast that disappears by mid morning. The banana and oats hold the carbohydrate side in place while those two hold the other.',
    flags: ['vegetarian', 'dairy_free', 'fish_free', 'pork_free'],
    allergens: ['eggs', 'nuts', 'gluten'],
    prepMinutes: 20,
    image: null,
  },
  {
    id: 'bf-breakfast-5',
    name: 'Black Bean and Sweet Potato Breakfast Hash with Avocado',
    type: 'breakfast',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Black beans', 'Sweet potato', 'Onion', 'Avocado', 'Olive oil', 'Smoked paprika'],
    summary: 'Sweet potato and black bean hash topped with avocado',
    whyItFits:
      'Beans for protein, sweet potato for carbohydrate and avocado for fat, all in one pan and all in proportion. Nothing from an animal is needed for this one to hold together.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 25,
    image: null,
  },
  {
    id: 'bf-breakfast-6',
    name: 'Cottage Cheese with Peaches and Whole Grain Toast',
    type: 'breakfast',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Lighter',
    ingredients: ['Cottage cheese', 'Peaches', 'Whole grain bread', 'Honey'],
    summary: 'Cottage cheese and sliced peaches with toast',
    whyItFits:
      'Almost nothing to prepare, and still a breakfast with protein in it rather than fruit and bread alone. The toast is there in a single slice, which keeps the balance even.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'gluten'],
    prepMinutes: 5,
    image: null,
  },

  // ---------------- lunch ----------------
  {
    id: 'bf-lunch-1',
    name: 'Chicken, Brown Rice and Roasted Vegetable Bowl',
    type: 'lunch',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Chicken breast', 'Brown rice', 'Courgette', 'Red pepper', 'Olive oil', 'Lemon'],
    summary: 'Chicken and brown rice with roasted vegetables',
    whyItFits:
      'Three roughly equal parts in one bowl, which is the simplest version of the balance your answers described. It also reheats without falling apart, which matters on a working day.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 25,
    image: null,
  },
  {
    id: 'bf-lunch-2',
    name: 'Tuna Salad Sandwich on Whole Grain Bread',
    type: 'lunch',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Tinned tuna', 'Whole grain bread', 'Olive oil', 'Lemon', 'Celery', 'Rocket'],
    summary: 'Tuna dressed in olive oil and lemon, with leaves',
    whyItFits:
      'Dressing the tuna in olive oil and lemon rather than anything richer keeps the fat honest and lets the bread and the fish sit evenly either side of it. Lunch in under ten minutes.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish', 'gluten'],
    prepMinutes: 10,
    image: 'bf-lunch-2.jpg',
  },
  {
    id: 'bf-lunch-3',
    name: 'Lentil Soup with Whole Grain Bread and a Side Salad',
    type: 'lunch',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Red lentils', 'Carrot', 'Celery', 'Onion', 'Whole grain bread', 'Mixed leaves', 'Olive oil'],
    summary: 'Lentil soup with bread and a dressed salad',
    whyItFits:
      'Lentils cover the protein and much of the carbohydrate at once, and the bread and the dressing finish the balance. A pot of this covers several lunches.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['gluten'],
    prepMinutes: 30,
    image: 'bf-lunch-3.jpg',
  },
  {
    id: 'bf-lunch-4',
    name: 'Turkey and Avocado Wrap with Mixed Greens',
    type: 'lunch',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Roast turkey', 'Whole grain wrap', 'Avocado', 'Mixed leaves', 'Tomato', 'Lime'],
    summary: 'Turkey, avocado and leaves rolled in a whole grain wrap',
    whyItFits:
      'The avocado is doing real work here, turning what could be a thin lunch into one with all three parts present. Easy to carry and easy to eat with one hand.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['gluten'],
    prepMinutes: 10,
    image: 'bf-lunch-4.jpg',
  },
  {
    id: 'bf-lunch-5',
    name: 'Greek Salad with Chickpeas and Pita',
    type: 'lunch',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Chickpeas', 'Feta', 'Cucumber', 'Tomatoes', 'Red onion', 'Olives', 'Whole grain pita', 'Olive oil'],
    summary: 'Chickpeas and feta through a chopped Greek salad with pita',
    whyItFits:
      'The chickpeas and feta share the protein, the pita brings the carbohydrate and the olive oil and olives bring the fat. Cold, quick and forgiving about exact quantities.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'gluten'],
    prepMinutes: 15,
    image: 'bf-lunch-5.jpg',
  },
  {
    id: 'bf-lunch-6',
    name: 'Grilled Steak Salad with Potatoes and Green Beans',
    type: 'lunch',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Sirloin steak', 'New potatoes', 'Green beans', 'Mixed leaves', 'Olive oil', 'Red wine vinegar'],
    summary: 'Sliced steak over potatoes, beans and leaves',
    whyItFits:
      'A steak lunch that keeps its potatoes rather than dropping them, which is what makes it balanced rather than protein led. Good use of anything left from the night before.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 25,
    image: null,
  },

  // ---------------- dinner ----------------
  {
    id: 'bf-dinner-1',
    name: 'Pan Seared Chicken with Potatoes and Green Salad',
    type: 'dinner',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Chicken breast', 'New potatoes', 'Mixed leaves', 'Olive oil', 'Lemon', 'Thyme'],
    summary: 'Seared chicken with potatoes and a dressed salad',
    whyItFits:
      'Protein, potato and salad in even portions is about as plain as a balanced dinner gets, and plain is the point. Every part of it is something you already know how to cook.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 30,
    image: 'bf-dinner-1.jpg',
  },
  {
    id: 'bf-dinner-2',
    name: 'Salmon with Brown Rice and Steamed Broccoli',
    type: 'dinner',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Salmon fillet', 'Brown rice', 'Broccoli', 'Lemon', 'Olive oil'],
    summary: 'Salmon, brown rice and steamed broccoli',
    whyItFits:
      'The salmon carries the fat as well as the protein, so nothing rich needs adding to the rice or the broccoli. A dinner that sits evenly and finishes quietly.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish'],
    prepMinutes: 25,
    image: 'bf-dinner-2.jpg',
  },
  {
    id: 'bf-dinner-3',
    name: 'Beef Chili with Beans and Brown Rice',
    type: 'dinner',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Ground beef', 'Kidney beans', 'Tomatoes', 'Onion', 'Brown rice', 'Cumin', 'Chilli powder'],
    summary: 'Beef and bean chili spooned over brown rice',
    whyItFits:
      'Beef and beans between them cover the protein, the rice covers the carbohydrate and the beef brings enough fat that nothing else has to. It improves on the second day, which is useful.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 40,
    image: 'bf-dinner-3.jpg',
  },
  {
    id: 'bf-dinner-4',
    name: 'Vegetable and Chickpea Stew with Couscous',
    type: 'dinner',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Chickpeas', 'Courgette', 'Carrot', 'Tomatoes', 'Onion', 'Whole wheat couscous', 'Olive oil', 'Cumin'],
    summary: 'Chickpea and vegetable stew over couscous',
    whyItFits:
      'Chickpeas hold the protein side up, the couscous holds the carbohydrate side and the olive oil finishes it. A plant dinner that keeps all three parts rather than two.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['gluten'],
    prepMinutes: 30,
    image: 'bf-dinner-4.jpg',
  },
  {
    id: 'bf-dinner-5',
    name: 'Aubergine and Lentil Bake with Yogurt',
    type: 'dinner',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Aubergine', 'Green lentils', 'Tomatoes', 'Onion', 'Plain yogurt', 'Olive oil', 'Oregano'],
    summary: 'Baked aubergine and lentils finished with yogurt',
    whyItFits:
      'The lentils and the yogurt together give this more protein than a vegetable bake usually carries. Slow to cook and almost no work while it does.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy'],
    prepMinutes: 40,
    image: null,
  },
  {
    id: 'bf-dinner-6',
    name: 'Pork Loin Chops with Roasted Squash and Apple',
    type: 'dinner',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Pork loin chops', 'Butternut squash', 'Apple', 'Sage', 'Olive oil'],
    summary: 'Pork chops with roasted squash and apple',
    whyItFits:
      'The squash is the carbohydrate rather than a potato, which keeps the plate even without making it heavy. Sage and apple do most of the seasoning work.',
    flags: ['dairy_free', 'egg_free', 'fish_free'],
    allergens: [],
    prepMinutes: 30,
    image: 'bf-dinner-6.jpg',
  },

  // ---------------- snack ----------------
  {
    id: 'bf-snack-1',
    name: 'Apple Slices with Peanut Butter',
    type: 'snack',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Apple', 'Peanut butter'],
    summary: 'Sliced apple with peanut butter',
    whyItFits:
      'Fruit on its own tends to pass through quickly, and the peanut butter is what stops that happening. Two ingredients, all three parts of the plate, no preparation.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['nuts'],
    prepMinutes: 3,
    image: null,
  },
  {
    id: 'bf-snack-2',
    name: 'Greek Yogurt with Honey and Oats',
    type: 'snack',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Lighter',
    ingredients: ['Plain Greek yogurt', 'Honey', 'Rolled oats'],
    summary: 'Yogurt with a spoon of oats and a little honey',
    whyItFits:
      'The oats turn a pot of yogurt into something with a carbohydrate side to it, and the honey is there in a small amount rather than as the point. Quiet, quick and easy to repeat.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'gluten'],
    prepMinutes: 3,
    image: 'bf-snack-2.jpg',
  },
  {
    id: 'bf-snack-3',
    name: 'Whole Grain Crackers with Cheese and Grapes',
    type: 'snack',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Whole grain crackers', 'Mature cheddar', 'Grapes'],
    summary: 'Crackers, cheese and a small bunch of grapes',
    whyItFits:
      'An old combination that happens to be balanced: the cheese covers protein and fat, the crackers and grapes cover the carbohydrate. Travels well in a bag.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'gluten'],
    prepMinutes: 3,
    image: 'bf-snack-3.jpg',
  },
  {
    id: 'bf-snack-4',
    name: 'Hummus with Carrot and Cucumber Sticks',
    type: 'snack',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Hummus', 'Carrot', 'Cucumber', 'Olive oil'],
    summary: 'Hummus with raw carrot and cucumber',
    whyItFits:
      'Chickpeas and olive oil are already a balanced pair, and the raw vegetables keep it light. One of the few snacks that is genuinely as good at a desk as at a table.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 5,
    image: 'bf-snack-4.jpg',
  },
  {
    id: 'bf-snack-5',
    name: 'Boiled Eggs with Whole Grain Toast Fingers',
    type: 'snack',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Moderate',
    fat: 'Moderate',
    ingredients: ['Eggs', 'Whole grain bread', 'Butter', 'Black pepper'],
    summary: 'Soft boiled eggs with toast cut into fingers',
    whyItFits:
      'The eggs do the protein and fat, the toast does the carbohydrate, and the whole thing takes one pan of water. Small enough to be a snack and solid enough to feel like one.',
    flags: ['vegetarian', 'fish_free', 'pork_free'],
    allergens: ['eggs', 'dairy', 'gluten'],
    prepMinutes: 10,
    image: 'bf-snack-5.jpg',
  },
  {
    id: 'bf-snack-6',
    name: 'Turkey and Cheese Roll Ups with Cherry Tomatoes',
    type: 'snack',
    pattern: 'balanced_fuel',
    protein: 'Moderate',
    carbohydrate: 'Lighter',
    fat: 'Moderate',
    ingredients: ['Roast turkey', 'Mature cheddar', 'Cherry tomatoes'],
    summary: 'Turkey rolled around cheese, with tomatoes',
    whyItFits:
      'A savory snack for an afternoon that does not want anything sweet, with the tomatoes keeping a little freshness in it. Assembled rather than cooked.',
    flags: ['egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy'],
    prepMinutes: 5,
    image: null,
  },
];

/** Carb-Supportive: whole food carbohydrate gets a little more room, with protein alongside. */
const CARB_SUPPORTIVE: FpaMeal[] = [
  // ---------------- breakfast ----------------
  {
    id: 'cs-breakfast-1',
    name: 'Oatmeal with Banana, Cinnamon and Almond Butter',
    type: 'breakfast',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Rolled oats', 'Banana', 'Almond butter', 'Cinnamon', 'Milk or water'],
    summary: 'Warm oats with banana and a spoon of almond butter',
    whyItFits:
      'The oats and banana give the carbohydrate the larger share, and the almond butter is what keeps the bowl from emptying too fast. Your answers pointed toward mornings that want this shape.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['nuts', 'gluten'],
    prepMinutes: 10,
    image: 'cs-breakfast-1.jpg',
  },
  {
    id: 'cs-breakfast-2',
    name: 'Whole Grain Toast with Eggs and Roasted Tomatoes',
    type: 'breakfast',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Whole grain bread', 'Eggs', 'Tomatoes', 'Olive oil', 'Basil'],
    summary: 'Two slices of toast with eggs and roasted tomatoes',
    whyItFits:
      'Toast leads, eggs follow, and the roasted tomatoes lift it out of being plain. The bread is the larger part here on purpose rather than by accident.',
    flags: ['vegetarian', 'dairy_free', 'fish_free', 'pork_free'],
    allergens: ['eggs', 'gluten'],
    prepMinutes: 15,
    image: 'cs-breakfast-2.jpg',
  },
  {
    id: 'cs-breakfast-3',
    name: 'Yogurt Bowl with Granola, Mango and Pumpkin Seeds',
    type: 'breakfast',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Plain yogurt', 'Oat granola', 'Mango', 'Pumpkin seeds'],
    summary: 'Yogurt under granola, mango and seeds',
    whyItFits:
      'Fruit and granola carry the carbohydrate while the yogurt and seeds keep some protein in the bowl. Sweet without being only sweet, which is the distinction that usually matters.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'gluten'],
    prepMinutes: 5,
    image: 'cs-breakfast-3.jpg',
  },
  {
    id: 'cs-breakfast-4',
    name: 'Sweet Potato and Black Bean Breakfast Bowl with Salsa',
    type: 'breakfast',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Sweet potato', 'Black beans', 'Tomato salsa', 'Coriander', 'Lime', 'Olive oil'],
    summary: 'Roasted sweet potato with black beans and salsa',
    whyItFits:
      'Sweet potato takes the larger share and the beans bring the protein alongside it, which is the arrangement your responses leaned toward. Savory, which suits a morning that does not want fruit.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 25,
    image: null,
  },
  {
    id: 'cs-breakfast-5',
    name: 'Rice Porridge with Apple, Raisins and Cinnamon',
    type: 'breakfast',
    pattern: 'carb_supportive',
    protein: 'Lighter',
    carbohydrate: 'Higher',
    fat: 'Lighter',
    ingredients: ['Short grain rice', 'Apple', 'Raisins', 'Cinnamon', 'Milk or water'],
    summary: 'Soft cooked rice with apple, raisins and cinnamon',
    whyItFits:
      'Gentle on the stomach and firmly carbohydrate led, which is a useful combination on a morning when appetite is slow to arrive. The fruit does the sweetening.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 20,
    image: 'cs-breakfast-5.jpg',
  },
  {
    id: 'cs-breakfast-6',
    name: 'Turkey Sausage with Roasted Potatoes and Apple',
    type: 'breakfast',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Turkey sausage', 'New potatoes', 'Apple', 'Olive oil', 'Sage'],
    summary: 'Turkey sausage with roasted potatoes and apple slices',
    whyItFits:
      'The potatoes are the larger part of this plate and the sausage keeps some protein in it. A cooked breakfast that stays on the carbohydrate side of the line.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 25,
    image: null,
  },

  // ---------------- lunch ----------------
  {
    id: 'cs-lunch-1',
    name: 'Chicken, Quinoa and Roasted Squash Bowl',
    type: 'lunch',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Chicken breast', 'Quinoa', 'Butternut squash', 'Spinach', 'Olive oil', 'Lemon'],
    summary: 'Quinoa and roasted squash under sliced chicken',
    whyItFits:
      'Quinoa and squash together make the carbohydrate the biggest part of the bowl, with the chicken there in a moderate portion rather than a large one. Built to support an afternoon that holds.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 30,
    image: null,
  },
  {
    id: 'cs-lunch-2',
    name: 'Rice and Black Bean Burrito Bowl with Corn and Salsa',
    type: 'lunch',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Brown rice', 'Black beans', 'Sweetcorn', 'Tomato salsa', 'Avocado', 'Lime', 'Coriander'],
    summary: 'Rice and beans with corn, salsa and avocado',
    whyItFits:
      'Rice and beans is one of the oldest complete pairings there is, and here the rice is the larger half. The avocado is the only fat in it and a little goes a long way.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 20,
    image: 'cs-lunch-2.jpg',
  },
  {
    id: 'cs-lunch-3',
    name: 'Sweet Potato, Lentil and Kale Salad with Lemon',
    type: 'lunch',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Sweet potato', 'Green lentils', 'Kale', 'Red onion', 'Olive oil', 'Lemon'],
    summary: 'Roasted sweet potato and lentils through dressed kale',
    whyItFits:
      'Sweet potato takes the leading role and lentils keep protein in the picture without crowding it out. Good warm on the day and good cold the next.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 30,
    image: null,
  },
  {
    id: 'cs-lunch-4',
    name: 'Whole Grain Pasta with Tomato, Basil and White Beans',
    type: 'lunch',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Whole grain pasta', 'Tomatoes', 'Cannellini beans', 'Basil', 'Garlic', 'Olive oil'],
    summary: 'Pasta in tomato sauce with white beans stirred through',
    whyItFits:
      'The beans are what turn a plate of pasta into a lunch with protein in it, and they do it without changing what the meal is. Carbohydrate leads, as your responses suggested it can.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['gluten'],
    prepMinutes: 20,
    image: null,
  },
  {
    id: 'cs-lunch-5',
    name: 'Tuna and Rice Salad with Peas and Sweetcorn',
    type: 'lunch',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Lighter',
    ingredients: ['Tinned tuna', 'Brown rice', 'Peas', 'Sweetcorn', 'Spring onion', 'Olive oil', 'Lemon'],
    summary: 'Cold rice salad with tuna, peas and sweetcorn',
    whyItFits:
      'Built from rice that is already cooked and a tin from the cupboard, with the rice as the larger part. Light on fat and easy to eat away from a kitchen.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish'],
    prepMinutes: 15,
    image: 'cs-lunch-5.jpg',
  },
  {
    id: 'cs-lunch-6',
    name: 'Barley and Roasted Vegetable Salad with Feta',
    type: 'lunch',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Pearl barley', 'Courgette', 'Red pepper', 'Red onion', 'Feta', 'Olive oil', 'Parsley'],
    summary: 'Barley with roasted vegetables and crumbled feta',
    whyItFits:
      'Barley holds its shape and holds an afternoon, and the feta adds just enough protein and salt to finish it. A grain salad that does not go soft by lunchtime.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'gluten'],
    prepMinutes: 30,
    image: 'cs-lunch-6.jpg',
  },

  // ---------------- dinner ----------------
  {
    id: 'cs-dinner-1',
    name: 'Chicken with Roasted Root Vegetables and Rice',
    type: 'dinner',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Chicken thighs', 'Carrot', 'Parsnip', 'Brown rice', 'Olive oil', 'Thyme'],
    summary: 'Roast root vegetables and rice with chicken',
    whyItFits:
      'Roots and rice together make the carbohydrate the larger share of the plate, and the chicken sits alongside rather than in front. An evening meal that is meant to leave you settled.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 35,
    image: 'cs-dinner-1.jpg',
  },
  {
    id: 'cs-dinner-2',
    name: 'Salmon with Sweet Potato Mash and Green Beans',
    type: 'dinner',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Salmon fillet', 'Sweet potato', 'Green beans', 'Olive oil', 'Lemon'],
    summary: 'Salmon over sweet potato mash with green beans',
    whyItFits:
      'The mash is generous and the salmon is a moderate piece, which puts the weight of the plate on the carbohydrate side. The fish supplies the fat so the mash does not need butter.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish'],
    prepMinutes: 25,
    image: 'cs-dinner-2.jpg',
  },
  {
    id: 'cs-dinner-3',
    name: 'Lentil Bolognese with Whole Grain Spaghetti',
    type: 'dinner',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Green lentils', 'Tomatoes', 'Carrot', 'Celery', 'Onion', 'Whole grain spaghetti', 'Olive oil', 'Oregano'],
    summary: 'Lentil ragu over whole grain spaghetti',
    whyItFits:
      'Lentils behave a great deal like mince in a sauce and bring protein with them, while the pasta stays the main event. A pot of the sauce covers more than one evening.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['gluten'],
    prepMinutes: 30,
    image: 'cs-dinner-3.jpg',
  },
  {
    id: 'cs-dinner-4',
    name: 'Vegetable Paella with Peas and Peppers',
    type: 'dinner',
    pattern: 'carb_supportive',
    protein: 'Lighter',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Short grain rice', 'Peas', 'Red pepper', 'Green beans', 'Onion', 'Garlic', 'Olive oil', 'Paprika'],
    summary: 'One pan of paprika rice with peas and peppers',
    whyItFits:
      'Rice is unapologetically the centre of this one, with vegetables through it rather than beside it. Made in a single pan, which is most of why it gets made at all.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 35,
    image: null,
  },
  {
    id: 'cs-dinner-5',
    name: 'Prawn and Vegetable Stir Fry with Rice Noodles',
    type: 'dinner',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Lighter',
    ingredients: ['Prawns', 'Rice noodles', 'Pak choi', 'Carrot', 'Ginger', 'Garlic', 'Soy sauce', 'Sesame oil'],
    summary: 'Rice noodles and vegetables tossed with prawns',
    whyItFits:
      'Noodles take the larger share and the prawns cook in about two minutes, which makes this the fastest dinner in the set. Light on fat and still properly filling.',
    flags: ['dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['shellfish', 'soy', 'gluten'],
    prepMinutes: 20,
    image: 'cs-dinner-5.jpg',
  },
  {
    id: 'cs-dinner-6',
    name: 'Roast Pork with Apple, Red Cabbage and Potatoes',
    type: 'dinner',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Pork shoulder', 'Apple', 'Red cabbage', 'Potatoes', 'Olive oil', 'Bay leaf'],
    summary: 'Slow roast pork with apple, cabbage and potatoes',
    whyItFits:
      'The potatoes and apple take up most of the plate and the pork is carved in a moderate portion. Long in the oven and short on attention, which suits a slower evening.',
    flags: ['dairy_free', 'egg_free', 'fish_free'],
    allergens: [],
    prepMinutes: 45,
    image: 'cs-dinner-6.jpg',
  },

  // ---------------- snack ----------------
  {
    id: 'cs-snack-1',
    name: 'Banana with a Handful of Almonds',
    type: 'snack',
    pattern: 'carb_supportive',
    protein: 'Lighter',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Banana', 'Almonds'],
    summary: 'A banana and a small handful of almonds',
    whyItFits:
      'The banana is the fuel and the almonds are what slow it down a little. Two things, no packaging, nothing to prepare.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['nuts'],
    prepMinutes: 2,
    image: null,
  },
  {
    id: 'cs-snack-2',
    name: 'Rice Cakes with Avocado and Tomato',
    type: 'snack',
    pattern: 'carb_supportive',
    protein: 'Lighter',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Rice cakes', 'Avocado', 'Tomato', 'Sea salt', 'Lemon'],
    summary: 'Rice cakes topped with smashed avocado and tomato',
    whyItFits:
      'Rice cakes on their own pass straight through, and the avocado is what gives this some staying power. Light, crisp and quick to put together.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 5,
    image: null,
  },
  {
    id: 'cs-snack-3',
    name: 'Yogurt with Granola and Blueberries',
    type: 'snack',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Lighter',
    ingredients: ['Plain yogurt', 'Oat granola', 'Blueberries'],
    summary: 'Yogurt with granola and a handful of blueberries',
    whyItFits:
      'Granola and fruit give the carbohydrate the larger share while the yogurt keeps a little protein underneath it. A small bowl rather than a large one is the whole trick.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy', 'gluten'],
    prepMinutes: 3,
    image: 'cs-snack-3.jpg',
  },
  {
    id: 'cs-snack-4',
    name: 'Orange Slices with Pumpkin Seeds',
    type: 'snack',
    pattern: 'carb_supportive',
    protein: 'Lighter',
    carbohydrate: 'Higher',
    fat: 'Moderate',
    ingredients: ['Orange', 'Pumpkin seeds'],
    summary: 'A sliced orange with toasted pumpkin seeds',
    whyItFits:
      'Fruit with seeds beside it lasts noticeably longer than fruit alone. Refreshing rather than heavy, which suits a warm afternoon.',
    flags: ['vegetarian', 'dairy_free', 'egg_free', 'fish_free', 'pork_free'],
    allergens: [],
    prepMinutes: 3,
    image: null,
  },
  {
    id: 'cs-snack-5',
    name: 'Cottage Cheese with Pineapple',
    type: 'snack',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Lighter',
    ingredients: ['Cottage cheese', 'Pineapple', 'Black pepper'],
    summary: 'Cottage cheese with fresh pineapple',
    whyItFits:
      'Sweet fruit and a mild protein together, with almost no fat in it. Useful late in the evening when something heavier would sit badly.',
    flags: ['vegetarian', 'egg_free', 'fish_free', 'pork_free'],
    allergens: ['dairy'],
    prepMinutes: 3,
    image: null,
  },
  {
    id: 'cs-snack-6',
    name: 'Tuna on Rice Cakes with Cucumber',
    type: 'snack',
    pattern: 'carb_supportive',
    protein: 'Moderate',
    carbohydrate: 'Higher',
    fat: 'Lighter',
    ingredients: ['Tinned tuna', 'Rice cakes', 'Cucumber', 'Lemon', 'Black pepper'],
    summary: 'Tuna and cucumber on rice cakes',
    whyItFits:
      'Savory rather than sweet, and the tuna gives a light carbohydrate snack something to hold on to. Assembled in about the time it takes to boil a kettle.',
    flags: ['dairy_free', 'egg_free', 'pork_free'],
    allergens: ['fish'],
    prepMinutes: 5,
    image: null,
  },
];

/** Every meal in the library, in pattern then meal type then authored order. */
export const FPA_MEALS: FpaMeal[] = [...PROTEIN_SUPPORTIVE, ...BALANCED_FUEL, ...CARB_SUPPORTIVE];

/** One meal by id, or null. Never throws on an id stored before a content edit removed it. */
export function fpaMealById(id: string): FpaMeal | null {
  return FPA_MEALS.find((meal) => meal.id === id) ?? null;
}
