/**
 * No internal or diagnostic language reaches a member.
 *
 * Two halves, deliberately.
 *
 *   1. The rules, as pure functions: what a program is called, what the
 *      interim description says, and which stored text is suppressed.
 *   2. The rendered screens, against a workout carrying the EXACT strings
 *      a real assigned workout on production carries today. A member never
 *      sees a pattern name, a severity, "auto-generated" or a generation
 *      seed, and the assertion is made on real HTML rather than on source
 *      text, so a future refactor that reintroduces a leak fails here.
 *
 * The coach side is asserted too, in the negative: the clinical names must
 * still be exactly what they were, because a coach reads a finding and a
 * member reads a program.
 */
import { describe, it, expect, vi } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import type {
  CoachAssignedWorkout,
  CoachAssignedWorkoutWithContent,
} from '@mef/shared-types-contracts';
import {
  MEMBER_FORBIDDEN_PHRASES,
  MEMBER_PROGRAM_NAME,
  blueprintKeysOf,
  containsClinicalLanguage,
  isGeneratedProgram,
  memberProgramBlurb,
  memberProgramFocus,
  memberProgramName,
  memberSafeText,
  memberSessionBlurb,
  memberSessionLabel,
  memberWorkoutTitle,
} from '../lib/programs/memberPresentation';
import { buildMemberProgramViews, currentProgramEntry } from '../lib/program-lifecycle/memberView';
import { CORRECTIVE_BLUEPRINTS } from '../lib/corrective-engine/blueprints';
import { BLUEPRINT_KEYS } from '../lib/corrective-engine/types';
import { MemberProgramsList } from '../components/coach-program-builder/MemberProgramsList';
import { MemberAssignedWorkoutDetail } from '../components/coach-program-builder/MemberAssignedWorkoutDetail';
import { AssignedProgramsCard } from '../components/AssignedProgramsCard';

vi.mock('next/navigation', () => ({
  useRouter: () => ({ push: () => {}, refresh: () => {}, replace: () => {}, back: () => {} }),
}));

/** Real components, real HTML, then the text a member actually reads. Same convention as tests/coach-dashboard.test.tsx. */
function renderedText(element: React.ReactElement): string {
  return renderToStaticMarkup(element)
    .replace(/<[^>]*>/g, ' ')
    .replace(/&quot;/g, '"')
    .replace(/&#x27;|&apos;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// The exact values a real assigned workout carries on production today.
// Copied verbatim, so this test is measuring the actual leak rather than a
// tidied-up impression of it.
const LIVE_TITLE = 'Corrective: Lower Cross: Session A';
const LIVE_DESCRIPTION =
  'Auto-generated 4-week corrective phase for Ebony (Lower Cross (moderate)). Session A of 3/week, ' +
  'this weekly session set repeats identically across all 4 weeks of the phase. Generated with seed ' +
  '"ab25b880-e067-4345-88f1-59044f3b8bfc:1787019973359".';
const LIVE_COACH_NOTES =
  'Generated by the Corrective Program Generator Engine, not yet reviewed. Detected patterns: ' +
  'Lower Cross (moderate). Overall severity (worst finding): moderate.';
// The per-block and per-exercise reasoning, also copied verbatim from
// production. THE LIVE RUN FOUND THESE: the first pass of this test had
// them as null, so it passed while the real session screen still printed
// "long/underactive in Lower Cross" under every exercise.
const LIVE_BLOCK_REASONING =
  "Myofascial release for this member's tight muscles (Lower Cross), always first, never touches " +
  'the long/weak side of the pattern.';
const LIVE_SELECTION_REASONING =
  'Stability/strengthening work for hamstrings (long/underactive in Lower Cross).';
const LIVE_PROGRAM_TAGS = [
  'corrective-program:46470b1d-490a-4638-a60d-0e4358dc126a',
  'corrective-generated',
  'corrective-member:ab25b880-e067-4345-88f1-59044f3b8bfc',
  'corrective-severity:moderate',
];

function workout(overrides: Partial<CoachAssignedWorkout> = {}): CoachAssignedWorkout {
  return {
    id: 'w1',
    assignment_id: 'a1',
    member_id: 'm1',
    coach_id: 'c1',
    scheduled_date: '2026-08-24',
    occurrence_label: null,
    template_name: LIVE_TITLE,
    description: LIVE_DESCRIPTION,
    goal: 'corrective',
    difficulty: 'intermediate',
    estimated_duration_minutes: null,
    equipment: [],
    program_tags: LIVE_PROGRAM_TAGS,
    corrective_tags: ['lower_cross'],
    movement_tags: [],
    target_muscles: [],
    member_instructions: null,
    coach_notes: LIVE_COACH_NOTES,
    internal_notes: null,
    status: 'not_started',
    ...overrides,
  } as CoachAssignedWorkout;
}

function workoutWithContent(): CoachAssignedWorkoutWithContent {
  return {
    ...workout(),
    member_feedback: null,
    sections: [
      {
        id: 's1',
        assigned_workout_id: 'w1',
        member_id: 'm1',
        coach_id: 'c1',
        name: 'Release',
        section_type: 'corrective',
        sequence_index: 0,
        block_reasoning: LIVE_BLOCK_REASONING,
        exercises: [
          {
            id: 'e1',
            assigned_workout_id: 'w1',
            section_id: 's1',
            member_id: 'm1',
            coach_id: 'c1',
            provider: 'your_move',
            external_id: 'quad-roll',
            exercise_name: 'Quadriceps Roll',
            sequence_index: 0,
            sets: 1,
            reps: null,
            rep_range_low: null,
            rep_range_high: null,
            time_seconds: null,
            distance_meters: null,
            rest_seconds: 15,
            tempo: null,
            rpe: null,
            load: null,
            load_unit: null,
            resistance: null,
            band_color: null,
            side: null,
            unilateral: false,
            hold_duration_seconds: 60,
            frequency: null,
            priority: 'medium',
            is_required: true,
            notes: null,
            coaching_cues: null,
            pain_modification_notes: null,
            alternate_exercises: {},
            selection_reasoning: LIVE_SELECTION_REASONING,
            status: 'not_started',
            difficulty_rating: null,
            comfort_rating: null,
            member_notes: null,
          },
        ],
      },
    ],
  } as unknown as CoachAssignedWorkoutWithContent;
}

function lifecycleRow(overrides: Record<string, unknown> = {}) {
  return {
    id: 'a1',
    member_id: 'm1',
    template_name_snapshot: LIVE_TITLE,
    program_group_key: 'corrective-program:46470b1d',
    status: 'active' as const,
    start_date: '2026-08-19',
    end_date: '2026-09-15',
    duration_weeks: 4,
    current_week: 1,
    paused_days: 0,
    started_at: null,
    completed_at: null,
    paused_at: null,
    resumed_at: null,
    replaced_at: null,
    replaced_by_assignment_id: null,
    schedule_type: 'weekly' as const,
    schedule_config: { type: 'weekly' as const, startDate: '2026-08-19', daysOfWeek: [1], weeks: 4 },
    published_at: '2026-08-17T00:00:00Z',
    created_at: '2026-08-17T00:00:00Z',
    updated_at: '2026-08-17T00:00:00Z',
    ...overrides,
  };
}

/** Every phrase this product refuses to put in front of a member. */
function assertNothingClinical(text: string) {
  for (const phrase of MEMBER_FORBIDDEN_PHRASES) {
    expect(text.toLowerCase()).not.toContain(phrase);
  }
  expect(text).not.toContain('—');
  // The generation seed is a uuid followed by a millisecond timestamp.
  expect(text).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i);
}

describe('the naming map', () => {
  it('gives every pattern a member-facing name about the body, not the finding', () => {
    expect(MEMBER_PROGRAM_NAME).toEqual({
      lower_cross: 'Hip and Core Foundation',
      upper_cross: 'Shoulder and Posture Foundation',
      flat_back: 'Back and Core Foundation',
      forward_head: 'Neck and Posture Foundation',
    });
  });

  it('covers every blueprint the engine can produce, so a new one cannot ship unmapped', () => {
    for (const key of BLUEPRINT_KEYS) {
      expect(MEMBER_PROGRAM_NAME[key]).toBeTruthy();
      assertNothingClinical(MEMBER_PROGRAM_NAME[key]);
    }
  });

  it('leaves the coach-facing clinical names exactly as they were', () => {
    expect(CORRECTIVE_BLUEPRINTS.lower_cross.name).toBe('Lower Cross');
    expect(CORRECTIVE_BLUEPRINTS.upper_cross.name).toBe('Upper Cross');
    expect(CORRECTIVE_BLUEPRINTS.flat_back.name).toBe('Flat Back');
    expect(CORRECTIVE_BLUEPRINTS.forward_head.name).toBe('Forward Head');
  });

  it('reads the name off the assignment’s own corrective_tags', () => {
    expect(
      memberProgramName({ templateName: LIVE_TITLE, correctiveTags: ['lower_cross'] })
    ).toBe('Hip and Core Foundation');
    expect(blueprintKeysOf(['lower_cross', 'not_a_pattern'])).toEqual(['lower_cross']);
  });

  it('names a two-pattern program for the whole body rather than reciting both findings', () => {
    const name = memberProgramName({
      templateName: 'Corrective: Lower Cross + Upper Cross: Session A',
      correctiveTags: ['lower_cross', 'upper_cross'],
    });
    expect(name).toBe('Whole Body Foundation');
    assertNothingClinical(name);
  });

  it('scrubs the stored title when there are no tags to read, which is the pre-existing-row case', () => {
    const name = memberProgramName({ templateName: LIVE_TITLE, correctiveTags: [] });
    assertNothingClinical(name);
    expect(name).toBe('Hip and Core Foundation');
  });

  it('leaves a coach-authored program name completely alone', () => {
    expect(memberProgramName({ templateName: 'Shoulder Reset', correctiveTags: [] })).toBe(
      'Shoulder Reset'
    );
  });

  it('keeps the session letter, because she needs to tell A from B', () => {
    expect(memberSessionLabel(LIVE_TITLE)).toBe('Session A');
    expect(memberSessionLabel('Shoulder Reset')).toBeNull();
    expect(memberWorkoutTitle({ templateName: LIVE_TITLE, correctiveTags: ['lower_cross'] })).toBe(
      'Hip and Core Foundation, Session A'
    );
  });
});

describe('the interim description', () => {
  it('says the length, the cadence and the focus, and claims nothing else', () => {
    const blurb = memberProgramBlurb({
      correctiveTags: ['lower_cross'],
      durationWeeks: 4,
      sessionsPerWeek: 3,
    });
    expect(blurb).toBe(
      'A 4 week program from your coach, 3 sessions a week. It focuses on your hips, deep core and glutes.'
    );
    assertNothingClinical(blurb);
  });

  it('degrades gracefully when a fact is missing rather than inventing one', () => {
    expect(memberProgramBlurb({ correctiveTags: [], durationWeeks: null, sessionsPerWeek: null }))
      .toBe('A program from your coach.');
    expect(memberProgramBlurb({ correctiveTags: ['flat_back'], durationWeeks: 4 })).toBe(
      'A 4 week program from your coach. It focuses on your lower back, hips and deep core.'
    );
  });

  it('the one-session version names the session and the focus', () => {
    const blurb = memberSessionBlurb({ templateName: LIVE_TITLE, correctiveTags: ['lower_cross'] });
    expect(blurb).toBe(
      'Session A of your program from your coach. It focuses on your hips, deep core and glutes.'
    );
    assertNothingClinical(blurb);
  });

  it('every focus phrase is plain body language', () => {
    for (const key of BLUEPRINT_KEYS) {
      const focus = memberProgramFocus([key]);
      expect(focus).toBeTruthy();
      assertNothingClinical(focus!);
    }
  });
});

describe('suppressing stored text that was frozen before this existed', () => {
  it('recognises the generator’s own description and coach note', () => {
    expect(containsClinicalLanguage(LIVE_DESCRIPTION)).toBe(true);
    expect(containsClinicalLanguage(LIVE_COACH_NOTES)).toBe(true);
    expect(memberSafeText(LIVE_DESCRIPTION)).toBeNull();
    expect(memberSafeText(LIVE_COACH_NOTES)).toBeNull();
  });

  it('recognises the per-block and per-exercise reasoning, which is coach vocabulary throughout', () => {
    expect(memberSafeText(LIVE_BLOCK_REASONING)).toBeNull();
    expect(memberSafeText(LIVE_SELECTION_REASONING)).toBeNull();
    // Every distinct string of it on production today, verbatim.
    for (const reasoning of [
      "The main corrective work: strengthening this pattern's long, underactive muscles with a stability emphasis (Lower Cross).",
      'Stretch and active mobility work for the ranges this pattern restricts (Lower Cross).',
      'Core-stability (anti-movement) work only, always the final block, never spinal-flexion.',
      'Core-stability work targeting this program\u2019s deep-stabilizer focus.',
      'Stability/strengthening work for glutes (long/underactive in Lower Cross).',
    ]) {
      expect(memberSafeText(reasoning)).toBeNull();
    }
  });

  it('passes a coach’s own words through untouched', () => {
    const note = 'Take the first week easy and tell me how your hips feel.';
    expect(memberSafeText(note)).toBe(note);
    expect(containsClinicalLanguage(note)).toBe(false);
  });

  it('treats an empty or whitespace-only field as nothing to show', () => {
    expect(memberSafeText('')).toBeNull();
    expect(memberSafeText('   ')).toBeNull();
    expect(memberSafeText(null)).toBeNull();
  });

  it('knows a generated program from a coach-authored one', () => {
    expect(isGeneratedProgram(LIVE_PROGRAM_TAGS)).toBe(true);
    expect(isGeneratedProgram([])).toBe(false);
  });
});

describe('the rendered member screens', () => {
  it('My Programs shows the friendly name and nothing clinical', () => {
    const views = buildMemberProgramViews([lifecycleRow()], [workout()]);
    const text = renderedText(<MemberProgramsList programs={views} workouts={[workout()]} />);

    expect(text).toContain('Hip and Core Foundation');
    expect(text).toContain('Hip and Core Foundation, Session A');
    expect(text).toContain('A 4 week program from your coach');
    assertNothingClinical(text);
  });

  it('the workout screen shows the friendly name, a composed description, and no coach boilerplate', () => {
    const text = renderedText(<MemberAssignedWorkoutDetail workout={workoutWithContent()} />);

    expect(text).toContain('Hip and Core Foundation, Session A');
    expect(text).toContain('Session A of your program from your coach.');
    expect(text).not.toContain('From your coach:');
    // The line the live run caught. It is not shown at all while the only
    // text behind it is written for a coach.
    expect(text).not.toContain('Why this exercise');
    // The exercise itself, its dose and its block name are still hers.
    expect(text).toContain('Quadriceps Roll');
    expect(text).toContain('Release');
    assertNothingClinical(text);
  });

  it('a coach’s real note still reaches her on that screen', () => {
    const withNote = {
      ...workoutWithContent(),
      coach_notes: 'Take the first week easy and tell me how your hips feel.',
    };
    const text = renderedText(<MemberAssignedWorkoutDetail workout={withNote} />);
    expect(text).toContain('From your coach:');
    expect(text).toContain('Take the first week easy');
    assertNothingClinical(text);
  });

  it('the Home card names the program, says the week, and offers the next session', () => {
    const views = buildMemberProgramViews([lifecycleRow()], [workout()]);
    const entry = currentProgramEntry(views, '2026-08-20');
    const text = renderedText(
      <AssignedProgramsCard program={entry!.program} nextWorkout={entry!.nextWorkout} />
    );

    expect(text).toContain('Hip and Core Foundation');
    expect(text).toContain('Week 1 of 4');
    expect(text).toContain('Next up: Session A, Monday, August 24');
    expect(text).toContain('Open your next session');
    // The framing this replaced.
    expect(text).not.toMatch(/workouts? waiting for you/i);
    expect(text).not.toContain('Your coach assigned');
    assertNothingClinical(text);
  });

  it('the Home card renders nothing at all when she is not on a program', () => {
    expect(renderedText(<AssignedProgramsCard program={null} nextWorkout={null} />)).toBe('');
  });
});

describe('what the member reaches, and where from', () => {
  it('the next session is the earliest unfinished one from today onward', () => {
    const views = buildMemberProgramViews(
      [lifecycleRow()],
      [
        workout({ id: 'w1', scheduled_date: '2026-08-24', status: 'completed' }),
        workout({ id: 'w2', scheduled_date: '2026-08-26' }),
        workout({ id: 'w3', scheduled_date: '2026-08-28' }),
      ]
    );
    expect(currentProgramEntry(views, '2026-08-25')!.nextWorkout!.id).toBe('w2');
  });

  it('a member who is behind is offered the session she missed, not silence', () => {
    const views = buildMemberProgramViews(
      [lifecycleRow()],
      [workout({ id: 'w1', scheduled_date: '2026-08-19' })]
    );
    expect(currentProgramEntry(views, '2026-08-25')!.nextWorkout!.id).toBe('w1');
  });

  it('a finished program is never what Home or Movement points at', () => {
    const views = buildMemberProgramViews([lifecycleRow({ status: 'completed' })], [workout()]);
    expect(currentProgramEntry(views, '2026-08-25')).toBeNull();
  });
});
