/**
 * "Nothing about the member experience changes except receiving the
 * program... no 'generated' labeling, no Your Move branding." Source-scan
 * over every file a member's own assigned-program pages actually render,
 * plus a check that this task's own migration never touched the tables
 * those pages read from.
 *
 * Proven non-vacuous by hand during this task: temporarily added the
 * string "Generated by Your Move" to MemberProgramsList.tsx, re-ran this
 * file, watched the first test fail, then removed it.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, it, expect } from 'vitest';

const MEMBER_FACING_FILES = [
  '../components/coach-program-builder/MemberProgramsList.tsx',
  '../components/coach-program-builder/MemberAssignedWorkoutDetail.tsx',
  '../app/programs/page.tsx',
  '../app/programs/[id]/page.tsx',
];

const FORBIDDEN_PATTERNS = [/generat/i, /your\s*move/i, /ymove/i];

describe('member-facing assigned-program rendering has zero generation-awareness', () => {
  for (const relativePath of MEMBER_FACING_FILES) {
    it(`${relativePath} never mentions generation or Your Move`, () => {
      const source = readFileSync(path.resolve(__dirname, relativePath), 'utf-8');
      for (const pattern of FORBIDDEN_PATTERNS) {
        expect(source).not.toMatch(pattern);
      }
    });
  }
});

describe("this feature's migration never touches member-visible program/assignment tables", () => {
  it('migration 122 only creates your_move_generation_log — no ALTER on coach_program_templates or coach_assigned_workouts', () => {
    const migration = readFileSync(
      path.resolve(__dirname, '../../../supabase/migrations/00000000000122_your_move_generation_log.sql'),
      'utf-8'
    ).toLowerCase();
    expect(migration).toContain('create table your_move_generation_log');
    expect(migration).not.toContain('alter table coach_program_templates');
    expect(migration).not.toContain('alter table coach_assigned_workouts');
    expect(migration).not.toContain('alter table coach_assigned_workout_exercises');
  });

  it('saved generated content becomes ordinary coach_program_templates rows via the existing createTemplate/replaceTemplateContent functions — no parallel write path', () => {
    const actionsSource = readFileSync(
      path.resolve(__dirname, '../app/actions/your-move-generation.ts'),
      'utf-8'
    );
    expect(actionsSource).toContain("from '@/lib/coach-program-builder/templates'");
    expect(actionsSource).not.toContain(".from('coach_program_templates')");
    expect(actionsSource).not.toContain(".from('coach_assigned_workouts')");
  });
});
