/**
 * WHAT THE DATA-SCALE GUARD KNOWS ABOUT THE DATABASE.
 *
 * Three lists, each of them a deliberate statement a reviewer can read.
 * tests/data-scale-guard.test.ts and tests/support/dataScaleScan.ts use them,
 * and docs/DATA_SCALE_AUDIT.md explains the method.
 */

import type { ScanOptions } from './dataScaleScan';

/**
 * UNIQUE KEYS, read from production's unique indexes (2026-09-17) for every
 * table the code queries. An equality filter on every column of one of these
 * returns at most one row, so it cannot be truncated. `id` is assumed for
 * every table and is not repeated here.
 *
 * A NEW TABLE, OR A NEW UNIQUE INDEX, is added here by hand from its
 * migration. Regenerate the whole list with:
 *
 *   select t.relname, array_agg(a.attname order by a.attname)
 *   from pg_index i join pg_class t on t.oid = i.indrelid
 *   join pg_namespace n on n.oid = t.relnamespace
 *   join pg_attribute a on a.attrelid = t.oid and a.attnum = any(i.indkey)
 *   where n.nspname = 'public' and i.indisunique and i.indpred is null
 *   group by t.relname, i.indexrelid;
 */
export const UNIQUE_KEYS: Record<string, string[][]> = {
  ai_agents: [['agent_key']],
  ai_rules: [['rule_key']],
  assessment_ai_analyses: [['source_feature', 'source_record_id']],
  assessment_attempts: [['source_id', 'source_table']],
  assessment_definitions: [['key']],
  body_assessment_annotations: [['capture_id']],
  body_assessment_captures: [['assessment_id', 'storage_path']],
  body_assessment_comparisons: [['assessment_a_id', 'assessment_b_id', 'dimension']],
  body_assessment_notes: [['assessment_id']],
  body_landmark_sets: [['capture_id']],
  body_systems_associations: [['entry_code']],
  body_systems_bands: [['band_key']],
  body_systems_copy: [['copy_key']],
  body_systems_questions: [['question_ref']],
  body_systems_red_flags: [['flag_key'], ['position']],
  body_systems_safety_levels: [['level']],
  body_systems_scale_options: [['value_key']],
  body_systems_sections: [['section_key'], ['position']],
  body_systems_settings: [['setting_key']],
  captured_lead_acquisition: [['captured_lead_id']],
  coach_assign_copy: [['copy_key']],
  coach_morning_briefs: [['local_date', 'member_id']],
  coaching_insights: [['category', 'local_date', 'member_id']],
  correlation_candidate_pairs: [['pair_key']],
  cross_system_body_areas: [['area_key'], ['position']],
  cross_system_complaint_classifications: [['position', 'report_id']],
  cross_system_complaint_contexts: [['context_key']],
  cross_system_complaint_lexicon: [['phrase', 'signal_slug']],
  cross_system_complaint_modifiers: [['kind', 'phrase']],
  cross_system_complaint_reports: [['ingest_fingerprint', 'member_id']],
  cross_system_complaint_surfaces: [['surface_key']],
  cross_system_pattern_match_signals: [['match_id', 'role', 'signal_id']],
  cross_system_pattern_matches: [['member_id', 'relationship_id']],
  cross_system_relationship_strength_levels: [['level_key', 'version_id']],
  cross_system_relationship_versions: [['relationship_id', 'version_number']],
  cross_system_relationships: [['pattern_key']],
  cross_system_root_finding_areas: [['finding_id', 'position']],
  cross_system_root_finding_signals: [['area_id', 'signal_id']],
  cross_system_root_finding_triggers: [['finding_id', 'signal_id']],
  cross_system_root_findings: [
    ['relationship_id', 'report_id'],
    ['member_id', 'relationship_id', 'source_key', 'source_session_id'],
  ],
  cross_system_signal_categories: [['category_key'], ['position']],
  cross_system_signal_names: [['signal_slug']],
  cross_system_signal_source_map: [['external_key', 'external_kind', 'source_key']],
  cross_system_signal_source_map_revisions: [
    ['external_key', 'external_kind', 'revision_number', 'source_key'],
  ],
  cross_system_signal_sources: [['source_key'], ['position']],
  cross_system_signals: [['ingest_fingerprint', 'member_id']],
  cross_system_symptom_types: [['symptom_key'], ['position']],
  cvs_experiment_daily_logs: [['experiment_id', 'local_date']],
  daily_checkin_probe_answers: [['local_date', 'member_id', 'question_key']],
  daily_checkins: [['checkin_version', 'local_date', 'user_id']],
  daily_feed_items: [['local_date', 'member_id']],
  driver_domains: [['key']],
  driver_goal_weights: [['driver_id', 'goal_key']],
  driver_probe_questions: [['question_key']],
  energy_forecasts: [['forecast_date', 'member_id']],
  evening_reflections: [['local_date', 'member_id']],
  exercise_catalog: [['external_id', 'provider']],
  exercise_extracted_posters: [['external_id', 'provider']],
  food_lens_label_scans: [['scan_id']],
  food_products: [['barcode', 'data_source']],
  fuel_meal_exclusions: [['exclusion_key', 'member_id']],
  fuel_meal_rejections: [['meal_id', 'member_id']],
  fuel_meal_saves: [['meal_id', 'member_id']],
  fuel_meal_slot_state: [['meal_type', 'member_id']],
  fuel_pattern_results: [['session_id']],
  guest_wellness_check_answers: [['question_key', 'session_id']],
  guest_wellness_check_sessions: [['visitor_token'], ['claimed_by']],
  habit_logs: [['habit_id', 'local_date']],
  lead_conversations: [['session_token']],
  mef_content_items: [['content_key']],
  mef_exercise_metadata: [['external_id', 'provider']],
  member_assignment_deliveries: [['assignment_id']],
  member_coaching_decisions: [['local_date', 'member_id']],
  member_coaching_grades: [['grade_key', 'grade_scope', 'member_id']],
  member_coaching_threads: [['member_id', 'thread_key']],
  member_correlation_findings: [['member_id', 'pair_key']],
  member_daily_priorities: [['local_date', 'member_id']],
  member_daily_probe_selections: [['local_date', 'member_id', 'question_key']],
  member_discovery_moments: [['member_id', 'signal_key']],
  member_driver_states: [['driver_id', 'member_id']],
  member_exercise_avoidance: [['external_id', 'member_id', 'provider']],
  member_exercise_favorites: [['external_id', 'member_id', 'provider']],
  member_exercise_recent_views: [['external_id', 'member_id', 'provider']],
  member_feature_visibility: [['feature_key', 'member_id']],
  member_food_preferences: [['member_id']],
  member_goal_progress_checkins: [['local_date', 'member_id']],
  member_health_profiles: [['member_id']],
  member_movement_profiles: [['member_id']],
  member_pattern_states: [['member_id', 'signal_key']],
  member_public_entry_origin: [['member_id'], ['session_id']],
  member_push_deliveries: [['local_date', 'member_id']],
  member_push_subscriptions: [['endpoint', 'member_id']],
  member_recommendation_computations: [['member_id']],
  member_reset_plan_daily_logs: [['local_date', 'plan_id']],
  member_return_greetings: [['gap_start_local_date', 'member_id']],
  member_root_popup_dismissals: [['member_id', 'message_key']],
  member_subscriptions: [['member_id']],
  member_trial_arc_closes: [['member_id']],
  member_trial_arc_deliveries: [['member_id', 'message_key']],
  member_trial_arc_recaps: [['member_id']],
  member_week_focus: [['member_id', 'week_start']],
  member_weekly_reflection_assignments: [['member_id', 'week_start']],
  member_weekly_reflection_deliveries: [['member_id', 'week_start']],
  member_weekly_reflections: [['member_id', 'week_start']],
  member_weekly_reviews: [['member_id', 'week_start']],
  member_whole_body_signal_focus: [['session_id']],
  member_whole_body_signal_question_actions: [['question_key', 'session_id']],
  movement_program_versions: [['program_id', 'version_number']],
  movement_programs: [['key']],
  movement_session_template_slots: [['slot_order', 'template_id']],
  movement_session_templates: [['session_key']],
  nutrition_rule_thresholds: [['key']],
  onboarding_assessment_versions: [['assessment_version']],
  onboarding_questions: [['question_key', 'question_version']],
  product_allergens: [['allergen', 'kind', 'product_id']],
  product_ingredients: [['product_id']],
  product_nutrients: [['product_id']],
  program_blueprint_slots: [
    ['program_version_id', 'session_designation', 'slot_order'],
    ['priority_rank', 'program_version_id', 'session_designation'],
  ],
  public_entry_answers: [['question_key', 'session_id']],
  public_entry_attribution: [['session_id', 'touch']],
  public_entry_links: [['source_code', 'utm_campaign', 'utm_medium']],
  public_entry_sessions: [['visitor_token']],
  public_entry_signup_refs: [['ref_hash']],
  public_entry_sources: [['code']],
  root_energy_forecasts: [['forecast_date', 'member_id']],
  root_score_snapshots: [['local_date', 'member_id']],
  safety_message_templates: [['template_key'], ['classification_level', 'version']],
  unified_assessment_answers: [['question_id', 'session_id']],
  unified_assessment_definitions: [['key']],
  unified_assessment_questions: [['question_key', 'version']],
  user_acquisition: [['member_id'], ['session_id']],
  wearable_connections: [['member_id', 'provider']],
  wearable_daily_metrics: [['local_date', 'member_id', 'metric_code', 'provider']],
  weekly_nutrition_reports: [['member_id', 'week_start']],
  wellness_assessment_answers: [['assessment_id', 'category_id', 'question_number']],
  wellness_assessment_category_scores: [['assessment_id', 'category_id']],
  wellness_coaching_style_profile: [['member_id']],
  wellness_profile_dimensions: [['dimension', 'member_id']],
  whole_body_signal_bands: [['band_key'], ['position']],
  whole_body_signal_branch_rules: [['option_key']],
  whole_body_signal_coaching_questions: [['question_key']],
  whole_body_signal_copy: [['copy_key']],
  whole_body_signal_patterns: [['pattern_key']],
  whole_body_signal_questions: [['question_ref']],
  whole_body_signal_routing_options: [['option_key'], ['position']],
  whole_body_signal_scale_options: [['value_key'], ['position', 'scale_key']],
  whole_body_signal_sections: [['section_key'], ['position']],
  whole_body_signal_settings: [['setting_key']],
  whole_body_signal_zones: [['zone_key'], ['position']],
};

/**
 * FIXED ENUM TABLES: a closed vocabulary that only a migration writes,
 * nothing in the app inserts into, and whose size is set by what it
 * describes rather than by members, time or authoring. Reading one whole is
 * category (c) in the audit. A table that coaches or admins author, or that
 * a migration can keep extending with content (questions, copy, phrases,
 * map entries), does NOT belong here: the lexicon was migration-seeded and
 * crossed the cap in one build.
 */
export const FIXED_SMALL_TABLES: Record<string, string> = {
  body_systems_safety_levels: 'the survey safety levels (2)',
  body_systems_bands: 'the survey score bands (3)',
  body_systems_scale_options: 'the survey answer scale (5)',
  body_systems_red_flags: 'the survey red-flag set (6)',
  body_systems_sections: 'the survey sections, one per body system (11)',
  whole_body_signal_bands: 'the check score bands (4)',
  whole_body_signal_scale_options: 'the check answer scale (8)',
  whole_body_signal_zones: 'the check zones (6)',
  whole_body_signal_routing_options: 'the check routing choices (6)',
  whole_body_signal_branch_rules: 'the check branch rules (6)',
  whole_body_signal_patterns: 'the check pattern set (8)',
  whole_body_signal_sections: 'the check sections (9)',
  whole_body_signal_settings: 'one row per named setting (14)',
  driver_domains: 'the driver domains (7)',
  cross_system_signal_sources: 'one row per signal source system (8)',
  cross_system_complaint_surfaces: 'one row per screen that accepts a complaint (14)',
  cross_system_complaint_contexts: 'the complaint context vocabulary (16)',
  cross_system_signal_categories: 'the signal category taxonomy (20)',
  cross_system_symptom_types: 'the symptom type taxonomy (28)',
  cross_system_body_areas: 'the body area taxonomy (30)',
  nutrition_rule_thresholds: 'one row per nutrition rule (12)',
  ai_agents: 'one row per registered agent (7)',
  ai_rules: 'one row per rules-engine rule (5)',
  coach_assign_copy: 'one row per assign-screen copy slot (20)',
  movement_session_templates: 'the movement session templates (6)',
  safety_message_templates: 'one row per safety message kind',
};

/**
 * EVERY DATABASE FUNCTION THE CODE CALLS, and whether it returns a set of
 * rows. A set-returning function is capped at db-max-rows exactly like a
 * table read. A new rpc fails the guard until it is added here.
 */
export const RPC_RETURNS_SET: Record<string, boolean> = {
  admin_expire_member_access: false,
  admin_list_member_access: true,
  admin_set_member_access: false,
  admin_set_trial_arc_suppression: false,
  analytics_member_scope: true,
  assign_client_to_coach: false,
  claim_member_push_subscription: false,
  // Does not exist: a script probes that no raw-SQL function is exposed.
  exec_sql_readonly: false,
  find_active_registry_entry: true,
  find_active_wellness_identity_observation: true,
  find_active_wellness_insight: true,
  get_member_restricted_topics: false,
  get_my_coaching_tone_preference: false,
  grant_coach_role: false,
  has_active_role: false,
  lead_acquisition_for_email: true,
  list_own_wellness_recommendation_feedback: true,
  member_trial_length_days: false,
  resolve_coaching_escalation: false,
  revoke_assignment: false,
  revoke_coach_role: false,
  set_member_feature_visibility: false,
  set_member_hydration_focus: false,
  submit_daily_checkin: false,
  submit_onboarding: false,
  supersede_registry_entry: false,
  upsert_member_health_profile: false,
  upsert_movement_profile_coach_fields: false,
  upsert_movement_profile_member_fields: false,
  upsert_wellness_coaching_style_profile: false,
  upsert_wellness_profile_dimension: false,
  upsert_wellness_recommendation_feedback: false,
};

export const DATA_SCALE_OPTIONS: ScanOptions = {
  uniqueKeys: UNIQUE_KEYS,
  fixedSmallTables: FIXED_SMALL_TABLES,
  rpcReturnsSet: RPC_RETURNS_SET,
};
