/**
 * The search phrase used to look for a photograph of each meal.
 *
 * WRITTEN BY HAND, NOT DERIVED FROM THE NAME. The exercise library work
 * (BUILD_STATUS, the Wikimedia sourcing run) found a thirty to forty per
 * cent false positive rate matching names to photographs by text alone,
 * and the cure there was never a better regex. Here every phrase names
 * the FOODS rather than the title, because a photograph search engine
 * indexes what is in the picture and not what a coach called the dish.
 *
 * Every candidate these phrases return is still looked at before it is
 * used. The phrase narrows the field; it does not decide.
 */
export const MEAL_QUERIES = {
  'ps-breakfast-1': ['eggs spinach sweet potato', 'fried eggs spinach', 'fried egg plate'],
  'ps-breakfast-2': ['smoked salmon scrambled eggs', 'smoked salmon eggs', 'smoked salmon plate'],
  'ps-breakfast-3': ['greek yogurt walnuts', 'yogurt nuts berries', 'yogurt bowl'],
  'ps-breakfast-4': ['turkey skillet breakfast', 'ground turkey peppers', 'breakfast hash'],
  'ps-breakfast-5': ['black beans avocado bowl', 'black bean bowl', 'black beans'],
  'ps-breakfast-6': ['steak and eggs', 'steak eggs plate', 'steak plate'],
  'ps-lunch-1': ['grilled chicken salad avocado', 'chicken salad avocado', 'chicken salad'],
  'ps-lunch-2': ['tuna bean salad', 'tuna white beans', 'tuna salad'],
  'ps-lunch-3': ['lentil roasted vegetables', 'lentil salad vegetables', 'lentil salad'],
  'ps-lunch-4': ['beef broccoli stir fry', 'beef and broccoli', 'stir fry beef'],
  'ps-lunch-5': ['cottage cheese cucumber', 'cottage cheese tomato', 'cottage cheese'],
  'ps-lunch-6': ['turkey lettuce wraps', 'lettuce wraps', 'minced turkey lettuce'],
  'ps-dinner-1': ['roast chicken green beans', 'chicken thighs vegetables', 'roast chicken plate'],
  'ps-dinner-2': ['baked salmon asparagus', 'salmon asparagus', 'grilled salmon fillet'],
  'ps-dinner-3': ['chickpea spinach curry', 'chickpea curry', 'chana masala'],
  'ps-dinner-4': ['pork tenderloin red cabbage', 'pork tenderloin sliced', 'pork loin plate'],
  'ps-dinner-5': ['eggs tomato pepper sauce', 'shakshuka', 'baked eggs tomato'],
  'ps-dinner-6': ['baked cod broccoli', 'cod fillet vegetables', 'baked cod'],
  'ps-snack-1': ['boiled eggs tomatoes', 'hard boiled eggs', 'boiled egg halves'],
  'ps-snack-2': ['yogurt almonds', 'greek yogurt nuts', 'yogurt with nuts'],
  'ps-snack-3': ['sliced turkey cucumber', 'cold cuts cucumber', 'turkey slices'],
  'ps-snack-4': ['roasted chickpeas', 'spiced chickpeas', 'chickpeas bowl'],
  'ps-snack-5': ['sardines cucumber', 'sardines plate', 'sardines'],
  'ps-snack-6': ['cheese walnuts apple', 'cheddar apple slices', 'cheese and apple'],
  'bf-breakfast-1': ['oatmeal yogurt berries', 'oatmeal raspberries almonds', 'porridge berries'],
  'bf-breakfast-2': ['eggs avocado toast', 'avocado toast egg', 'egg on toast'],
  'bf-breakfast-3': ['sausage eggs potatoes breakfast', 'cooked breakfast potatoes', 'scrambled eggs sausage'],
  'bf-breakfast-4': ['banana oat pancakes', 'pancakes nut butter', 'pancakes banana'],
  'bf-breakfast-5': ['sweet potato hash avocado', 'sweet potato black bean hash', 'sweet potato hash'],
  'bf-breakfast-6': ['cottage cheese peaches', 'cottage cheese fruit toast', 'cottage cheese bowl'],
  'bf-lunch-1': ['chicken rice vegetable bowl', 'chicken brown rice bowl', 'rice bowl chicken'],
  'bf-lunch-2': ['tuna sandwich', 'tuna salad sandwich', 'tuna sandwich plate'],
  'bf-lunch-3': ['lentil soup bread', 'lentil soup', 'soup and bread'],
  'bf-lunch-4': ['turkey avocado wrap', 'wrap sandwich avocado', 'tortilla wrap'],
  'bf-lunch-5': ['greek salad feta', 'greek salad chickpeas', 'greek salad'],
  'bf-lunch-6': ['steak salad potatoes', 'sliced steak salad', 'steak salad'],
  'bf-dinner-1': ['chicken breast potatoes salad', 'pan seared chicken potatoes', 'chicken and potatoes'],
  'bf-dinner-2': ['salmon rice broccoli', 'salmon broccoli plate', 'salmon and rice'],
  'bf-dinner-3': ['chili beans rice', 'beef chili bowl', 'chili con carne'],
  'bf-dinner-4': ['chickpea stew couscous', 'vegetable couscous', 'couscous stew'],
  'bf-dinner-5': ['aubergine lentil bake', 'eggplant bake yogurt', 'moussaka'],
  'bf-dinner-6': ['pork chop squash', 'pork chops apple', 'pork chop plate'],
  'bf-snack-1': ['apple peanut butter', 'apple slices peanut butter', 'peanut butter apple'],
  'bf-snack-2': ['yogurt honey oats', 'yogurt honey', 'yogurt bowl honey'],
  'bf-snack-3': ['crackers cheese grapes', 'cheese and crackers', 'cheese plate grapes'],
  'bf-snack-4': ['hummus carrot cucumber', 'hummus vegetable sticks', 'hummus plate'],
  'bf-snack-5': ['boiled egg toast soldiers', 'soft boiled egg toast', 'boiled egg toast'],
  'bf-snack-6': ['turkey cheese roll ups', 'cold cuts cheese plate', 'charcuterie cheese plate'],
  'cs-breakfast-1': ['oatmeal banana', 'porridge banana cinnamon', 'porridge bowl'],
  'cs-breakfast-2': ['poached eggs toast tomatoes', 'eggs on toast', 'eggs on toast'],
  'cs-breakfast-3': ['yogurt granola mango', 'granola yogurt bowl', 'granola bowl'],
  'cs-breakfast-4': ['sweet potato black bean bowl', 'sweet potato salsa bowl', 'sweet potato bowl'],
  'cs-breakfast-5': ['rice porridge apple', 'rice pudding cinnamon', 'rice pudding'],
  'cs-breakfast-6': ['sausage roasted potatoes', 'sausage potatoes plate', 'roasted potatoes plate'],
  'cs-lunch-1': ['chicken quinoa squash', 'quinoa bowl chicken', 'quinoa salad'],
  'cs-lunch-2': ['rice beans burrito bowl', 'burrito bowl', 'rice and beans'],
  'cs-lunch-3': ['sweet potato lentil salad', 'roasted sweet potato kale', 'roasted sweet potato salad'],
  'cs-lunch-4': ['pasta tomato beans', 'pasta tomato basil', 'pasta with tomato sauce'],
  'cs-lunch-5': ['tuna rice salad', 'rice salad peas corn', 'rice salad'],
  'cs-lunch-6': ['barley salad feta', 'grain salad roasted vegetables', 'barley salad'],
  'cs-dinner-1': ['roast chicken root vegetables', 'chicken rice vegetables', 'roast chicken vegetables'],
  'cs-dinner-2': ['salmon sweet potato mash', 'salmon mashed sweet potato', 'salmon plate'],
  'cs-dinner-3': ['lentil bolognese spaghetti', 'spaghetti lentil sauce', 'spaghetti bolognese'],
  'cs-dinner-4': ['vegetable paella', 'paella pan vegetables', 'paella'],
  'cs-dinner-5': ['prawn noodle stir fry', 'rice noodles prawns', 'stir fried noodles'],
  'cs-dinner-6': ['roast pork red cabbage', 'roast pork potatoes', 'roast pork plate'],
  'cs-snack-1': ['banana almonds', 'banana nuts', 'banana'],
  'cs-snack-2': ['rice cakes avocado', 'rice cake topping', 'rice cakes'],
  'cs-snack-3': ['yogurt granola blueberries', 'granola blueberries', 'granola yogurt'],
  'cs-snack-4': ['orange slices seeds', 'sliced orange plate', 'orange slices'],
  'cs-snack-5': ['cottage cheese pineapple', 'cottage cheese fruit', 'cottage cheese fruit'],
  'cs-snack-6': ['tuna rice cakes', 'rice cakes cucumber', 'rice cakes tuna'],
};
