/**
 * What a member is allowed to read about an assigned program.
 *
 * The corrective engine names and describes a program for the COACH, and
 * everything it writes was reaching the member unchanged. A real assigned
 * workout on production reads, today:
 *
 *   title        "Corrective: Lower Cross: Session A"
 *   description  "Auto-generated 4-week corrective phase for Ebony (Lower
 *                 Cross (moderate)). ... Generated with seed
 *                 "ab25b880-...:1787019973359"."
 *   coach_notes  "Generated by the Corrective Program Generator Engine,
 *                 not yet reviewed. Detected patterns: Lower Cross
 *                 (moderate). Overall severity (worst finding): moderate."
 *
 * A member should never meet a pattern name, a severity, the word
 * "auto-generated", or a generation seed. This module is the one place
 * that decides what she reads instead, so every member surface asks the
 * same question and gets the same answer.
 *
 * NOTHING IS STORED TWICE. The friendly name is derived from
 * `corrective_tags`, which the assignment and its frozen workouts already
 * carry, so the coach's screen and the member's screen read the same row
 * and there is no second copy of a name to drift. The coach keeps the
 * clinical names exactly as they are; this is a display mapping on the way
 * out to a member and nothing more.
 *
 * The composed description is INTERIM COPY. It says only what is safely
 * known from the assignment itself: how long the program runs, how many
 * sessions a week, and the area it works on in plain words. It claims no
 * outcome. The personalized explanation is a later prompt.
 */

import type { BlueprintKey } from '../corrective-engine/types';

/** The tag lib/corrective-engine/save.ts puts on every template it generates. */
export const GENERATED_PROGRAM_TAG = 'corrective-generated';

/**
 * The member-facing name for each corrective pattern. Named for the part
 * of the body the work is on, in words a member uses about herself, never
 * for the finding behind it.
 */
export const MEMBER_PROGRAM_NAME: Record<BlueprintKey, string> = {
  lower_cross: 'Hip and Core Foundation',
  upper_cross: 'Shoulder and Posture Foundation',
  flat_back: 'Back and Core Foundation',
  forward_head: 'Neck and Posture Foundation',
};

/** The same idea again, as the middle of a sentence: what the work is on. Plain words, no claim about what it will achieve. */
export const MEMBER_PROGRAM_FOCUS: Record<BlueprintKey, string> = {
  lower_cross: 'your hips, deep core and glutes',
  upper_cross: 'your shoulders, upper back and chest',
  flat_back: 'your lower back, hips and deep core',
  forward_head: 'your neck, upper back and shoulders',
};

/**
 * Vocabulary that must never reach a member. Used to suppress text that
 * was frozen onto an already-assigned workout before this module existed,
 * and asserted against in tests so a new leak fails the build rather than
 * reaching somebody's phone.
 *
 * Matched case-insensitively as whole phrases. Deliberately includes the
 * generator's own boilerplate openings, the seed marker, and the severity
 * words as they are actually written by the engine.
 */
export const MEMBER_FORBIDDEN_PHRASES: readonly string[] = [
  'lower cross',
  'lower_cross',
  'lower-crossed',
  'lower crossed',
  'upper cross',
  'upper_cross',
  'upper-crossed',
  'upper crossed',
  'flat back',
  'flat_back',
  'forward head',
  'forward_head',
  'auto-generated',
  'autogenerated',
  'corrective phase',
  'corrective program generator',
  'generated with seed',
  'detected patterns',
  'overall severity',
  'worst finding',
  'not yet reviewed',
  'blueprint',
  'postural pattern',
  'crossed pattern',
];

/** True when any forbidden phrase appears. The guard behind every member-facing text field on a generated program. */
export function containsClinicalLanguage(text: string | null | undefined): boolean {
  if (!text) return false;
  const haystack = text.toLowerCase();
  return MEMBER_FORBIDDEN_PHRASES.some((phrase) => haystack.includes(phrase));
}

export function isGeneratedProgram(programTags: readonly string[] | null | undefined): boolean {
  return (programTags ?? []).includes(GENERATED_PROGRAM_TAG);
}

/** The blueprint keys on a program, in the order they were detected. */
export function blueprintKeysOf(
  correctiveTags: readonly string[] | null | undefined
): BlueprintKey[] {
  return (correctiveTags ?? []).filter(
    (tag): tag is BlueprintKey => tag in MEMBER_PROGRAM_NAME
  );
}

/**
 * Strips the ": Session A" suffix the generator appends per weekly
 * session. Returns null when the name carries no session label, which is
 * every coach-authored program.
 */
export function memberSessionLabel(templateName: string | null | undefined): string | null {
  const match = (templateName ?? '').match(/:\s*(Session\s+[A-Z])\s*$/);
  return match?.[1] ?? null;
}

/**
 * Last line of defence for a title this module could not map: strip the
 * "Corrective:" prefix and the session suffix, and replace any clinical
 * name still in it. A title that survives all of that with nothing
 * recognisable in it is a coach's own words and is left alone.
 */
function scrubTitle(templateName: string): string {
  let name = templateName.replace(/^\s*Corrective:\s*/i, '').replace(/:\s*Session\s+[A-Z]\s*$/, '');
  for (const [key, friendly] of Object.entries(MEMBER_PROGRAM_NAME) as [BlueprintKey, string][]) {
    const clinical = key.replace('_', ' ');
    name = name.replace(new RegExp(clinical, 'ig'), friendly);
  }
  return name.trim();
}

export interface ProgramNamingSource {
  templateName: string;
  correctiveTags?: readonly string[] | null;
  programTags?: readonly string[] | null;
}

/**
 * The program's name as a member reads it.
 *
 * Reads `corrective_tags` off the assignment first, because that is the
 * stored fact both the coach's screen and this one are looking at. Falls
 * back to scrubbing the stored title, which is what covers programs
 * assigned before this module existed and whose frozen snapshot cannot be
 * rewritten.
 */
export function memberProgramName(source: ProgramNamingSource): string {
  const keys = blueprintKeysOf(source.correctiveTags);
  if (keys.length === 1) return MEMBER_PROGRAM_NAME[keys[0]!];
  if (keys.length > 1) {
    // Two findings, one program. Naming it after both would be a mouthful
    // and would still be about her posture rather than about her work.
    return 'Whole Body Foundation';
  }
  return scrubTitle(source.templateName) || 'Your program';
}

/** "Hip and Core Foundation, Session A" for a list row, where both facts have to fit on one line. */
export function memberWorkoutTitle(source: ProgramNamingSource): string {
  const name = memberProgramName(source);
  const session = memberSessionLabel(source.templateName);
  return session ? `${name}, ${session}` : name;
}

/** What the program works on, in plain words, or null when nothing is safely known. */
export function memberProgramFocus(
  correctiveTags: readonly string[] | null | undefined
): string | null {
  const keys = blueprintKeysOf(correctiveTags);
  if (keys.length === 0) return null;
  const parts = keys.map((key) => MEMBER_PROGRAM_FOCUS[key]);
  if (parts.length === 1) return parts[0]!;
  return `${parts.slice(0, -1).join(', ')} and ${parts.at(-1)}`;
}

export interface MemberBlurbInput {
  correctiveTags?: readonly string[] | null;
  durationWeeks?: number | null;
  sessionsPerWeek?: number | null;
}

/**
 * The interim description, composed from what is safely known rather than
 * copied from what the engine wrote for the coach. Short, warm, no em
 * dashes, and it promises nothing.
 */
export function memberProgramBlurb(input: MemberBlurbInput): string {
  const weeks = input.durationWeeks && input.durationWeeks > 0 ? input.durationWeeks : null;
  const perWeek =
    input.sessionsPerWeek && input.sessionsPerWeek > 0 ? input.sessionsPerWeek : null;
  const focus = memberProgramFocus(input.correctiveTags);

  const opening = weeks
    ? `A ${weeks} week program from your coach`
    : 'A program from your coach';
  const cadence = perWeek ? `, ${perWeek} session${perWeek === 1 ? '' : 's'} a week` : '';
  const focusLine = focus ? ` It focuses on ${focus}.` : '';

  return `${opening}${cadence}.${focusLine}`;
}

/** The one-session version, for the screen a member opens to do the work. */
export function memberSessionBlurb(input: {
  correctiveTags?: readonly string[] | null;
  templateName: string;
}): string {
  const focus = memberProgramFocus(input.correctiveTags);
  const session = memberSessionLabel(input.templateName);
  const opening = session
    ? `${session} of your program from your coach.`
    : 'Part of your program from your coach.';
  return focus ? `${opening} It focuses on ${focus}.` : opening;
}

/**
 * A stored free-text field on its way to a member. Returns null when the
 * text is the generator's own writing rather than the coach's, which is
 * how the already-frozen descriptions and coach notes on live assignments
 * are kept off her screen without rewriting a snapshot that is supposed to
 * be immutable.
 *
 * A coach's own note passes through untouched, which is the point: this
 * suppresses machine boilerplate, it does not censor a coach.
 */
export function memberSafeText(text: string | null | undefined): string | null {
  const trimmed = (text ?? '').trim();
  if (trimmed === '') return null;
  return containsClinicalLanguage(trimmed) ? null : trimmed;
}
