/**
 * Coach Authority — the engine recommends, the coach approves, nothing is
 * automatically assigned. approvePrescriptionSnapshot() is the only path
 * that turns a prescription_snapshots tree into a real, member-visible
 * assignment: it materializes the (possibly coach-edited) blocks/exercises
 * into a coach_program_templates + coach_program_assignments +
 * coach_assigned_workouts* tree through the exact same Program Builder
 * data layer a coach's own from-scratch program goes through
 * (createTemplate/replaceTemplateContent/createAssignment) — this file
 * introduces no second prescription format. rejectPrescriptionSnapshot()
 * simply records why a run was declined; nothing is ever materialized for
 * a rejected snapshot.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import type {
  PrescriptionBlockType,
  ProgramScheduleConfig,
  ProgramScheduleType,
  ProgramSectionType,
} from '@mef/shared-types-contracts';
import { MOVEMENT_SESSION_SECTION_LABEL } from '@mef/shared-types-contracts';
import { getPrescriptionSnapshotWithContent } from './data';
import {
  createTemplate,
  replaceTemplateContent,
  getTemplateWithContent,
  type TemplateContentSectionInput,
} from '../coach-program-builder/templates';
import { createAssignment } from '../coach-program-builder/assignments';
import { recordTimelineEvent } from '../timeline/data';
import { todaysLocalDate } from '../time/localDate';

/**
 * coach_program_template_sections.section_type is a narrower, independently
 * curated taxonomy (migration 82) than the Program Section taxonomy
 * prescription_blocks.block_type reuses (migration 80/83) — see each
 * migration's own header for why the Program Builder deliberately keeps
 * its own vocabulary. Anything without a direct match becomes 'custom'
 * with the block's real name preserved on the section's `name` field, the
 * same escape hatch the Program Builder UI itself uses for a coach-typed
 * custom section.
 */
const BLOCK_TYPE_TO_SECTION_TYPE: Record<PrescriptionBlockType, ProgramSectionType> = {
  preparation: 'warm_up',
  breathing: 'custom',
  mobility: 'mobility',
  activation: 'activation',
  stability: 'custom',
  strength: 'strength',
  power: 'custom',
  conditioning: 'conditioning',
  recovery: 'recovery',
};

export type ApprovePrescriptionSnapshotInput = {
  snapshotId: string;
  coachId: string;
  templateName: string;
  memberInstructions: string | null;
  scheduleType: ProgramScheduleType;
  scheduleConfig: ProgramScheduleConfig;
  publishImmediately: boolean;
  memberTimezone: string;
};

export type ApprovePrescriptionSnapshotResult = {
  templateId: string;
  assignmentId: string;
};

/** Materializes an approved (possibly coach-edited) snapshot into a real template + assignment, then marks the snapshot 'approved' and frozen. Returns null if the snapshot isn't found, isn't still pending review, or materialization fails partway (in which case the snapshot is left untouched — pending_coach_review — so the coach can retry). */
export async function approvePrescriptionSnapshot(
  supabase: SupabaseClient,
  input: ApprovePrescriptionSnapshotInput
): Promise<ApprovePrescriptionSnapshotResult | null> {
  const snapshot = await getPrescriptionSnapshotWithContent(supabase, input.snapshotId);
  if (!snapshot || snapshot.status !== 'pending_coach_review') return null;
  if (snapshot.blocks.length === 0) return null;

  const template = await createTemplate(supabase, input.coachId, {
    name: input.templateName,
    description: snapshot.strategy_summary,
    goal: snapshot.goals.join(', ') || null,
    difficulty: snapshot.blocks[0]?.difficulty ?? null,
    estimatedDurationMinutes: snapshot.time_available_minutes,
    equipment: snapshot.equipment,
    programTags: [],
    correctiveTags: snapshot.corrective_priorities,
    movementTags: snapshot.blocks.flatMap((b) => b.required_movement_tags),
    targetMuscles: [],
    coachNotes: snapshot.strategy_summary,
    internalNotes: `Generated by the Prescription Intelligence Engine (confidence: ${snapshot.confidence_level}).`,
    memberInstructions: input.memberInstructions,
  });
  if (!template) return null;

  const sections: TemplateContentSectionInput[] = snapshot.blocks.map((block) => ({
    name: MOVEMENT_SESSION_SECTION_LABEL[block.block_type],
    sectionType: BLOCK_TYPE_TO_SECTION_TYPE[block.block_type],
    blockReasoning: block.block_reasoning,
    exercises: block.exercises.map((exercise) => ({
      provider: exercise.provider,
      externalId: exercise.external_id,
      exerciseName: exercise.exercise_name,
      sets: exercise.sets,
      reps: exercise.reps,
      rep_range_low: exercise.rep_range_low,
      rep_range_high: exercise.rep_range_high,
      time_seconds: exercise.time_seconds,
      distance_meters: null,
      rest_seconds: exercise.rest_seconds,
      tempo: exercise.tempo,
      rpe: null,
      load: null,
      load_unit: null,
      resistance: null,
      band_color: null,
      side: exercise.side,
      unilateral: exercise.unilateral,
      hold_duration_seconds: exercise.hold_duration_seconds,
      frequency: null,
      priority: 'medium',
      is_required: true,
      notes: null,
      coaching_cues: null,
      pain_modification_notes: null,
      alternate_exercises: {},
      selectionReasoning: exercise.selection_reasoning,
    })),
  }));

  const contentSaved = await replaceTemplateContent(supabase, template.id, input.coachId, sections);
  if (!contentSaved) return null;

  // Re-fetch with real DB-generated section/exercise ids and sequence
  // indices — createAssignment freezes whatever this object contains, so
  // it must reflect exactly what was just persisted, not the pre-insert
  // input shape.
  const templateWithContent = await getTemplateWithContent(supabase, template.id);
  if (!templateWithContent) return null;

  const assignment = await createAssignment(supabase, {
    memberId: snapshot.member_id,
    coachId: input.coachId,
    template: templateWithContent,
    scheduleType: input.scheduleType,
    scheduleConfig: input.scheduleConfig,
    assignmentNotes: null,
    internalNotes: null,
    publishImmediately: input.publishImmediately,
    sourcePrescriptionSnapshotId: snapshot.id,
  });
  if (!assignment) return null;

  const { error: updateError } = await supabase
    .from('prescription_snapshots')
    .update({
      status: 'approved',
      reviewed_by: input.coachId,
      reviewed_at: new Date().toISOString(),
      resulting_template_id: template.id,
      resulting_assignment_id: assignment.id,
      updated_at: new Date().toISOString(),
    })
    .eq('id', input.snapshotId);
  if (updateError) {
    console.error('approvePrescriptionSnapshot (snapshot update) failed', updateError);
  }

  await recordTimelineEvent(supabase, {
    memberId: snapshot.member_id,
    eventType: 'prescription_approved',
    localDate: todaysLocalDate(input.memberTimezone),
    title: 'Your coach approved a new prescription',
    detail: snapshot.strategy_summary,
    sourceFeature: 'prescription_snapshot',
    sourceRecordId: snapshot.id,
    memberVisible: false,
  });

  return { templateId: template.id, assignmentId: assignment.id };
}

export async function rejectPrescriptionSnapshot(
  supabase: SupabaseClient,
  snapshotId: string,
  coachId: string,
  reason: string,
  memberTimezone: string
): Promise<boolean> {
  const { data: snapshot, error: snapshotError } = await supabase
    .from('prescription_snapshots')
    .update({
      status: 'rejected',
      reviewed_by: coachId,
      reviewed_at: new Date().toISOString(),
      rejection_reason: reason,
      updated_at: new Date().toISOString(),
    })
    .eq('id', snapshotId)
    .select('member_id')
    .single();
  if (snapshotError || !snapshot) {
    console.error('rejectPrescriptionSnapshot failed', snapshotError);
    return false;
  }

  await recordTimelineEvent(supabase, {
    memberId: snapshot.member_id,
    eventType: 'prescription_rejected',
    localDate: todaysLocalDate(memberTimezone),
    title: 'A prescription run was rejected by the coach',
    detail: reason,
    sourceFeature: 'prescription_snapshot',
    sourceRecordId: snapshotId,
    memberVisible: false,
  });

  return true;
}
