-- The MEF Body Systems Survey's coach association library.
--
-- COACH ONLY, PERMANENTLY. Migration 220 gives this table a coach and
-- platform administrator select policy and no member policy at all, so a
-- member session asking for these rows directly gets none. The app draws
-- the same fence a second time in lib/body-systems/associations.ts, which
-- is never imported by anything a member renders, and
-- tests/body-systems-member-language.test.ts proves the import graph.
--
-- POSSIBILITIES, NEVER CONCLUSIONS. Every association_text below is the
-- coach approved sentence, whole, including its cautious frame. The app
-- composes nothing around it: what a coach reads is exactly this column.
-- That is what makes the banned conclusion vocabulary enforceable, and
-- tests/body-systems-associations.test.ts reads these rows through the
-- renderer and fails on has, shows, indicates or confirms.
--
-- EVERY ENTRY DEFINES ITS TRIGGER PRECISELY, and every fired entry cites
-- the member's actual answers that fired it. The trigger vocabulary is
-- documented on the table in migration 220. "Elevated" means Often or
-- Almost always, which is body_systems_scale_options.is_elevated rather
-- than a number repeated in thirty eight triggers. "Cluster" means two or
-- more elevated inside the listed set.
--
-- WHERE A TRIGGER READS NARROWER THAN THE PROSE, it is because the prose
-- named an emphasis rather than a requirement, and the safest literal
-- reading was taken. Both cases are listed in the build report:
--   K-1 fires on K1 and K2 elevated. B9 strengthens it in the prose
--       ("especially with") and is not required.
--   K-2 fires on K4 elevated. Its second clause ("or K3 elevated
--       alongside it") also requires K4, so K4 is the trigger.

insert into body_systems_associations
  (entry_code, position, section_key, branch, title, trigger, association_text, next_step)
values
  ('D-1', 1, 'digestion', 'all', 'Upper digestion cluster', '{"type":"cluster","questions":["D1","D3","D4","D5"],"min":2}'::jsonb, 'Possible considerations include: low stomach acid patterns, slow stomach emptying, reflux-type patterns, eating speed and meal size, stress at meals', 'further questioning on meal timing, eating pace, and stress state while eating; medical evaluation if burning is frequent or long-standing'),
  ('D-2', 2, 'digestion', 'all', 'Lower digestion cluster', '{"type":"cluster","questions":["D6","D7","D8","D10"],"min":2}'::jsonb, 'Possible considerations include: food intolerance patterns, gut flora imbalance, irritable-bowel-type patterns; D7 and D8 both elevated is its own alternating pattern worth naming in session', 'food and symptom timeline questioning; consider discussing with an appropriate healthcare professional if pain is significant or persistent'),
  ('D-3', 3, 'digestion', 'all', 'Absorption pattern (cross-section)', '{"type":"all_elevated","questions":["D10","D2","B8"]}'::jsonb, 'This combination may overlap with patterns sometimes seen in incomplete digestion or absorption', 'these findings may warrant medical evaluation if persistent alongside low energy or weight change'),
  ('B-1', 4, 'blood_sugar', 'all', 'Reactive pattern', '{"type":"cluster","questions":["B1","B5","B7"],"min":2}'::jsonb, 'Possible considerations include: blood sugar regulation patterns, long gaps between meals, meals light on protein', 'meal timing and composition questioning'),
  ('B-2', 5, 'blood_sugar', 'all', 'Post-meal crash pattern', '{"type":"all_elevated","questions":["B2","B8"]}'::jsonb, 'This pattern can be associated with insulin response patterns and refined-carbohydrate-heavy meals', 'what a typical plate looks like; one-week meal and energy log through daily check-ins'),
  ('B-3', 6, 'blood_sugar', 'all', 'Thirst and frequency pattern (cross-section)', '{"type":"all_of","conditions":[{"type":"any_elevated","questions":["B9"]},{"type":"any_elevated","questions":["B6","K2"]}]}'::jsonb, 'This combination may overlap with patterns sometimes seen in blood sugar dysregulation', 'these findings may warrant medical evaluation, including blood glucose testing, if persistent'),
  ('L-1', 7, 'liver', 'all', 'Chemical sensitivity cluster', '{"type":"cluster","questions":["L1","L2","L9"],"min":2}'::jsonb, 'Possible considerations include: clearance and detoxification load patterns', 'exposure questioning (household products, alcohol frequency, medication list awareness)'),
  ('L-2', 8, 'liver', 'all', 'Skin and elimination cluster', '{"type":"cluster","questions":["L4","L5","L8"],"min":2}'::jsonb, 'This pattern can be associated with elimination pathway load and food sensitivity patterns', 'pair with Digestion section findings before concluding anything; further questioning on skin timeline'),
  ('L-3', 9, 'liver', 'all', 'Night waking pattern', '{"type":"all_elevated","questions":["L3","L6"]}'::jsonb, 'Possible considerations include: overnight blood sugar dips and circadian load patterns; traditional frameworks also associate this window with liver load', 'evening meal timing and alcohol questioning; cross-check Blood Sugar section'),
  ('A-1', 10, 'adrenals', 'all', 'Depletion cluster', '{"type":"cluster","questions":["A1","A5","A9"],"min":2}'::jsonb, 'This pattern can be associated with stress-response depletion and under-recovery patterns; overlaps with low thyroid patterns are common, so read both sections together', 'recovery inventory (what actually restores her), sleep quality questioning'),
  ('A-2', 11, 'adrenals', 'all', 'Blood pressure and mineral pattern', '{"type":"cluster","questions":["A3","A4","A10"],"min":2}'::jsonb, 'This combination may overlap with patterns sometimes discussed around blood pressure regulation and stress hormone output', 'these findings may warrant a blood pressure check; hydration and electrolyte questioning'),
  ('A-3', 12, 'adrenals', 'all', 'Inverted rhythm pattern (cross-section)', '{"type":"all_elevated","questions":["A2","A6","N7"]}'::jsonb, 'Possible considerations include: stress hormone rhythm patterns running late', 'evening routine questioning; screen and stimulation timing'),
  ('T-1', 13, 'thyroid', 'all', 'Slow metabolism cluster', '{"type":"min_elevated","questions":["T1","T2","T3","T4","T5","T6","T8"],"min":3}'::jsonb, 'This combination may overlap with patterns sometimes seen in low thyroid function; iron and B12 patterns can look similar', 'these findings may warrant medical evaluation, including a thyroid panel, if persistent'),
  ('T-2', 14, 'thyroid', 'all', 'Endocrine axis pattern (cross-section)', '{"type":"sections_at_band","sections":["thyroid","adrenals","hormonal"],"band":"showing_up"}'::jsonb, 'Possible considerations include: the hormonal axis moving together rather than one gland in isolation', 'coach the foundations (sleep, blood sugar, stress) first; consider discussing the combined pattern with an appropriate healthcare professional if clinically appropriate'),
  ('H-1', 15, 'heart', 'all', 'Rhythm awareness pattern', '{"type":"any_elevated","questions":["H1","H8"]}'::jsonb, 'Possible considerations include: caffeine load, stress physiology, electrolyte patterns; thyroid overlap is common', 'these findings may warrant medical evaluation if new, frequent, or paired with breathlessness or chest pressure (check red flags first, always)'),
  ('H-2', 16, 'heart', 'all', 'Workload pattern', '{"type":"all_of","conditions":[{"type":"any_elevated","questions":["H2","H3"]},{"type":"any_elevated","questions":["H4"]}]}'::jsonb, 'This combination may overlap with patterns sometimes seen in cardiovascular strain; deconditioning can present similarly', 'these findings may warrant medical evaluation if persistent or worsening; activity history questioning'),
  ('H-3', 17, 'heart', 'all', 'Circulation pattern', '{"type":"all_elevated","questions":["H5","H9"]}'::jsonb, 'Possible considerations include: circulation patterns; low thyroid patterns present similarly, so read with the Thyroid section', 'further questioning on when and where it appears'),
  ('I-1', 18, 'immune', 'all', 'Resilience cluster', '{"type":"cluster","questions":["I1","I2","I3"],"min":2}'::jsonb, 'This pattern can be associated with immune resilience load, nutrient status patterns, sleep debt, and sustained stress; read with the Adrenals section', 'sleep and stress load first; nutrition quality questioning'),
  ('I-2', 19, 'immune', 'all', 'Reactive cluster', '{"type":"cluster","questions":["I6","I7","I9"],"min":2}'::jsonb, 'This combination may overlap with patterns sometimes seen in allergy-type or histamine-related responses', 'trigger timeline questioning; consider discussing with an appropriate healthcare professional if reactions are strong'),
  ('I-3', 20, 'immune', 'all', 'Persistent activation pattern', '{"type":"any_elevated","questions":["I4","I8"]}'::jsonb, 'These findings may warrant medical evaluation if persistent', 'duration questioning, then referral conversation if ongoing'),
  ('K-1', 21, 'kidney', 'all', 'Frequency pattern (cross-section)', '{"type":"all_elevated","questions":["K1","K2"]}'::jsonb, 'This combination may overlap with patterns sometimes seen in blood sugar dysregulation; on Branch B, prostate-related patterns are also a consideration', 'these findings may warrant medical evaluation if persistent'),
  ('K-2', 22, 'kidney', 'all', 'Irritation pattern', '{"type":"any_elevated","questions":["K4"]}'::jsonb, 'This pattern can be associated with infection-type irritation', 'if burning is current, treat this as a medical follow-up conversation now, not a coaching target'),
  ('K-3', 23, 'kidney', 'all', 'Fluid retention pattern (cross-section)', '{"type":"cluster","questions":["K6","K7","H4"],"min":2}'::jsonb, 'Possible considerations include: fluid handling patterns with kidney, cardiovascular, and hormonal overlaps', 'these findings may warrant medical evaluation if swelling is new or one-sided; sodium and hydration questioning'),
  ('M-1', 24, 'muscles', 'all', 'Inflammatory joint pattern', '{"type":"cluster","questions":["M1","M2","M8"],"min":2}'::jsonb, 'This combination may overlap with patterns sometimes seen in inflammatory joint conditions, especially if morning stiffness lasts beyond 30 minutes', 'stiffness duration questioning; these findings may warrant medical evaluation'),
  ('M-2', 25, 'muscles', 'all', 'Cramp and mineral pattern', '{"type":"any_elevated","questions":["M4"]}'::jsonb, 'Possible considerations include: magnesium and electrolyte patterns, hydration, training load', 'hydration and mineral intake questioning'),
  ('M-3', 26, 'muscles', 'all', 'Widespread soreness pattern (cross-section)', '{"type":"all_of","conditions":[{"type":"any_elevated","questions":["M3"]},{"type":"any_elevated","questions":["N3","A1"]}]}'::jsonb, 'This combination may overlap with patterns sometimes seen in fibromyalgia-type presentations, low thyroid function, or vitamin D status', 'these findings may warrant further questioning and medical evaluation if persistent'),
  ('N-1', 27, 'brain', 'all', 'Cognitive load cluster', '{"type":"cluster","questions":["N1","N2","N3"],"min":2}'::jsonb, 'Possible considerations include: sleep debt, blood sugar swings, low thyroid patterns, iron and B12 patterns, sustained stress load; read with Blood Sugar, Thyroid, and Adrenals', 'coach the foundations first; medical evaluation if it is progressing'),
  ('N-2', 28, 'brain', 'all', 'Activation cluster (cross-section)', '{"type":"all_elevated","questions":["N5","A8"]}'::jsonb, 'This pattern can be associated with a stress physiology running high; breathing mechanics are directly coachable here', 'breathing assessment and downregulation work; consider discussing with an appropriate healthcare professional if it interferes with daily life'),
  ('N-3', 29, 'brain', 'all', 'Nerve signal pattern', '{"type":"any_elevated","questions":["N9"]}'::jsonb, 'Possible considerations include: B12 patterns, circulation, nerve compression from posture or repetitive positions', 'where and when questioning (pairs with your corrective work); these findings may warrant medical evaluation if constant or spreading'),
  ('N-4', 30, 'brain', 'all', 'Low mood pattern', '{"type":"any_elevated","questions":["N6"]}'::jsonb, 'Handle with care in session; this is support territory, not a coaching fix', 'consider discussing with an appropriate healthcare professional if clinically appropriate; keep the door open in your own conversation'),
  ('HA-1', 31, 'hormonal', 'a', 'Transition pattern', '{"type":"cluster","questions":["HA1","HA3","HA4","HA7"],"min":2}'::jsonb, 'This combination may overlap with patterns sometimes seen in perimenopausal transition; thyroid patterns can look similar, so read both sections', 'consider discussing this pattern with an appropriate healthcare professional if clinically appropriate; sleep support is directly coachable now'),
  ('HA-2', 32, 'hormonal', 'a', 'Heavy cycle pattern (cross-section)', '{"type":"all_of","conditions":[{"type":"any_elevated","questions":["HA2"]},{"type":"any_elevated","questions":["A1","N3"]}]}'::jsonb, 'This combination may overlap with patterns sometimes seen in low iron status', 'these findings may warrant medical evaluation, including iron testing'),
  ('HA-3', 33, 'hormonal', 'a', 'Rhythm pattern', '{"type":"cluster","questions":["HA5","HA8","HA10"],"min":2}'::jsonb, 'Possible considerations include: hormone rhythm patterns amplified by blood sugar swings and stress load', 'coach blood sugar steadiness and recovery first, then reassess'),
  ('HB-1', 34, 'hormonal', 'b', 'Androgen pattern', '{"type":"min_elevated","questions":["HB1","HB2","HB3","HB4","HB6"],"min":3}'::jsonb, 'This combination may overlap with patterns sometimes seen with declining androgen levels; sleep debt, stress, and blood sugar patterns present similarly and are coachable first', 'these findings may warrant medical evaluation, including hormone testing, if persistent after foundations improve'),
  ('HB-2', 35, 'hormonal', 'b', 'Night sweat pattern', '{"type":"all_elevated","questions":["HB8","HB7"]}'::jsonb, 'Possible considerations include: overnight blood sugar dips, alcohol timing, stress load, room temperature', 'evening routine questioning; medical follow-up if sweats are drenching or paired with weight loss (check red flags)'),
  ('X-1', 36, null, 'all', 'Systemic load', '{"type":"sections_count_at_band","band":"speaking_loudly","min":3}'::jsonb, 'Possible considerations include: whole-system load rather than one broken part; chasing any single system first is usually the wrong move', 'coach the foundations in order (sleep, blood sugar steadiness, stress and recovery); consider whether a broader medical workup is appropriate'),
  ('X-2', 37, null, 'all', 'Energy triad', '{"type":"sections_at_band","sections":["adrenals","blood_sugar","brain"],"band":"showing_up"}'::jsonb, 'This pattern can be associated with the fuel-stress-focus loop feeding itself', 'blood sugar steadiness is usually the first domino here'),
  ('X-3', 38, null, 'all', 'Gut-immune-skin axis', '{"type":"all_of","conditions":[{"type":"sections_at_band","sections":["digestion","immune"],"band":"showing_up"},{"type":"any_elevated","questions":["L4","L5"]}]}'::jsonb, 'This combination may overlap with patterns sometimes seen in gut-driven immune and skin responses', 'digestion work first, skin as the progress marker')
on conflict (entry_code) do nothing;
