-- Driver Question Bank — expands driver_probe_questions (migration 106)
-- from 7 rows to 87, covering the 33 drivers in MEF-driver-library-v1.md
-- that get daily questions (MEC-2/MEC-3 are camera-assessment-only, per
-- that doc, and correctly get none). Content drafted in
-- docs/driver-question-bank-draft-v1.md, corrected there by the site
-- owner before this migration was written — every prompt/option label
-- below is taken verbatim from that file.
--
-- 1. Adds `screen` ('morning' | 'evening') to driver_probe_questions —
--    which of the two existing check-in surfaces (Morning Readiness,
--    Evening Reflection) a question belongs on. This was previously an
--    unwritten convention (each screen's React component hard-coded which
--    exact question_keys it recognized); making it a real column is what
--    lets a future question be routed to the right screen with a plain
--    update, no deploy — the same "no deploy" property this table
--    already had for a question's existence, now extended to its
--    placement too.
-- 2. Backfills `screen` for the 7 existing rows to match their CURRENT,
--    already-shipped behavior exactly (see app/checkin/CheckinForm.tsx
--    and app/checkin/evening/EveningReflectionForm.tsx as they stood
--    before this migration) — nothing about where an existing question
--    appears changes.
-- 3. Wires morning_soreness (an existing daily_checkins column, asked
--    unconditionally on Morning Readiness since migration 63, never
--    previously linked to a driver) to MOV-5 — pure backend evidence
--    wiring for the driver-state engine, zero UI change, since that
--    field's own rendering was never gated by driver_probe_questions
--    membership.
-- 4. Inserts 80 new rows (docs/driver-question-bank-draft-v1.md's items
--    1-46 and 48-81; its item 47 is the morning_soreness wiring above,
--    not a new question). New goal-relevant follow-ups (e.g.
--    "what kept you up", "which meal(s) did you skip") reuse this same
--    table's existing `driver_id: null` local-follow-up convention
--    (established by migration 106's pain_location/pain_aggravating_factor
--    rows) — excluded from the server-side adaptive bank
--    (lib/daily-checkin-adaptive/probeBank.ts already skips any row with
--    a null driver_id), shown instead by client-side evaluation of their
--    own `requires` array against this same day's already-entered
--    answers (see components/checkin/DriverProbeField.tsx and the two
--    check-in forms, changed in the same commit as this migration).
alter table driver_probe_questions
  add column screen text not null default 'morning' check (screen in ('morning', 'evening'));

update driver_probe_questions set screen = 'evening'
where question_key in ('checkin_probe.digestion_rating', 'checkin_probe.movement_today');
-- night_waking_count, night_sweats, bowel_movement_status, pain_location,
-- pain_aggravating_factor keep the 'morning' default — matches their
-- current, unchanged rendering on Morning Readiness.

insert into driver_probe_questions (question_key, driver_id, prompt, response_type, options, storage, daily_checkins_column, wearable_metric_code, requires, excludes, priority, screen) values
  ('checkin_probe.morning_soreness', 'MOV-5', 'How sore does your body feel this morning?', 'scale', '[1,2,3,4,5]'::jsonb, 'daily_checkins_column', 'morning_soreness', null, '[]'::jsonb, '[]'::jsonb, 0, 'morning');

insert into driver_probe_questions (question_key, driver_id, prompt, response_type, options, storage, daily_checkins_column, wearable_metric_code, requires, excludes, priority, screen) values
  ('checkin_probe.sleep_felt_like_enough', 'SLP-1', 'Even given the hours, did last night''s sleep feel like enough?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.woke_and_couldnt_fall_back', 'SLP-2', 'Once you woke up, how did falling back asleep go?', 'single_select', '[{"value":"fell_back_asleep_easily","label":"Fell back asleep easily"},{"value":"took_a_while","label":"Took a while"},{"value":"couldnt_fall_back_asleep","label":"Couldn''t fall back asleep"},{"value":"didnt_wake_up","label":"Didn''t wake up"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.morning_grogginess', 'SLP-2', 'How groggy did you feel when you first woke up?', 'scale', '[1,2,3,4,5]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.bedtime_vs_usual', 'SLP-3', 'Compared to your usual bedtime, last night you went to bed—', 'single_select', '[{"value":"much_earlier","label":"Much earlier"},{"value":"little_earlier","label":"A little earlier"},{"value":"about_the_same","label":"About the same time"},{"value":"little_later","label":"A little later"},{"value":"much_later","label":"Much later"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.weekday_weekend_bedtime_gap', 'SLP-3', 'Is your bedtime usually different on weekends than weekdays?', 'single_select', '[{"value":"about_the_same","label":"About the same"},{"value":"a_little_different","label":"A little different"},{"value":"very_different","label":"Very different"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.trouble_falling_asleep', 'SLP-3', 'Did it take you a while to fall asleep last night?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.bedtime_later_than_wanted', 'SLP-4', 'Did you go to bed later than you wanted to?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.what_kept_you_up', null, 'What kept you up?', 'single_select', '[{"value":"work","label":"Work"},{"value":"screens_or_tv","label":"Screens or TV"},{"value":"socializing","label":"Socializing"},{"value":"couldnt_sleep_wasnt_tired","label":"Couldn''t sleep / wasn''t tired"},{"value":"other","label":"Other"}]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.bedtime_later_than_wanted","op":"eq","value":true}]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.sleep_position', 'SLP-5', 'What position did you mostly sleep in?', 'single_select', '[{"value":"side","label":"Side"},{"value":"back","label":"Back"},{"value":"stomach","label":"Stomach"},{"value":"propped_up","label":"Propped up"},{"value":"varied_didnt_notice","label":"Varied / didn''t notice"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.woke_in_different_position', 'SLP-5', 'Did you wake up in a different position than you fell asleep in?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.sleep_setup_recent_change', 'SLP-5', 'Any recent change to your pillow, mattress, or sleep setup?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.woke_up_hot', 'SLP-6', 'Did you wake up feeling overheated, even without sweating?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.room_temperature_comfort', 'SLP-6', 'Was your room temperature comfortable last night?', 'single_select', '[{"value":"too_hot","label":"Too hot"},{"value":"too_cold","label":"Too cold"},{"value":"just_right","label":"Just right"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'morning'),
  ('checkin_probe.last_meal_timing', 'FUE-1', 'About when did you eat your last meal or snack?', 'single_select', '[{"value":"before_6pm","label":"Before 6pm"},{"value":"6_to_8pm","label":"6–8pm"},{"value":"8_to_9pm","label":"8–9pm"},{"value":"after_9pm","label":"After 9pm"},{"value":"skipped_dinner","label":"Skipped dinner"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.late_eating_reason', null, 'What made it a later meal?', 'single_select', '[{"value":"work_schedule","label":"Work schedule"},{"value":"social","label":"Social"},{"value":"just_hungry","label":"Just hungry"},{"value":"habit","label":"Habit"},{"value":"other","label":"Other"}]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.last_meal_timing","op":"in","value":["8_to_9pm","after_9pm"]}]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.breakfast_timing', 'FUE-1', 'About how soon after waking did you eat?', 'single_select', '[{"value":"within_1h_of_waking","label":"Within an hour of waking"},{"value":"1_to_3h_after_waking","label":"1–3 hours after waking"},{"value":"skipped_breakfast","label":"Skipped breakfast"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.meals_skipped_today', 'FUE-2', 'How many meals did you skip today?', 'count', '[0,1,2,3]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.longest_gap_between_meals', 'FUE-2', 'What was the longest stretch between meals today?', 'single_select', '[{"value":"under_3h","label":"Under 3 hours"},{"value":"3_to_5h","label":"3–5 hours"},{"value":"5_to_7h","label":"5–7 hours"},{"value":"7h_plus","label":"7+ hours"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.skipped_meal_which', null, 'Which meal(s) did you skip?', 'single_select', '[{"value":"breakfast","label":"Breakfast"},{"value":"lunch","label":"Lunch"},{"value":"dinner","label":"Dinner"},{"value":"more_than_one","label":"More than one"}]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.meals_skipped_today","op":"gte","value":1}]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.hydration_felt_adequate', 'FUE-3', 'Did you feel like you drank enough water today?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.energy_crash_today', 'FUE-4', 'Did you hit an energy crash at any point today?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.crash_timing', null, 'About when did it hit?', 'single_select', '[{"value":"mid_morning","label":"Mid-morning"},{"value":"early_afternoon","label":"Early afternoon"},{"value":"late_afternoon","label":"Late afternoon"},{"value":"evening","label":"Evening"},{"value":"more_than_once","label":"More than once"}]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.energy_crash_today","op":"eq","value":true}]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.cravings_today', 'FUE-4', 'Any strong cravings today?', 'single_select', '[{"value":"none","label":"None"},{"value":"sugar_or_carbs","label":"Sugar or carbs"},{"value":"salty","label":"Salty"},{"value":"caffeine","label":"Caffeine"},{"value":"just_hungry_in_general","label":"Just hungry in general"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.caffeine_servings', 'FUE-5', 'How many caffeinated drinks did you have today?', 'count', '[0,1,2,3,4,5]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.last_caffeine_timing', 'FUE-5', 'About when was your last one?', 'single_select', '[{"value":"before_noon","label":"Before noon"},{"value":"noon_to_3pm","label":"Noon–3pm"},{"value":"3_to_6pm","label":"3–6pm"},{"value":"after_6pm","label":"After 6pm"},{"value":"none_today","label":"None today"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.caffeine_on_empty_stomach', 'FUE-5', 'Did you have caffeine before eating anything?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.alcohol_present', 'FUE-6', 'Did you have any alcohol today?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.alcohol_drinks_count', null, 'About how many drinks?', 'count', '[1,2,3,4]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.alcohol_present","op":"eq","value":true}]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.meals_with_protein', 'FUE-7', 'How many of today''s meals had a real protein source?', 'single_select', '[{"value":"all_of_them","label":"All of them"},{"value":"most_of_them","label":"Most of them"},{"value":"about_half","label":"About half"},{"value":"one_or_none","label":"One or none"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.protein_at_breakfast', 'FUE-7', 'Did your first meal today include protein?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.protein_source_today', 'FUE-7', 'What was your main protein source today, if any?', 'single_select', '[{"value":"meat_fish_eggs","label":"Meat, fish, or eggs"},{"value":"dairy","label":"Dairy"},{"value":"plant_based","label":"Plant-based"},{"value":"protein_supplement","label":"Protein supplement/shake"},{"value":"mostly_none","label":"Mostly none"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.bowel_movement_frequency_today', 'DIG-1', 'How many bowel movements today?', 'count', '[0,1,2,3]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.bowel_regularity_this_week', 'DIG-1', 'How regular has this been for you this week overall?', 'single_select', '[{"value":"very_regular","label":"Very regular"},{"value":"somewhat_regular","label":"Somewhat regular"},{"value":"irregular","label":"Irregular"},{"value":"not_sure","label":"Not sure"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.digestive_symptom_type', null, 'What kind of discomfort?', 'single_select', '[{"value":"bloating","label":"Bloating"},{"value":"cramping","label":"Cramping"},{"value":"reflux_or_heartburn","label":"Reflux or heartburn"},{"value":"gas","label":"Gas"},{"value":"nausea","label":"Nausea"},{"value":"more_than_one","label":"More than one"}]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.digestion_rating","op":"lte","value":2}]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.discomfort_timing', 'DIG-2', 'When does it tend to show up?', 'single_select', '[{"value":"after_meals","label":"After meals"},{"value":"most_of_the_day","label":"Most of the day"},{"value":"morning","label":"Morning"},{"value":"evening","label":"Evening"},{"value":"no_clear_pattern","label":"No clear pattern"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.sitting_hours_today', 'MOV-1', 'About how many hours did you spend sitting today?', 'single_select', '[{"value":"under_4h","label":"Under 4 hours"},{"value":"4_to_6h","label":"4–6 hours"},{"value":"6_to_8h","label":"6–8 hours"},{"value":"8_to_10h","label":"8–10 hours"},{"value":"over_10h","label":"Over 10 hours"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.longest_sitting_stretch', 'MOV-1', 'What was the longest stretch you sat without getting up?', 'single_select', '[{"value":"under_1h","label":"Under 1 hour"},{"value":"1_to_2h","label":"1–2 hours"},{"value":"2_to_3h","label":"2–3 hours"},{"value":"over_3h","label":"Over 3 hours"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.got_up_from_sitting', 'MOV-1', 'About how often did you get up from sitting today?', 'single_select', '[{"value":"every_30_60_min","label":"Every 30–60 minutes"},{"value":"every_couple_hours","label":"Every couple hours"},{"value":"rarely_got_up","label":"Rarely got up"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.training_minutes_today', 'MOV-2', 'About how long was today''s session, if you had one?', 'single_select', '[{"value":"none","label":"None"},{"value":"under_20min","label":"Under 20 min"},{"value":"20_to_40min","label":"20–40 min"},{"value":"40_to_60min","label":"40–60 min"},{"value":"over_60min","label":"Over 60 min"}]'::jsonb, 'probe_answer', null, 'exercise_sessions_count', '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.session_intensity', 'MOV-2', 'How intense did today''s session feel, if you had one?', 'single_select', '[{"value":"easy","label":"Easy"},{"value":"moderate","label":"Moderate"},{"value":"hard","label":"Hard"},{"value":"very_hard","label":"Very hard"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.days_since_last_real_workout', 'MOV-3', 'How long has it been since your last real workout?', 'single_select', '[{"value":"today_or_yesterday","label":"Today or yesterday"},{"value":"2_to_3_days","label":"2–3 days"},{"value":"4_to_7_days","label":"4–7 days"},{"value":"over_a_week","label":"Over a week"},{"value":"cant_remember","label":"Can''t remember"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.longest_break_this_month', 'MOV-3', 'Have you had a longer break from training this month?', 'single_select', '[{"value":"none","label":"None"},{"value":"a_few_days","label":"A few days"},{"value":"about_a_week","label":"About a week"},{"value":"more_than_a_week","label":"More than a week"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.motivation_to_train', 'MOV-3', 'How''s your motivation to train feeling lately?', 'single_select', '[{"value":"eager","label":"Eager"},{"value":"neutral","label":"Neutral"},{"value":"dreading_it","label":"Dreading it"},{"value":"didnt_think_about_it","label":"Didn''t think about it"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.movement_type_today', 'MOV-4', 'Was today''s movement the same pattern you usually do, or something different?', 'single_select', '[{"value":"same_as_usual","label":"Same as usual"},{"value":"something_different","label":"Something different"},{"value":"mix_of_both","label":"A mix of both"},{"value":"no_movement_today","label":"No movement today"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.variety_this_week', 'MOV-4', 'How varied has your movement been this week?', 'single_select', '[{"value":"mostly_one_activity","label":"Mostly one activity"},{"value":"two_or_three_activities","label":"Two or three activities"},{"value":"lots_of_variety","label":"Lots of variety"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.same_muscle_groups_repeatedly', 'MOV-4', 'Have you been hitting the same muscle groups or movement pattern repeatedly lately?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.took_a_rest_day', 'MOV-5', 'Was today a planned rest day?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.feel_recovered', 'MOV-5', 'How recovered do you feel from your last hard session?', 'single_select', '[{"value":"fully_recovered","label":"Fully recovered"},{"value":"mostly_recovered","label":"Mostly recovered"},{"value":"still_a_bit_tired","label":"Still a bit tired"},{"value":"still_pretty_sore_or_tired","label":"Still pretty sore or tired"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.activity_level_today', 'MOV-6', 'How active would you say you were today overall, movement-wise?', 'single_select', '[{"value":"mostly_sedentary","label":"Mostly sedentary"},{"value":"some_walking","label":"Some walking"},{"value":"fairly_active","label":"Fairly active"},{"value":"very_active","label":"Very active"}]'::jsonb, 'probe_answer', null, 'steps', '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.steps_felt_like', 'MOV-6', 'Compared to your usual, did today feel like more or less walking than normal?', 'single_select', '[{"value":"a_lot_less_than_usual","label":"A lot less than usual"},{"value":"about_usual","label":"About usual"},{"value":"more_than_usual","label":"More than usual"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.desk_hours_today', 'MEC-1', 'About how many hours were you at a desk or workstation today?', 'single_select', '[{"value":"none","label":"None"},{"value":"under_2h","label":"Under 2 hours"},{"value":"2_to_4h","label":"2–4 hours"},{"value":"4_to_6h","label":"4–6 hours"},{"value":"over_6h","label":"Over 6 hours"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.screen_height_comfort', 'MEC-1', 'Was your screen at a comfortable height, or did you find yourself hunching toward it?', 'single_select', '[{"value":"comfortable","label":"Comfortable"},{"value":"a_little_off","label":"A little off"},{"value":"uncomfortable_had_to_hunch","label":"Uncomfortable — had to hunch"},{"value":"not_sure","label":"Not sure"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.got_up_hourly', null, 'Did you get up and move at least once an hour?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.desk_hours_today","op":"in","value":["4_to_6h","over_6h"]}]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.footwear_today', 'MEC-4', 'What were you mostly in, shoe-wise, today?', 'single_select', '[{"value":"supportive_sneakers","label":"Supportive sneakers"},{"value":"dress_or_work_shoes","label":"Dress or work shoes"},{"value":"heels","label":"Heels"},{"value":"flats_or_sandals","label":"Flats or sandals"},{"value":"barefoot_or_socks_mostly","label":"Barefoot or socks, mostly"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.barefoot_time_today', 'MEC-4', 'How much time did you spend barefoot today?', 'single_select', '[{"value":"none","label":"None"},{"value":"a_little","label":"A little"},{"value":"a_good_amount","label":"A good amount"},{"value":"most_of_the_day","label":"Most of the day"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.footwear_support_level', 'MEC-4', 'How much support would you say today''s footwear gave you?', 'single_select', '[{"value":"good_support","label":"Good support"},{"value":"minimal_support","label":"Minimal support"},{"value":"no_support","label":"No support"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.bag_or_carry_side', 'MEC-5', 'If you carried a bag today, which side — or did you switch?', 'single_select', '[{"value":"always_same_side","label":"Always the same side"},{"value":"switch_sides","label":"I switch sides"},{"value":"backpack_or_even_load","label":"Backpack / evenly loaded"},{"value":"didnt_carry_anything","label":"Didn''t carry anything"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.dominant_side_overuse', 'MEC-5', 'Did you notice yourself favoring one side of your body today?', 'single_select', '[{"value":"yes_noticeably","label":"Yes, noticeably"},{"value":"a_little","label":"A little"},{"value":"not_that_i_noticed","label":"Not that I noticed"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.one_sided_activity_today', 'MEC-5', 'Did anything today load one side more than the other — a sport, carrying something, your desk setup?', 'single_select', '[{"value":"golf_or_racquet_sport","label":"Golf or a racquet sport"},{"value":"carrying_child_or_heavy_bag","label":"Carrying a child or heavy bag"},{"value":"desk_with_mouse_or_phone_favoring_one_side","label":"Desk/mouse/phone favoring one side"},{"value":"none_that_i_noticed","label":"None that I noticed"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.stress_source_today', 'STR-1', 'What''s most of today''s stress coming from, if anything?', 'single_select', '[{"value":"work","label":"Work"},{"value":"relationships_or_family","label":"Relationships or family"},{"value":"health","label":"Health"},{"value":"money","label":"Money"},{"value":"time_pressure","label":"Time pressure"},{"value":"no_clear_source","label":"No clear source"},{"value":"other","label":"Other"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.breath_holding_or_shallow', 'STR-2', 'How would you describe your breathing today — relaxed, or shallow/held at times?', 'single_select', '[{"value":"normal_relaxed","label":"Normal and relaxed"},{"value":"shallow_at_times","label":"Shallow at times"},{"value":"caught_myself_holding_breath","label":"Caught myself holding my breath"},{"value":"not_sure","label":"Not sure"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.chest_vs_belly_breathing', 'STR-2', 'When you notice your breath, does it feel like it''s coming more from your chest or your belly?', 'single_select', '[{"value":"mostly_belly","label":"Mostly belly"},{"value":"mostly_chest","label":"Mostly chest"},{"value":"a_mix","label":"A mix"},{"value":"not_sure","label":"Not sure"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.sighing_or_yawning_a_lot', 'STR-2', 'Did you catch yourself sighing or yawning a lot today?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.screens_before_bed', 'STR-3', 'About how much screen time did you have in the hour before bed?', 'single_select', '[{"value":"none","label":"None"},{"value":"under_30min","label":"Under 30 min"},{"value":"30_to_60min","label":"30–60 min"},{"value":"over_60min","label":"Over 60 min"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.had_a_windown_routine', 'STR-3', 'Did you have any kind of wind-down routine before bed last night?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.work_right_up_to_bed', 'STR-3', 'Were you working, emailing, or on your phone for work right up until bed?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.emotional_load_today', 'STR-4', 'How emotionally heavy did today feel?', 'single_select', '[{"value":"light","label":"Light"},{"value":"some","label":"Some"},{"value":"heavy","label":"Heavy"},{"value":"very_heavy","label":"Very heavy"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.emotional_load_source', null, 'What was most of that weight about, if you''re comfortable sharing?', 'single_select', '[{"value":"work","label":"Work"},{"value":"relationship_or_family","label":"Relationship or family"},{"value":"health","label":"Health"},{"value":"grief_or_loss","label":"Grief or loss"},{"value":"caregiving","label":"Caregiving"},{"value":"money","label":"Money"},{"value":"other","label":"Other"}]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.emotional_load_today","op":"in","value":["heavy","very_heavy"]}]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.had_unstructured_time', 'STR-5', 'Did you have any real downtime today — time with nothing scheduled or expected of you?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.downtime_amount', 'STR-5', 'About how much unstructured time did you get?', 'single_select', '[{"value":"none","label":"None"},{"value":"a_few_minutes","label":"A few minutes"},{"value":"15_to_30_minutes","label":"15–30 minutes"},{"value":"more_than_30_minutes","label":"More than 30 minutes"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.felt_rushed_all_day', 'STR-5', 'Did today feel rushed from start to finish?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.cycle_phase', 'CTX-1', 'Where are you in your cycle, if applicable?', 'single_select', '[{"value":"menstrual","label":"Menstrual"},{"value":"follicular","label":"Follicular"},{"value":"ovulation","label":"Ovulation"},{"value":"luteal","label":"Luteal"},{"value":"not_applicable","label":"Not applicable"},{"value":"prefer_not_to_say","label":"Prefer not to say"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.morning_light_today', 'CTX-2', 'Did you get outside in daylight within an hour or two of waking?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.time_outdoors_today', 'CTX-2', 'About how much time did you spend outdoors today?', 'single_select', '[{"value":"none","label":"None"},{"value":"under_15min","label":"Under 15 min"},{"value":"15_to_60min","label":"15–60 min"},{"value":"over_1h","label":"Over 1 hour"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.mostly_indoors_today', 'CTX-2', 'Were you mostly indoors today?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.schedule_today_vs_usual', 'CTX-3', 'Was today''s schedule your normal routine, or was it thrown off — travel, a shift change, something like that?', 'single_select', '[{"value":"normal_routine","label":"Normal routine"},{"value":"slightly_different","label":"Slightly different"},{"value":"very_different_travel_or_shift","label":"Very different — travel or shift change"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.days_of_irregular_schedule_this_week', 'CTX-3', 'How many days this week have been off your usual schedule?', 'single_select', '[{"value":"none","label":"None"},{"value":"one_or_two","label":"One or two"},{"value":"most_of_the_week","label":"Most of the week"}]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.upcoming_travel_or_shift_change', 'CTX-3', 'Any travel or schedule change coming up in the next few days?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.medication_or_supplement_change', 'CTX-4', 'Any change to medications or supplements recently — starting, stopping, or a dose change?', 'boolean', '[]'::jsonb, 'probe_answer', null, null, '[]'::jsonb, '[]'::jsonb, 0, 'evening'),
  ('checkin_probe.what_changed', null, 'What changed?', 'single_select', '[{"value":"started_something_new","label":"Started something new"},{"value":"stopped_something","label":"Stopped something"},{"value":"changed_a_dose","label":"Changed a dose"},{"value":"prefer_not_to_say","label":"Prefer not to say"}]'::jsonb, 'probe_answer', null, null, '[{"question_key":"checkin_probe.medication_or_supplement_change","op":"eq","value":true}]'::jsonb, '[]'::jsonb, 0, 'evening');
