-- WBSA content — 16 body-system sections, original MEF-authored questions.
-- Generated from a structured content model (see the WBSA build task); not
-- hand-typed row by row, to guarantee every requires/excludes/validation
-- JSON blob is well-formed. Original wording throughout, not derived from
-- HAQ, Short HAQ, or any third-party instrument.

with def as (
  insert into unified_assessment_definitions (
    key, catalog_definition_id, title, description, assessment_type,
    estimated_completion_time_minutes, adaptive_enabled, reassessment_enabled,
    safety_enabled, version, active
  ) values (
    'wbsa', 'bfb52589-7566-4347-95aa-03d696a1041e',
    'Whole-Body Systems Assessment',
    'A whole-body check-in across 16 connected functional systems, built to help surface patterns worth a closer look. This is wellness education, not a medical diagnosis.',
    'intake_questionnaire', 20, true, true, true, 1, true
  )
  returning id
),
sections as (
  insert into unified_assessment_sections (assessment_definition_id, title, subtitle, display_order, optional, required)
  select def.id, v.title, v.subtitle, v.display_order, false, true
  from def, (values
    ('Upper Digestive Function', 'How food sits with you after eating', 1),
    ('Lower Digestive & Elimination Function', 'Regularity, comfort, and change over time', 2),
    ('Blood Sugar & Energy Regulation', 'How steady your energy feels between meals', 3),
    ('Liver & Detoxification Support', 'How your body handles rich food and alcohol', 4),
    ('Immune & Inflammatory Patterns', 'How often your body is fighting something off', 5),
    ('Respiratory & Oxygenation Patterns', 'How easily you breathe during daily life', 6),
    ('Circulation & Cardiovascular-Related Observations', 'Blood flow, warmth, and steadiness on standing', 7),
    ('Kidney, Bladder & Fluid-Balance Patterns', 'How your body manages fluid and waste', 8),
    ('Thyroid & Metabolic-Related Observations', 'Temperature, weight, and energy rhythm', 9),
    ('Adrenal & Stress-Response Patterns', 'How your body handles daily demands', 10),
    ('Reproductive & Hormonal Patterns', 'Cycle, libido, and hormonal rhythm', 11),
    ('Neurological & Cognitive Patterns', 'Focus, memory, and nervous system signals', 12),
    ('Musculoskeletal & Connective-Tissue Patterns', 'Stiffness, joints, and how you move', 13),
    ('Skin, Hair & Nail Observations', 'Outward signals of what is going on inside', 14),
    ('Nutrient Insufficiency Patterns', 'What your everyday eating pattern suggests', 15),
    ('Recovery & Resilience Patterns', 'How well your body and mind bounce back', 16)
  ) as v(title, subtitle, display_order)
  returning id, title
)
insert into unified_assessment_questions (
  assessment_definition_id, section_id, question_key, display_order, prompt,
  answer_type, answer_options, validation, body_system, concern_category,
  severity_tags, allows_prefer_not_to_answer, requires
)
select def.id, sections.id, q.question_key, q.display_order, q.prompt,
  q.answer_type, q.answer_options, q.validation, q.body_system, q.concern_category,
  q.severity_tags, q.allows_prefer_not_to_answer, q.requires
from def, sections,
(values
  ('Upper Digestive Function', 'wbsa_updig_fullness', 1, 'After a normal-sized meal, how often do you feel uncomfortably full or bloated?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'upper_digestive', 'digestive', array['mild']::text[], false, null),
  ('Upper Digestive Function', 'wbsa_updig_burning', 2, 'How often do you notice a burning or acidic sensation in your chest or throat after eating?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'upper_digestive', 'digestive', array['moderate']::text[], false, null),
  ('Upper Digestive Function', 'wbsa_updig_timing', 3, 'When does that fullness or bloating usually show up?', 'single_select', '[{"value":"within_30_min","label":"Within 30 minutes of eating"},{"value":"one_two_hours","label":"1 to 2 hours after eating"},{"value":"most_of_day","label":"It lingers for most of the day"},{"value":"varies","label":"It varies a lot"}]'::jsonb, null, 'upper_digestive', null, null, false, '{"type":"or","conditions":[{"type":"leaf","questionKey":"wbsa_updig_fullness","op":"equals","value":"often"},{"type":"leaf","questionKey":"wbsa_updig_fullness","op":"equals","value":"frequently"}]}'::jsonb),
  ('Upper Digestive Function', 'wbsa_updig_trigger_foods', 4, 'Do certain foods, like dairy, gluten, or fried food, seem to trigger these feelings more than others?', 'boolean', null, null, 'upper_digestive', null, null, false, null),
  ('Lower Digestive & Elimination Function', 'wbsa_lowdig_regularity', 1, 'How would you describe your bowel regularity most weeks?', 'single_select', '[{"value":"very_regular","label":"Very regular, close to daily"},{"value":"somewhat_irregular","label":"Somewhat irregular"},{"value":"unpredictable","label":"Unpredictable, hard to plan around"},{"value":"infrequent","label":"Infrequent, fewer than three times a week"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["unpredictable","infrequent"]}}'::jsonb, 'lower_digestive', 'digestive', array['mild']::text[], false, null),
  ('Lower Digestive & Elimination Function', 'wbsa_lowdig_discomfort', 2, 'How often do you experience cramping, urgency, or discomfort around bowel movements?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'lower_digestive', 'digestive', array['moderate']::text[], false, null),
  ('Lower Digestive & Elimination Function', 'wbsa_lowdig_redflag_bleeding', 3, 'Have you noticed blood in your stool or unexplained rectal bleeding?', 'boolean', null, '{"findingRule":{"type":"boolean_true"}}'::jsonb, 'lower_digestive', 'digestive', array['significant']::text[], false, '{"type":"or","conditions":[{"type":"leaf","questionKey":"wbsa_lowdig_discomfort","op":"equals","value":"often"},{"type":"leaf","questionKey":"wbsa_lowdig_discomfort","op":"equals","value":"frequently"}]}'::jsonb),
  ('Lower Digestive & Elimination Function', 'wbsa_lowdig_change', 4, 'Has your normal pattern changed noticeably in the last few months?', 'boolean', null, null, 'lower_digestive', null, null, false, null),
  ('Blood Sugar & Energy Regulation', 'wbsa_glucose_crash', 1, 'How often do you feel shaky, irritable, or foggy if a meal is delayed or skipped?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'blood_sugar_energy', 'metabolic', array['moderate']::text[], false, null),
  ('Blood Sugar & Energy Regulation', 'wbsa_glucose_afternoon', 2, 'How often do you hit a noticeable energy crash in the early-to-mid afternoon?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'blood_sugar_energy', 'metabolic', array['mild']::text[], false, null),
  ('Blood Sugar & Energy Regulation', 'wbsa_glucose_cravings', 3, 'When energy dips, what do you crave most?', 'single_select', '[{"value":"sugar_sweets","label":"Sugar or sweets"},{"value":"caffeine","label":"Caffeine"},{"value":"salty_starchy","label":"Salty or starchy food"},{"value":"nothing_particular","label":"Nothing in particular"}]'::jsonb, null, 'blood_sugar_energy', null, null, false, '{"type":"or","conditions":[{"type":"leaf","questionKey":"wbsa_glucose_crash","op":"equals","value":"often"},{"type":"leaf","questionKey":"wbsa_glucose_crash","op":"equals","value":"frequently"}]}'::jsonb),
  ('Blood Sugar & Energy Regulation', 'wbsa_glucose_thirst', 4, 'Have you noticed unusually frequent thirst or urination lately?', 'boolean', null, '{"findingRule":{"type":"boolean_true"}}'::jsonb, 'blood_sugar_energy', 'metabolic', array['moderate']::text[], false, null),
  ('Liver & Detoxification Support', 'wbsa_liver_alcohol_sensitivity', 1, 'How does your body seem to handle alcohol or rich, fatty meals?', 'single_select', '[{"value":"handles_fine","label":"Handles it fine"},{"value":"mild_next_day","label":"Mild next-day sluggishness"},{"value":"noticeably_unwell","label":"Noticeably sluggish or unwell"},{"value":"avoid_it","label":"I avoid it because it affects me strongly"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["noticeably_unwell","avoid_it"]}}'::jsonb, 'liver_detox', 'metabolic', array['mild']::text[], false, null),
  ('Liver & Detoxification Support', 'wbsa_liver_skin_tone', 2, 'Have you or others noticed a yellowish tint to your skin or the whites of your eyes?', 'boolean', null, '{"findingRule":{"type":"boolean_true"}}'::jsonb, 'liver_detox', 'metabolic', array['significant']::text[], false, null),
  ('Liver & Detoxification Support', 'wbsa_liver_fatigue_after_eating', 3, 'How often do you feel unusually heavy or fatigued within an hour of eating a rich meal?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, null, 'liver_detox', null, null, false, null),
  ('Liver & Detoxification Support', 'wbsa_liver_body_odor', 4, 'Have you noticed a change in body odor or breath that feels different from before?', 'boolean', null, null, 'liver_detox', null, null, true, null),
  ('Immune & Inflammatory Patterns', 'wbsa_immune_frequency', 1, 'In the past year, how often have you caught colds, infections, or other bugs going around?', 'single_select', '[{"value":"rarely","label":"Rarely, zero to one time"},{"value":"occasionally","label":"Occasionally, two to three times"},{"value":"often","label":"Often, four or more times"},{"value":"almost_constantly","label":"Almost constantly"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","almost_constantly"]}}'::jsonb, 'immune_inflammatory', 'immune', array['moderate']::text[], false, null),
  ('Immune & Inflammatory Patterns', 'wbsa_immune_recovery', 2, 'When you do get sick, how often does it take longer than it used to for you to bounce back?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'immune_inflammatory', 'immune', array['mild']::text[], false, null),
  ('Immune & Inflammatory Patterns', 'wbsa_immune_puffiness', 3, 'How often do you notice puffiness, swelling, or achiness that seems unrelated to activity?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, null, 'immune_inflammatory', null, null, false, null),
  ('Immune & Inflammatory Patterns', 'wbsa_immune_allergic', 4, 'Have you developed any new sensitivities, rashes, or allergic-type reactions in the past year?', 'boolean', null, null, 'immune_inflammatory', null, null, false, null),
  ('Respiratory & Oxygenation Patterns', 'wbsa_resp_breathlessness', 1, 'How often do you feel more out of breath than expected during light activity, like climbing a flight of stairs?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'respiratory_oxygenation', 'breathing', array['moderate']::text[], false, null),
  ('Respiratory & Oxygenation Patterns', 'wbsa_resp_shallow', 2, 'How often do you notice yourself breathing shallowly, especially when focused or stressed?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'respiratory_oxygenation', 'breathing', array['mild']::text[], false, null),
  ('Respiratory & Oxygenation Patterns', 'wbsa_resp_redflag_chest', 3, 'Have you experienced chest pain, tightness, or a sudden inability to catch your breath?', 'boolean', null, '{"findingRule":{"type":"boolean_true"}}'::jsonb, 'respiratory_oxygenation', 'breathing', array['significant']::text[], false, '{"type":"or","conditions":[{"type":"leaf","questionKey":"wbsa_resp_breathlessness","op":"equals","value":"often"},{"type":"leaf","questionKey":"wbsa_resp_breathlessness","op":"equals","value":"frequently"}]}'::jsonb),
  ('Respiratory & Oxygenation Patterns', 'wbsa_resp_congestion', 4, 'How often do you deal with nasal congestion or a sense of restricted airflow?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, null, 'respiratory_oxygenation', null, null, false, null),
  ('Circulation & Cardiovascular-Related Observations', 'wbsa_circ_cold_extremities', 1, 'How often are your hands or feet noticeably cold, even in a warm room?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'circulation_cardiovascular', 'circulatory', array['mild']::text[], false, null),
  ('Circulation & Cardiovascular-Related Observations', 'wbsa_circ_dizziness', 2, 'How often do you feel lightheaded or dizzy when standing up quickly?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'circulation_cardiovascular', 'circulatory', array['moderate']::text[], false, null),
  ('Circulation & Cardiovascular-Related Observations', 'wbsa_circ_swelling', 3, 'Do you notice swelling in your ankles, feet, or legs by the end of the day?', 'boolean', null, null, 'circulation_cardiovascular', null, null, false, null),
  ('Circulation & Cardiovascular-Related Observations', 'wbsa_circ_redflag_palpitations', 4, 'Have you noticed your heart racing, pounding, or skipping beats along with the dizziness?', 'boolean', null, '{"findingRule":{"type":"boolean_true"}}'::jsonb, 'circulation_cardiovascular', 'circulatory', array['significant']::text[], false, '{"type":"or","conditions":[{"type":"leaf","questionKey":"wbsa_circ_dizziness","op":"equals","value":"often"},{"type":"leaf","questionKey":"wbsa_circ_dizziness","op":"equals","value":"frequently"}]}'::jsonb),
  ('Kidney, Bladder & Fluid-Balance Patterns', 'wbsa_renal_urination_frequency', 1, 'How often do you find yourself needing to urinate through the day?', 'single_select', '[{"value":"typical","label":"About typical for me"},{"value":"more_than_usual","label":"More than usual"},{"value":"much_more","label":"Much more than usual"},{"value":"less_than_usual","label":"Less than usual"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["much_more","less_than_usual"]}}'::jsonb, 'kidney_bladder_fluid', 'renal', array['moderate']::text[], false, null),
  ('Kidney, Bladder & Fluid-Balance Patterns', 'wbsa_renal_water_retention', 2, 'How often do you notice puffiness or water retention, especially around your face or hands?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'kidney_bladder_fluid', 'renal', array['mild']::text[], false, null),
  ('Kidney, Bladder & Fluid-Balance Patterns', 'wbsa_renal_thirst_balance', 3, 'Do you often feel like you can''t quite quench your thirst, no matter how much you drink?', 'boolean', null, null, 'kidney_bladder_fluid', null, null, false, null),
  ('Kidney, Bladder & Fluid-Balance Patterns', 'wbsa_renal_urine_color', 4, 'Most days, what best describes the color of your urine?', 'single_select', '[{"value":"pale_yellow","label":"Pale yellow"},{"value":"dark_yellow","label":"Dark yellow"},{"value":"amber_brownish","label":"Amber or brownish"},{"value":"varies","label":"Varies a lot"}]'::jsonb, null, 'kidney_bladder_fluid', null, null, true, null),
  ('Thyroid & Metabolic-Related Observations', 'wbsa_thyroid_temperature', 1, 'How do you typically run temperature-wise compared to those around you?', 'single_select', '[{"value":"about_the_same","label":"About the same as most people"},{"value":"run_cold","label":"I tend to run cold"},{"value":"run_warm","label":"I tend to run warm"},{"value":"varies","label":"It varies unpredictably"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["run_cold"]}}'::jsonb, 'thyroid_metabolic', 'metabolic', array['mild']::text[], false, null),
  ('Thyroid & Metabolic-Related Observations', 'wbsa_thyroid_weight_change', 2, 'Have you noticed an unexplained change in weight in the past several months?', 'single_select', '[{"value":"no_change","label":"No meaningful change"},{"value":"gradual_gain","label":"Gradual gain"},{"value":"gradual_loss","label":"Gradual loss"},{"value":"noticeable_swings","label":"Noticeable swings either way"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["gradual_gain","gradual_loss","noticeable_swings"]}}'::jsonb, 'thyroid_metabolic', 'metabolic', array['moderate']::text[], false, null),
  ('Thyroid & Metabolic-Related Observations', 'wbsa_thyroid_hair_thinning', 3, 'Have you noticed thinning hair, especially at the outer eyebrows or scalp?', 'boolean', null, null, 'thyroid_metabolic', null, null, false, null),
  ('Thyroid & Metabolic-Related Observations', 'wbsa_thyroid_energy_pattern', 4, 'How often do you feel a heavy, sluggish kind of tired that a good night''s sleep doesn''t fix?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, null, 'thyroid_metabolic', null, null, false, null),
  ('Adrenal & Stress-Response Patterns', 'wbsa_adrenal_wired_tired', 1, 'How often do you feel simultaneously wired and exhausted, like you can''t relax but also can''t get going?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'adrenal_stress_response', 'stress', array['moderate']::text[], false, null),
  ('Adrenal & Stress-Response Patterns', 'wbsa_adrenal_morning_energy', 2, 'How does your energy typically feel in the first hour after waking?', 'single_select', '[{"value":"steady_clear","label":"Steady and clear"},{"value":"slow_but_improves","label":"Slow to start but improves"},{"value":"jolt_then_crash","label":"A jolt then a crash"},{"value":"consistently_low","label":"Consistently low"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["jolt_then_crash","consistently_low"]}}'::jsonb, 'adrenal_stress_response', 'stress', array['mild']::text[], false, null),
  ('Adrenal & Stress-Response Patterns', 'wbsa_adrenal_overwhelm', 3, 'How often do ordinary daily demands feel more overwhelming than they used to?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, null, 'adrenal_stress_response', null, null, false, null),
  ('Adrenal & Stress-Response Patterns', 'wbsa_adrenal_coping', 4, 'When stress builds up, what do you find yourself leaning on most?', 'multi_select', '[{"value":"food","label":"Food"},{"value":"caffeine","label":"Caffeine"},{"value":"alcohol","label":"Alcohol"},{"value":"screens","label":"Screens or scrolling"},{"value":"exercise","label":"Exercise"},{"value":"talking_to_someone","label":"Talking to someone"},{"value":"none_help","label":"None of these really help"}]'::jsonb, null, 'adrenal_stress_response', null, null, true, null),
  ('Reproductive & Hormonal Patterns', 'wbsa_repro_cycle_or_libido_change', 1, 'Have you noticed a change in your monthly cycle, libido, or hormonal rhythm over the past several months?', 'single_select', '[{"value":"no_change","label":"No noticeable change"},{"value":"mild_change","label":"A mild change"},{"value":"clear_ongoing_change","label":"A clear and ongoing change"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["clear_ongoing_change"]}}'::jsonb, 'reproductive_hormonal', 'hormone', array['moderate']::text[], true, null),
  ('Reproductive & Hormonal Patterns', 'wbsa_repro_mood_swings', 2, 'How often do you notice mood swings that seem tied to a hormonal pattern, monthly, seasonal, or otherwise?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'reproductive_hormonal', 'hormone', array['mild']::text[], false, null),
  ('Reproductive & Hormonal Patterns', 'wbsa_repro_sleep_disruption', 3, 'Do hot flashes, night sweats, or temperature swings disrupt your sleep?', 'boolean', null, null, 'reproductive_hormonal', null, null, true, null),
  ('Reproductive & Hormonal Patterns', 'wbsa_repro_redflag_pain', 4, 'Have you experienced new or worsening pelvic pain, unusual bleeding, or symptoms that concern you?', 'boolean', null, '{"findingRule":{"type":"boolean_true"}}'::jsonb, 'reproductive_hormonal', 'hormone', array['significant']::text[], true, null),
  ('Neurological & Cognitive Patterns', 'wbsa_neuro_brain_fog', 1, 'How often do you experience brain fog, forgetfulness, or trouble concentrating?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'neurological_cognitive', 'neurological', array['moderate']::text[], false, null),
  ('Neurological & Cognitive Patterns', 'wbsa_neuro_headaches', 2, 'How often do you get headaches?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'neurological_cognitive', 'neurological', array['mild']::text[], false, null),
  ('Neurological & Cognitive Patterns', 'wbsa_neuro_redflag_severity', 3, 'When these headaches happen, how would you describe them?', 'single_select', '[{"value":"mild_manageable","label":"Mild and manageable"},{"value":"noticeable_tolerable","label":"Noticeable but tolerable"},{"value":"severe_disruptive","label":"Severe and disruptive"},{"value":"worst_ever","label":"The worst headache of my life"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["worst_ever"]}}'::jsonb, 'neurological_cognitive', 'neurological', array['significant']::text[], false, '{"type":"or","conditions":[{"type":"leaf","questionKey":"wbsa_neuro_headaches","op":"equals","value":"often"},{"type":"leaf","questionKey":"wbsa_neuro_headaches","op":"equals","value":"frequently"}]}'::jsonb),
  ('Neurological & Cognitive Patterns', 'wbsa_neuro_balance', 4, 'Have you noticed any new numbness, tingling, weakness, or balance problems?', 'boolean', null, '{"findingRule":{"type":"boolean_true"}}'::jsonb, 'neurological_cognitive', 'neurological', array['significant']::text[], false, null),
  ('Musculoskeletal & Connective-Tissue Patterns', 'wbsa_musc_stiffness', 1, 'How often do you wake up with noticeable stiffness that takes a while to work out?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'musculoskeletal_connective', 'movement', array['mild']::text[], false, null),
  ('Musculoskeletal & Connective-Tissue Patterns', 'wbsa_musc_joint_pain', 2, 'Which best describes any joint or muscle discomfort you experience?', 'single_select', '[{"value":"none","label":"None"},{"value":"mild_occasional","label":"Mild and occasional"},{"value":"moderate_regular","label":"Moderate and regular"},{"value":"significant_limiting","label":"Significant and limiting"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["moderate_regular","significant_limiting"]}}'::jsonb, 'musculoskeletal_connective', 'movement', array['moderate']::text[], false, null),
  ('Musculoskeletal & Connective-Tissue Patterns', 'wbsa_musc_injury_recovery', 3, 'Do old injuries or strains seem to take longer to feel better than they used to?', 'boolean', null, null, 'musculoskeletal_connective', null, null, false, null),
  ('Musculoskeletal & Connective-Tissue Patterns', 'wbsa_musc_flexibility', 4, 'How often does tightness or reduced flexibility get in the way of daily movement?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, null, 'musculoskeletal_connective', null, null, false, null),
  ('Skin, Hair & Nail Observations', 'wbsa_skin_dryness', 1, 'How often does your skin feel unusually dry, flaky, or irritated?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'skin_hair_nails', 'dermatological', array['mild']::text[], false, null),
  ('Skin, Hair & Nail Observations', 'wbsa_skin_breakouts', 2, 'How often do you deal with breakouts, rashes, or unexplained skin reactions?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["often","frequently"]}}'::jsonb, 'skin_hair_nails', 'dermatological', array['moderate']::text[], false, null),
  ('Skin, Hair & Nail Observations', 'wbsa_skin_nail_texture', 3, 'Have you noticed your nails becoming more brittle, ridged, or slow-growing?', 'boolean', null, null, 'skin_hair_nails', null, null, false, null),
  ('Skin, Hair & Nail Observations', 'wbsa_skin_hair_texture', 4, 'Has your hair''s texture, shine, or shedding pattern changed noticeably?', 'boolean', null, null, 'skin_hair_nails', null, null, false, null),
  ('Nutrient Insufficiency Patterns', 'wbsa_nutrient_variety', 1, 'How would you describe the variety of whole foods in your typical week?', 'single_select', '[{"value":"wide_variety","label":"Wide variety"},{"value":"moderate_variety","label":"Moderate variety"},{"value":"fairly_repetitive","label":"Fairly repetitive"},{"value":"very_limited","label":"Very limited"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["fairly_repetitive","very_limited"]}}'::jsonb, 'nutrient_insufficiency', 'nutrition', array['mild']::text[], false, null),
  ('Nutrient Insufficiency Patterns', 'wbsa_nutrient_cravings', 2, 'Do you regularly crave any of the following?', 'multi_select', '[{"value":"red_meat_iron","label":"Red meat or iron-rich food"},{"value":"salty_food","label":"Salty food"},{"value":"sweets_sugar","label":"Sweets or sugar"},{"value":"ice_cold_drinks","label":"Ice or very cold drinks"},{"value":"none","label":"None of these"}]'::jsonb, null, 'nutrient_insufficiency', null, null, false, null),
  ('Nutrient Insufficiency Patterns', 'wbsa_nutrient_appetite', 3, 'How has your appetite felt lately?', 'single_select', '[{"value":"steady_normal","label":"Steady and normal"},{"value":"lower_than_usual","label":"Lower than usual"},{"value":"higher_than_usual","label":"Higher than usual"},{"value":"unpredictable","label":"Unpredictable"}]'::jsonb, null, 'nutrient_insufficiency', null, null, true, null),
  ('Nutrient Insufficiency Patterns', 'wbsa_nutrient_supplement_use', 4, 'Are you currently taking any vitamins, minerals, or supplements regularly?', 'boolean', null, null, 'nutrient_insufficiency', null, null, false, null),
  ('Recovery & Resilience Patterns', 'wbsa_recovery_sleep_restorative', 1, 'How often do you wake up feeling genuinely rested, even after a full night''s sleep?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["never_rarely","occasionally"]}}'::jsonb, 'recovery_resilience', 'sleep', array['moderate']::text[], false, null),
  ('Recovery & Resilience Patterns', 'wbsa_recovery_bounce_back', 2, 'After a physically or mentally demanding day, how long does it typically take you to feel back to normal?', 'single_select', '[{"value":"same_day","label":"The same day"},{"value":"a_day_or_two","label":"A day or two"},{"value":"several_days","label":"Several days"},{"value":"never_fully_catch_up","label":"It feels like I never fully catch up"}]'::jsonb, '{"findingRule":{"type":"value_in","concerningValues":["several_days","never_fully_catch_up"]}}'::jsonb, 'recovery_resilience', 'sleep', array['mild']::text[], false, null),
  ('Recovery & Resilience Patterns', 'wbsa_recovery_illness_recovery', 3, 'Do you generally feel like your body recovers from minor illness or exertion at the pace you would expect?', 'boolean', null, null, 'recovery_resilience', null, null, false, null),
  ('Recovery & Resilience Patterns', 'wbsa_recovery_resilience_mood', 4, 'How often do minor setbacks feel harder to bounce back from emotionally than they used to?', 'frequency', '[{"value":"never_rarely","label":"Never or rarely"},{"value":"occasionally","label":"Occasionally (a few times a month)"},{"value":"often","label":"Often (a few times a week)"},{"value":"frequently","label":"Frequently (daily or almost daily)"}]'::jsonb, null, 'recovery_resilience', null, null, false, null)
) as q(section_title, question_key, display_order, prompt, answer_type, answer_options, validation, body_system, concern_category, severity_tags, allows_prefer_not_to_answer, requires)
where sections.title = q.section_title;

