-- Movement Intelligence — The Rooted Reset.
--
-- IMPORTANT: this migration does NOT add a workout library or any real
-- exercise content. It adds the data architecture a daily, intelligently
-- composed movement session needs so that any exercise source (an
-- internal placeholder catalog today; Exercise.com, Physitrack, custom
-- video, or a future proprietary API tomorrow) can plug in later with zero
-- schema change — see apps/consumer-web-app/lib/movement/providers/ for
-- the provider abstraction this schema backs, mirroring exactly how
-- migration 37 (body_assessments) backs lib/body-assessment/providers/.
--
--   movement_sessions           one row per day a member is offered a
--                                movement session. Generated by the
--                                deterministic decision engine
--                                (lib/movement/rules/) from real check-in,
--                                assessment, registry, and session-history
--                                facts — never fabricated. Never versioned
--                                in place; a regenerated session for the
--                                same day is simply a new row, same
--                                "append-only history" posture as
--                                daily_checkins and body_assessments.
--
--   movement_session_exercises  one row per exercise slot placed into a
--                                session by the decision engine, tagged
--                                with the section it belongs to
--                                (preparation/breathing/mobility/
--                                activation/strength/conditioning/
--                                recovery). `exercise_id` is a plain text
--                                key into whichever provider generated the
--                                session (lib/movement/exercises/catalog.ts
--                                today) — intentionally NOT a foreign key,
--                                since a future external provider's
--                                exercise ids don't live in this database
--                                at all.
--
-- Nothing in this migration computes a "real" Movement Score beyond a
-- simple, honest adherence calculation over completed sessions — see
-- lib/movement/score.ts. It is explicitly labeled a placeholder in the UI
-- pending richer signals (wearable recovery, range-of-motion tracking).
--
-- RLS follows the exact established pattern (migration 15 helpers,
-- migrations 27-37 precedent): member_read_own / member_insert_own /
-- member_update_own, coach_read_assigned / coach_update_assigned via
-- is_active_coach_for, platform_admin_all.

-- ============================================================
-- Extend ai_events.event_type additively — same convention migrations 37,
-- 39, and 47 already used for this exact table.
-- ============================================================
alter table ai_events drop constraint ai_events_event_type_check;
alter table ai_events add constraint ai_events_event_type_check
  check (event_type in (
    'member_completed_onboarding',
    'member_completed_checkin',
    'member_missed_checkin',
    'reassessment_completed',
    'pain_increased',
    'pain_decreased',
    'stress_increased',
    'stress_decreased',
    'sleep_declined',
    'movement_improved',
    'digestion_worsened',
    'coach_added_notes',
    'coach_completed_session',
    'member_inactive',
    'habit_streak_achieved',
    'wellness_index_changed_significantly',
    'body_assessment_completed',
    'assessment_submitted_for_coach_review',
    'wearable_synced',
    'hrv_declining',
    'recovery_excellent',
    'activity_declined',
    'movement_session_completed'
  ));

-- ============================================================
-- movement_sessions
-- ============================================================
create table movement_sessions (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references auth.users(id) on delete cascade,

  timezone text not null,
  local_date date not null,

  -- Lifecycle: generated and ready to view, started once the member opens
  -- the session experience, completed, or explicitly skipped (a real,
  -- honest state — never silently dropped).
  status text not null default 'ready' check (status in (
    'ready', 'in_progress', 'completed', 'skipped'
  )),

  focus_summary text not null,
  recovery_status text not null default 'unknown' check (recovery_status in (
    'ready', 'moderate', 'limited', 'rest', 'unknown'
  )),
  estimated_duration_minutes int not null default 0,

  -- Array of {label, domain, detail} — every entry traceable to a real
  -- fact the decision engine actually read (lib/movement/rules/facts.ts),
  -- never a canned line. Same "structured jsonb bag with a documented
  -- shape" convention as evidence_refs elsewhere in this schema.
  selection_reasons jsonb not null default '[]'::jsonb,

  -- Placeholder score pending richer signals — null until there's enough
  -- completed-session history to compute one (lib/movement/score.ts),
  -- never guessed at.
  movement_score numeric,

  generated_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  skipped_at timestamptz,
  skip_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index movement_sessions_member_idx on movement_sessions (member_id, local_date desc);

alter table movement_sessions enable row level security;

create policy member_read_own_movement_sessions on movement_sessions
  for select
  using (member_id = auth.uid());

create policy coach_read_assigned_movement_sessions on movement_sessions
  for select
  using (
    public.has_active_role(auth.uid(), 'coach')
    and public.is_active_coach_for(auth.uid(), member_id)
  );

create policy member_insert_own_movement_sessions on movement_sessions
  for insert
  with check (member_id = auth.uid());

create policy member_update_own_movement_sessions on movement_sessions
  for update
  using (member_id = auth.uid());

create policy coach_update_assigned_movement_sessions on movement_sessions
  for update
  using (
    public.has_active_role(auth.uid(), 'coach')
    and public.is_active_coach_for(auth.uid(), member_id)
  );

create policy platform_admin_all_movement_sessions on movement_sessions
  for all
  using (public.has_active_role(auth.uid(), 'platform_administrator'));

-- ============================================================
-- movement_session_exercises
-- ============================================================
create table movement_session_exercises (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references movement_sessions(id) on delete cascade,
  member_id uuid not null references auth.users(id) on delete cascade,

  -- Not a foreign key on purpose — see this file's header. A text key into
  -- whichever provider generated this session.
  exercise_id text not null,

  section text not null check (section in (
    'preparation', 'breathing', 'mobility', 'activation',
    'strength', 'conditioning', 'recovery'
  )),
  sequence_index int not null default 0,

  prescribed_sets int,
  prescribed_reps text,
  prescribed_tempo text,
  prescribed_rest_seconds int,
  estimated_duration_seconds int not null default 0,

  -- Why this exercise was picked over a sibling candidate (e.g. a pain
  -- report excluded the section's usual default) — null when it was
  -- simply the default pick for this section.
  substitution_reason text,

  completed boolean not null default false,
  completed_at timestamptz,
  member_notes text,

  created_at timestamptz not null default now()
);

create index movement_session_exercises_session_idx
  on movement_session_exercises (session_id, sequence_index);
create index movement_session_exercises_member_idx on movement_session_exercises (member_id);

alter table movement_session_exercises enable row level security;

create policy member_read_own_movement_session_exercises on movement_session_exercises
  for select
  using (member_id = auth.uid());

create policy coach_read_assigned_movement_session_exercises on movement_session_exercises
  for select
  using (
    public.has_active_role(auth.uid(), 'coach')
    and public.is_active_coach_for(auth.uid(), member_id)
  );

create policy member_insert_own_movement_session_exercises on movement_session_exercises
  for insert
  with check (member_id = auth.uid());

create policy member_update_own_movement_session_exercises on movement_session_exercises
  for update
  using (member_id = auth.uid());

create policy platform_admin_all_movement_session_exercises on movement_session_exercises
  for all
  using (public.has_active_role(auth.uid(), 'platform_administrator'));

-- ============================================================================
-- Universal Registry adapter seam (migration 40) — extend the existing
-- source_feature check constraint additively, and grant a narrow member
-- insert/update policy scoped to domain='movement', mirroring exactly how
-- migration 55 opened the same seam for food_lens_pattern_comparison. A
-- completed movement session's adherence summary has no coach-review gate,
-- so — like Food Lens — the member's own session is the writer.
-- ============================================================================
alter table registry_entries drop constraint registry_entries_source_feature_check;
alter table registry_entries add constraint registry_entries_source_feature_check
  check (source_feature in (
    'body_assessment_finding', 'assessment_ai_observation', 'wearable_daily_metric',
    'food_lens_pattern_comparison', 'movement_session_completed'
  ));

create policy member_insert_own_movement_registry_entries on registry_entries
  for insert
  with check (
    member_id = auth.uid()
    and domain = 'movement'
    and source_feature = 'movement_session_completed'
  );

create policy member_update_own_movement_registry_entries on registry_entries
  for update
  using (member_id = auth.uid() and domain = 'movement')
  with check (member_id = auth.uid() and domain = 'movement');

-- ============================================================================
-- health_timeline_events.event_type — widen additively for a completed
-- movement session, same convention migration 53 used for streak_milestone
-- etc.
-- ============================================================================
alter table health_timeline_events drop constraint health_timeline_events_event_type_check;
alter table health_timeline_events add constraint health_timeline_events_event_type_check
  check (event_type in (
    'onboarding_completed', 'reassessment_completed', 'checkin_submitted',
    'assessment_published', 'wearable_synced',
    'streak_milestone', 'trend_improving', 'trend_declining', 'wearable_connected',
    'movement_session_completed'
  ));

-- ============================================================================
-- conversation_sessions.entry_point — add 'movement', same additive
-- drop/re-add pattern migrations 37 and 55 used for 'body_assessment' and
-- 'food_lens'.
-- ============================================================================
alter table conversation_sessions drop constraint conversation_sessions_entry_point_check;
alter table conversation_sessions add constraint conversation_sessions_entry_point_check
  check (entry_point in (
    'nav',
    'today_focus',
    'today_easier_option',
    'today_why',
    'today_completed',
    'progress_pattern',
    'progress_improved',
    'progress_focus',
    'checkin_explain',
    'checkin_feeling',
    'dashboard',
    'profile',
    'assessment',
    'body_assessment',
    'food_lens',
    'movement'
  ));
