-- Extends notifications.type for the Proactive AI Coach (see
-- apps/consumer-web-app/lib/ai/agents/proactive-coach.ts) — same
-- additive-constraint-extension convention migration 43 already used for
-- intelligence_coach_alerts.alert_type. Without this, a proactive
-- coaching message (HRV declining, sleep declining, excellent recovery,
-- etc.) generated by the dispatcher can never be persisted into the one
-- table any member-facing "Coach Messages" surface reads from.
alter table notifications drop constraint notifications_type_check;
alter table notifications add constraint notifications_type_check
  check (type in ('assessment_report_published', 'proactive_coach_message'));
