-- Real adaptive onboarding assessment engine. Replaces the old reorder-only
-- "adaptive" branching (lib/onboarding/branching.ts, now used only by the
-- reassessment flow, which deliberately keeps its original fixed-12
-- behavior unchanged) with genuine per-concern question banks: 9
-- concern-specific banks (~16 candidate questions each) plus a small
-- "zoom out" shared pool covering Recovery/Lifestyle/Mindset, from which
-- lib/onboarding/adaptivePlan.ts + lib/adaptive-assessment-engine/ pick a
-- personalized subset per member.
--
-- The 12 legacy rows (seeded by migrations 49/68) are left completely
-- untouched — same question_key/question_version/domain/display_order —
-- so lib/onboarding/comparison.ts and lib/onboarding/guestObservation.ts,
-- which read several of those keys by exact name, need zero changes. New
-- columns default such that every legacy row is implicitly
-- question_pool = 'legacy', concern = null, weight = 1 — inert for
-- selection purposes, since the engine never runs over 'legacy' rows.
alter table onboarding_questions
  add column question_pool text not null default 'legacy'
    check (question_pool in ('legacy', 'concern_bank', 'shared_pool')),
  add column concern text,
  add column weight numeric not null default 1,
  add column requires jsonb,
  add column boosts jsonb,
  add column helper_text text;

comment on column onboarding_questions.question_pool is
  'legacy = the original fixed 12, always fetched alone for reassessments (getOnboardingQuestions). concern_bank = one of the 9 concern-specific deep-dive banks. shared_pool = the Phase 3b "zoom out" sampler (Recovery/Lifestyle/Mindset).';
comment on column onboarding_questions.concern is
  'Set only for question_pool = concern_bank — which primary_concern value this question''s bank belongs to (e.g. pain, weight, sleep). Null for legacy/shared_pool.';
comment on column onboarding_questions.weight is
  'Base selection score for lib/adaptive-assessment-engine. Irrelevant for legacy rows, which are never adaptively selected.';
comment on column onboarding_questions.requires is
  'Eligibility gate: [{question_key, op, value}], ALL must hold against already-collected answers. Null/empty = always eligible. May only reference primary_concern or another key in the SAME concern bank (or, for shared_pool, primary_concern) — see tests/onboarding-adaptive-plan.test.ts''s ordering-safety validator.';
comment on column onboarding_questions.boosts is
  'Additive personalization: [{question_key, op, value, amount}]. Same reference restriction as requires.';
comment on column onboarding_questions.helper_text is
  'Optional short line under the prompt for concern_bank/shared_pool questions, authored directly on the row. Legacy questions'' helper copy (where any exists) stays in lib/onboarding/coachCopy.ts''s COACH_HELPER instead.';

-- Idempotent, same pattern as migrations 49/68: safe to run against a
-- database that already has this content.
do $$
declare
  v_version_id uuid;
begin
  select id into v_version_id from onboarding_assessment_versions where assessment_version = 1;

  if v_version_id is null then
    raise exception 'No onboarding_assessment_versions row for version 1 — run migration 49 first.';
  end if;

  insert into onboarding_questions
    (question_key, assessment_version_id, question_version, display_order, prompt_text, helper_text,
     answer_type, allowed_values, domain, allows_not_sure, allows_not_applicable, allows_prefer_not_to_answer,
     question_pool, concern, weight, requires, boosts)
  values
  ('pain_primary_location', v_version_id, 1, 1000, 'Where in your body has been bothering you the most lately?', null, 'enum', '["neck","shoulders","upper_back","lower_back","hips","knees","feet_or_ankles","hands_or_wrists","widespread","other"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1.5, null, null),
  ('pain_secondary_location', v_version_id, 1, 1001, 'Is there a second spot that''s been acting up too, or is it really just the one area?', 'Select any others that apply.', 'multi_select', '["neck","shoulders","upper_back","lower_back","hips","knees","feet_or_ankles","hands_or_wrists","none_just_the_one_spot"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1, '[{"question_key":"pain_primary_location","op":"in","value":["neck","shoulders","upper_back","lower_back","hips","knees","feet_or_ankles","hands_or_wrists","other"]}]'::jsonb, null),
  ('pain_duration', v_version_id, 1, 1002, 'How long has this been part of your life — days, months, longer?', null, 'enum', '["under_2_weeks","2_weeks_to_3_months","3_to_12_months","over_a_year","on_and_off_for_years"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1.5, null, null),
  ('pain_pattern', v_version_id, 1, 1003, 'Is it there constantly, or does it come and go depending on the day?', null, 'enum', '["constant","comes_and_goes","only_with_certain_movements","mostly_gone_now"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_intensity_typical', v_version_id, 1, 1004, 'On a typical day, how much does it demand your attention?', '1 = barely notice it, 5 = hard to think about anything else.', 'numeric', null, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1.5, null, null),
  ('pain_worst_moments', v_version_id, 1, 1005, 'At its worst, how much does it throw off your day?', '1 = a minor annoyance, 5 = it stops me in my tracks.', 'numeric', null, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_previous_injury', v_version_id, 1, 1006, 'Does this trace back to a specific injury or event, or has it just crept in over time?', null, 'enum', '["specific_injury_or_accident","gradual_onset","after_a_surgery","not_sure_where_it_started"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_aggravating_activities', v_version_id, 1, 1007, 'What tends to set it off or make it worse?', 'Select any that apply.', 'multi_select', '["sitting_for_long_periods","standing_for_long_periods","bending_or_twisting","lifting","exercise_or_sports","sleeping_position","stress_or_tension","cold_weather","not_sure"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1.5, null, null),
  ('pain_relieving_activities', v_version_id, 1, 1008, 'And on the flip side — what actually helps, even a little?', 'Select any that apply.', 'multi_select', '["rest","gentle_movement_or_stretching","heat","ice","massage_or_bodywork","medication","nothing_reliably_helps"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_disrupts_sleep', v_version_id, 1, 1009, 'Does it ever wake you up at night or make it hard to get comfortable?', null, 'boolean', null, 'recovery', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_prior_treatment_tried', v_version_id, 1, 1010, 'Have you tried working on this before — physical therapy, a professional, anything at home?', null, 'enum', '["yes_saw_a_professional","yes_tried_things_on_my_own","no_havent_addressed_it_yet","currently_working_on_it"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_treatment_helped', v_version_id, 1, 1011, 'Did what you tried actually move the needle, or did it not really stick?', null, 'enum', '["helped_a_lot","helped_somewhat","didnt_really_help","too_soon_to_tell"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'pain', 1, '[{"question_key":"pain_prior_treatment_tried","op":"in","value":["yes_saw_a_professional","yes_tried_things_on_my_own","currently_working_on_it"]}]'::jsonb, null),
  ('pain_mood_impact', v_version_id, 1, 1012, 'Has dealing with this affected your mood or confidence at all?', '1 = not really, 5 = it weighs on me a lot.', 'numeric', null, 'mindset', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_activity_limited', v_version_id, 1, 1013, 'Is there something specific you love doing that this has gotten in the way of?', null, 'free_text', null, 'movement_energy', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_avoids_movement', v_version_id, 1, 1014, 'Would you say you hold back from moving or exercising because of it?', null, 'boolean', null, 'movement_energy', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('pain_daily_task_difficulty', v_version_id, 1, 1015, 'Are there everyday things — carrying groceries, playing with kids, getting up from a chair — that feel harder than they should?', null, 'enum', '["yes_several_things","yes_one_or_two_things","not_really","not_at_all"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'pain', 1, null, null),
  ('weight_desired_outcome', v_version_id, 1, 1016, 'If this went really well, what would actually be different in six months?', null, 'free_text', null, 'mindset', true, true, true, 'concern_bank', 'weight', 1.5, null, null),
  ('weight_previous_attempts', v_version_id, 1, 1017, 'How many real attempts have you made at this before?', null, 'enum', '["this_is_my_first_real_attempt","a_couple_of_times","many_times","i_feel_like_ive_tried_everything"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'weight', 1.5, null, null),
  ('weight_biggest_obstacle', v_version_id, 1, 1018, 'What''s gotten in the way the most in the past?', 'Select any that apply.', 'multi_select', '["cravings","lack_of_time","inconsistent_motivation","stress_or_emotions","social_situations","not_knowing_what_actually_works","plateaus","lack_of_energy"]'::jsonb, 'lifestyle', true, true, true, 'concern_bank', 'weight', 1.5, null, null),
  ('weight_hunger_level', v_version_id, 1, 1019, 'How would you describe your hunger on a normal day?', '1 = rarely feel hungry, 5 = feel hungry often, hard to ignore.', 'numeric', null, 'nutrition_digestion', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_craving_frequency', v_version_id, 1, 1020, 'How often do strong cravings show up for you?', null, 'enum', '["rarely","a_few_times_a_week","daily","multiple_times_a_day"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_craving_triggers', v_version_id, 1, 1021, 'When cravings hit, what tends to be behind them?', null, 'enum', '["stress_or_emotions","boredom","genuine_hunger","habit_or_time_of_day","being_around_certain_foods","not_sure"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'weight', 1, '[{"question_key":"weight_craving_frequency","op":"in","value":["a_few_times_a_week","daily","multiple_times_a_day"]}]'::jsonb, null),
  ('weight_energy_level', v_version_id, 1, 1022, 'How would you rate your everyday energy right now?', '1 = running on empty most days, 5 = genuinely energized.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_eating_pattern', v_version_id, 1, 1023, 'Which best describes how you tend to eat during the day?', null, 'enum', '["structured_meals","grazing_throughout_the_day","skip_meals_then_eat_a_lot_later","irregular_no_real_pattern"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_relationship_with_food', v_version_id, 1, 1024, 'Would you say your approach to food tends to be more restrictive, or more go-with-the-flow?', null, 'enum', '["very_restrictive","somewhat_restrictive","fairly_intuitive","very_intuitive_no_rules"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_emotional_eating', v_version_id, 1, 1025, 'Do you notice yourself eating in response to stress, boredom, or emotions, more than actual hunger?', null, 'boolean', null, 'mindset', true, true, true, 'concern_bank', 'weight', 1.5, null, null),
  ('weight_emotional_eating_frequency', v_version_id, 1, 1026, 'How often would you say that happens?', null, 'enum', '["rarely","sometimes","often","most_days"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'weight', 1, '[{"question_key":"weight_emotional_eating","op":"eq","value":true}]'::jsonb, null),
  ('weight_confidence_impact', v_version_id, 1, 1027, 'How much does this affect how confident you feel day to day?', '1 = doesn''t really touch it, 5 = it affects it a lot.', 'numeric', null, 'mindset', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_motivation_source', v_version_id, 1, 1028, 'What''s driving this for you right now, more than anything else?', null, 'enum', '["health_concerns","energy_and_vitality","how_i_look_and_feel","a_specific_event_or_milestone","longevity_for_family","confidence","other"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_support_system', v_version_id, 1, 1029, 'Do you have people around you supporting this, or are you mostly figuring it out on your own?', null, 'enum', '["strong_support","some_support","mostly_on_my_own","people_around_me_work_against_it"]'::jsonb, 'lifestyle', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_activity_level', v_version_id, 1, 1030, 'How would you describe your typical activity level right now?', null, 'enum', '["mostly_sedentary","lightly_active","moderately_active","very_active"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('weight_success_feeling', v_version_id, 1, 1031, 'Beyond a number on a scale, what would actually make you feel like this worked?', null, 'free_text', null, 'mindset', true, true, true, 'concern_bank', 'weight', 1, null, null),
  ('digestion_primary_concern', v_version_id, 1, 1032, 'What''s the main thing going on with your digestion right now?', null, 'enum', '["bloating","irregularity","discomfort_or_cramping","reflux_or_heartburn","gas","unpredictable_bathroom_habits","low_appetite","other"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1.5, null, null),
  ('digestion_secondary_concern', v_version_id, 1, 1033, 'Anything else going on alongside that, or is it really just the one thing?', 'Select any others that apply.', 'multi_select', '["bloating","irregularity","discomfort_or_cramping","reflux_or_heartburn","gas","unpredictable_bathroom_habits","low_appetite","none_just_the_one_thing"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1, '[{"question_key":"digestion_primary_concern","op":"in","value":["bloating","irregularity","discomfort_or_cramping","reflux_or_heartburn","gas","unpredictable_bathroom_habits","low_appetite","other"]}]'::jsonb, null),
  ('digestion_worst_time_of_day', v_version_id, 1, 1034, 'Is there a time of day when it tends to be worst — morning, after meals, evening?', null, 'enum', '["morning","midday","after_meals","evening","late_at_night","no_real_pattern"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_frequency', v_version_id, 1, 1035, 'How often would you say this is showing up?', null, 'enum', '["almost_every_day","a_few_times_a_week","about_once_a_week","occasionally"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1.5, null, null),
  ('digestion_duration', v_version_id, 1, 1036, 'How long has this been going on for you?', null, 'enum', '["under_a_month","1_to_6_months","6_months_to_a_year","over_a_year","on_and_off_for_years"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_severity_typical', v_version_id, 1, 1037, 'On a typical day it shows up, how much does it throw you off?', '1 = barely notice it, 5 = it derails my day.', 'numeric', null, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1.5, null, null),
  ('digestion_meal_relationship', v_version_id, 1, 1038, 'Does it seem tied to specific meals or eating patterns, or does it feel random?', null, 'enum', '["specific_foods","meal_size_or_timing","eating_too_fast","skipping_meals","feels_random","not_sure"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_trigger_foods', v_version_id, 1, 1039, 'Are there particular foods or drinks you''ve noticed tend to set it off?', null, 'free_text', null, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1, '[{"question_key":"digestion_meal_relationship","op":"eq","value":"specific_foods"}]'::jsonb, null),
  ('digestion_affects_energy', v_version_id, 1, 1040, 'Do you notice your energy dipping when your digestion is off?', null, 'boolean', null, 'movement_energy', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_affects_sleep', v_version_id, 1, 1041, 'Does it ever interfere with falling asleep or sleeping through the night?', null, 'boolean', null, 'recovery', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_prior_changes_tried', v_version_id, 1, 1042, 'Have you tried changing your diet or eliminating certain foods to get ahead of this?', null, 'enum', '["yes_worked_with_a_professional","yes_tried_it_myself","no_havent_tried_yet","currently_trying_something"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_changes_helped', v_version_id, 1, 1043, 'Did that actually make a difference, or did it not really change much?', null, 'enum', '["helped_a_lot","helped_somewhat","didnt_really_help","too_soon_to_tell"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'digestion', 1, '[{"question_key":"digestion_prior_changes_tried","op":"in","value":["yes_worked_with_a_professional","yes_tried_it_myself","currently_trying_something"]}]'::jsonb, null),
  ('digestion_stress_connection', v_version_id, 1, 1044, 'Have you noticed a connection between how stressed you''re feeling and how your digestion behaves?', '1 = no connection I can see, 5 = they track together closely.', 'numeric', null, 'mind_stress', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_hydration_habit', v_version_id, 1, 1045, 'How would you describe your water intake on a normal day?', null, 'enum', '["well_hydrated","could_be_better","i_barely_drink_water","not_sure"]'::jsonb, 'lifestyle', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_eating_pace', v_version_id, 1, 1046, 'When you eat, would you say you tend to rush, or take your time?', null, 'enum', '["usually_rushed","somewhere_in_between","usually_relaxed"]'::jsonb, 'lifestyle', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('digestion_social_impact', v_version_id, 1, 1047, 'Has this ever made you hesitant around meals out, travel, or social plans?', null, 'boolean', null, 'mindset', true, true, true, 'concern_bank', 'digestion', 1, null, null),
  ('sleep_falling_asleep_time', v_version_id, 1, 1048, 'Once you''re actually in bed, how long does it usually take you to fall asleep?', null, 'enum', '["under_10_minutes","10_to_20_minutes","20_to_40_minutes","over_40_minutes"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1.5, null, null),
  ('sleep_racing_mind', v_version_id, 1, 1049, 'As you''re trying to drift off, how much is your mind still running?', '1 = completely quiet, 5 = constant chatter.', 'numeric', null, 'mindset', true, true, true, 'concern_bank', 'sleep', 1.5, null, null),
  ('sleep_night_waking_frequency', v_version_id, 1, 1050, 'How often do you wake up in the middle of the night, once you''ve actually fallen asleep?', null, 'enum', '["rarely_or_never","once","twice","three_or_more_times"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1.5, null, null),
  ('sleep_waking_reason', v_version_id, 1, 1051, 'When you do wake up in the night, what''s usually behind it?', 'Select any that apply.', 'multi_select', '["need_the_bathroom","racing_thoughts","noise","too_hot_or_too_cold","a_partner_or_pet","discomfort","no_clear_reason","other"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, '[{"question_key":"sleep_night_waking_frequency","op":"in","value":["once","twice","three_or_more_times"]}]'::jsonb, null),
  ('sleep_back_to_sleep_ease', v_version_id, 1, 1052, 'Once you wake up in the night, how easily do you fall back asleep?', '1 = it takes forever, 5 = almost right away.', 'numeric', null, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_wake_feeling', v_version_id, 1, 1053, 'In that first moment you wake up in the morning, how do you actually feel?', null, 'enum', '["refreshed","okay_but_not_great","groggy","completely_exhausted"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1.5, null, null),
  ('sleep_morning_energy_ramp', v_version_id, 1, 1054, 'Once you''re up, how long does it take before you actually feel awake?', null, 'enum', '["im_awake_immediately","15_to_30_minutes","about_an_hour","most_of_the_morning"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_screens_before_bed', v_version_id, 1, 1055, 'Are you usually still on a screen right up until you try to fall asleep?', null, 'boolean', null, 'recovery', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_caffeine_timing', v_version_id, 1, 1056, 'What time does your last caffeine of the day usually land?', null, 'enum', '["before_noon","early_afternoon","late_afternoon","evening_or_later","i_dont_drink_caffeine"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_bedtime_wind_down', v_version_id, 1, 1057, 'Walk me through the last half hour before you turn the lights off — what does that usually look like?', null, 'free_text', null, 'recovery', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_reliance_on_aid', v_version_id, 1, 1058, 'Do you lean on anything — a supplement, a sound machine, a nightly ritual — to help you fall asleep?', null, 'boolean', null, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_environment_quality', v_version_id, 1, 1059, 'Is there anything about your bedroom itself that makes it harder to sleep well?', 'Select any that apply.', 'multi_select', '["too_much_light","noise","uncomfortable_temperature","uncomfortable_mattress_or_pillow","nothing_its_fine","other"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_weekday_weekend_consistency', v_version_id, 1, 1060, 'How consistent are your bed and wake times — weekdays compared to weekends?', '1 = totally different schedules, 5 = basically the same every day.', 'numeric', null, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_worry_content', v_version_id, 1, 1061, 'When your mind is looping at night, what''s it usually circling back to?', null, 'enum', '["work","health","relationships","money","nothing_specific_just_busy","other"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'sleep', 1, '[{"question_key":"sleep_racing_mind","op":"gte","value":3}]'::jsonb, null),
  ('sleep_naps', v_version_id, 1, 1062, 'Do you find yourself napping during the day?', null, 'enum', '["never","occasionally","regularly","i_need_to_but_cant"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('sleep_cant_sleep_response', v_version_id, 1, 1063, 'When you''ve been lying awake a while and sleep just isn''t coming, what do you usually do?', null, 'enum', '["stay_in_bed_and_wait_it_out","get_up_and_do_something_calm","check_my_phone","get_frustrated_and_toss_and_turn","other"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'sleep', 1, null, null),
  ('stress_carrying_level', v_version_id, 1, 1064, 'On a typical day, how much stress would you say you''re carrying?', '1 = barely any, 5 = about as much as you can handle.', 'numeric', null, 'mind_stress', true, true, true, 'concern_bank', 'stress', 1.5, null, null),
  ('stress_pattern', v_version_id, 1, 1065, 'Does your stress feel more like a constant hum in the background, or does it come in sharp waves?', null, 'enum', '["constant_low_level","sharp_waves","a_mix_of_both","depends_on_the_week"]'::jsonb, 'mind_stress', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('stress_physical_tension_location', v_version_id, 1, 1066, 'Where does stress tend to show up in your body first?', 'Select any that apply.', 'multi_select', '["jaw_or_teeth","neck_and_shoulders","stomach","chest","headaches","lower_back","nowhere_specific","other"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'stress', 1.5, null, null),
  ('stress_jaw_tension_frequency', v_version_id, 1, 1067, 'How often do you catch yourself clenching your jaw or grinding your teeth?', null, 'enum', '["never","occasionally","most_days","almost_always"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'stress', 1, '[{"question_key":"stress_physical_tension_location","op":"in","value":["jaw_or_teeth"]}]'::jsonb, null),
  ('stress_headache_frequency', v_version_id, 1, 1068, 'How often does stress seem to turn into a headache?', null, 'enum', '["never","rarely","a_few_times_a_month","weekly_or_more"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'stress', 1, '[{"question_key":"stress_physical_tension_location","op":"in","value":["headaches"]}]'::jsonb, null),
  ('stress_emotional_symptoms', v_version_id, 1, 1069, 'Which of these have you been feeling more than you''d like lately?', 'Select any that apply.', 'multi_select', '["irritability","overwhelm","anxiousness","sadness","numbness","restlessness","none_of_these"]'::jsonb, 'mind_stress', true, true, true, 'concern_bank', 'stress', 1.5, null, null),
  ('stress_overwhelm_frequency', v_version_id, 1, 1070, 'When overwhelm shows up, how often does it feel like genuinely too much?', null, 'enum', '["rarely","sometimes","often","most_days"]'::jsonb, 'mind_stress', true, true, true, 'concern_bank', 'stress', 1, '[{"question_key":"stress_emotional_symptoms","op":"in","value":["overwhelm"]}]'::jsonb, null),
  ('stress_bounce_back_speed', v_version_id, 1, 1071, 'After a stressful day or moment, how quickly do you feel like yourself again?', '1 = it lingers for days, 5 = pretty much right away.', 'numeric', null, 'recovery', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('stress_impact_on_sleep', v_version_id, 1, 1072, 'Does stress tend to follow you into bed and make it harder to fall asleep?', null, 'boolean', null, 'sleep', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('stress_impact_relationships', v_version_id, 1, 1073, 'How much does your stress spill over onto the people around you — snapping, going quiet, that kind of thing?', null, 'enum', '["not_at_all","a_little","noticeably","a_lot"]'::jsonb, 'mind_stress', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('stress_impact_eating', v_version_id, 1, 1074, 'When you''re stressed, what tends to happen to your eating?', null, 'enum', '["i_eat_more","i_eat_less","no_real_change","it_depends_on_the_day"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('stress_current_coping', v_version_id, 1, 1075, 'When stress hits, what do you actually reach for right now?', 'Select any that apply — no judgment, just want the real picture.', 'multi_select', '["exercise","food","alcohol","scrolling_my_phone","talking_to_someone","alone_time","nothing_in_particular","other"]'::jsonb, 'mind_stress', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('stress_has_an_outlet', v_version_id, 1, 1076, 'Right now, do you feel like you have any real outlet for stress?', null, 'boolean', null, 'mindset', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('stress_main_sources', v_version_id, 1, 1077, 'What''s driving most of your stress these days?', 'Select whatever''s realest — even a few at once.', 'multi_select', '["work","family","money","health","relationships","uncertainty_about_the_future","too_much_on_my_plate","other"]'::jsonb, 'mind_stress', true, true, true, 'concern_bank', 'stress', 1.5, null, null),
  ('stress_work_impact', v_version_id, 1, 1078, 'How is stress showing up in your work or day-to-day performance, if at all?', null, 'free_text', null, 'mind_stress', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('stress_wind_down_ability', v_version_id, 1, 1079, 'At the end of the day, how easily can you actually switch off?', '1 = I can''t switch off at all, 5 = I switch off easily.', 'numeric', null, 'recovery', true, true, true, 'concern_bank', 'stress', 1, null, null),
  ('energy_dip_time', v_version_id, 1, 1080, 'When does your energy tend to crash the hardest during the day?', null, 'enum', '["morning","mid_afternoon","evening","it_doesnt_really_dip","it_varies_a_lot"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'energy', 1.5, null, null),
  ('energy_caffeine_reliance', v_version_id, 1, 1081, 'How much are you leaning on caffeine to get through a normal day?', null, 'enum', '["none","one_serving","two_to_three_servings","four_or_more_servings"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'energy', 1.5, null, null),
  ('energy_sugar_reliance', v_version_id, 1, 1082, 'When your energy dips, do you find yourself reaching for something sugary or quick to fix it?', null, 'enum', '["often","sometimes","rarely","never"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_motivation_to_move', v_version_id, 1, 1083, 'How much does your energy level decide whether you actually move your body that day?', '1 = no connection at all, 5 = it completely decides it.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_motivation_to_socialize', v_version_id, 1, 1084, 'How often does low energy make you want to cancel plans or avoid people?', '1 = never, 5 = it''s usually the reason.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_sleep_connection', v_version_id, 1, 1085, 'How closely tied is your energy to how well you slept the night before?', null, 'enum', '["directly_tied","somewhat_tied","not_really_connected","not_sure"]'::jsonb, 'sleep', true, true, true, 'concern_bank', 'energy', 1.5, null, null),
  ('energy_nutrition_connection', v_version_id, 1, 1086, 'Do you notice your energy shifting based on what or when you eat?', null, 'enum', '["yes_clearly","somewhat","not_really","havent_really_paid_attention"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_changed_recently', v_version_id, 1, 1087, 'Has your energy changed recently, or has it felt like this for a long time?', null, 'enum', '["a_recent_change","a_gradual_decline_over_time","always_been_this_way","not_sure"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_recent_change_reason', v_version_id, 1, 1088, 'What do you think changed?', null, 'free_text', null, 'movement_energy', true, true, true, 'concern_bank', 'energy', 1, '[{"question_key":"energy_changed_recently","op":"eq","value":"a_recent_change"}]'::jsonb, null),
  ('energy_mental_vs_physical', v_version_id, 1, 1089, 'Is it more your body that feels tired, or your mind — or both?', null, 'enum', '["mostly_physical","mostly_mental","both_equally","not_sure"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_ideal_day_feeling', v_version_id, 1, 1090, 'If you had a genuinely energized day, what would that actually feel like for you?', null, 'free_text', null, 'mindset', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_stress_drain', v_version_id, 1, 1091, 'How much does stress feel like it''s draining your energy right now?', '1 = not at all, 5 = it''s the main thing draining me.', 'numeric', null, 'mind_stress', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_exercise_frequency', v_version_id, 1, 1092, 'How often are you moving your body in a typical week — walks, workouts, anything active?', null, 'enum', '["rarely_or_never","once_or_twice","a_few_times","most_days"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'energy', 1.5, null, null),
  ('energy_exercise_effect', v_version_id, 1, 1093, 'After you''ve been active, how does your energy usually respond?', null, 'enum', '["it_boosts_my_energy","it_drains_me_for_the_rest_of_the_day","it_depends_on_the_day","no_noticeable_effect"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'energy', 1, '[{"question_key":"energy_exercise_frequency","op":"in","value":["once_or_twice","a_few_times","most_days"]}]'::jsonb, null),
  ('energy_morning_startup', v_version_id, 1, 1094, 'Do you wake up already feeling behind on energy, before the day''s even started?', null, 'boolean', null, 'sleep', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('energy_drainers', v_version_id, 1, 1095, 'What tends to drain your energy the most in a normal week?', 'Select any that apply.', 'multi_select', '["poor_sleep","stress","skipping_meals","too_much_screen_time","lack_of_movement","an_overloaded_schedule","not_sure","other"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'energy', 1, null, null),
  ('performance_definition', v_version_id, 1, 1096, 'When you picture yourself performing at your best, what does that actually look like day to day?', null, 'free_text', null, 'mindset', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_activity_type', v_version_id, 1, 1097, 'What does your current training or activity mostly look like?', 'Select any that apply.', 'multi_select', '["strength_training","endurance_or_cardio","team_or_individual_sport","functional_daily_movement","mobility_or_flexibility_work","other"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1.5, null, null),
  ('performance_training_frequency', v_version_id, 1, 1098, 'In a typical week, how many days are you actually training or working on this?', null, 'enum', '["0_to_1","2_to_3","4_to_5","6_plus"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_training_intensity', v_version_id, 1, 1099, 'On the days you do train, how hard would you say you''re pushing yourself?', '1 = pretty easy effort, 5 = leaving everything out there.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_plateau', v_version_id, 1, 1100, 'Does it feel like your progress has stalled recently, even though you''re still putting in the work?', null, 'boolean', null, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1.5, null, null),
  ('performance_plateau_duration', v_version_id, 1, 1101, 'About how long has it felt like you''ve been stuck at this level?', null, 'enum', '["less_than_a_month","one_to_three_months","three_to_six_months","over_six_months"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1, '[{"question_key":"performance_plateau","op":"eq","value":true}]'::jsonb, null),
  ('performance_sleep_quality', v_version_id, 1, 1102, 'How rested do you typically feel heading into a training day or a big effort?', '1 = running on empty, 5 = fully rested.', 'numeric', null, 'sleep', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_recovery_between_efforts', v_version_id, 1, 1103, 'After a hard session or event, how fully do you feel recovered before the next one?', '1 = still beat up, 5 = completely bounced back.', 'numeric', null, 'recovery', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_consistency', v_version_id, 1, 1104, 'How consistent has your training or practice actually been over the last month or so?', '1 = on-and-off at best, 5 = like clockwork.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_consistency_barrier', v_version_id, 1, 1105, 'What tends to knock you off your rhythm?', 'Select any that apply.', 'multi_select', '["time","energy","motivation","injury_or_pain","travel_or_schedule","life_stress","other"]'::jsonb, 'lifestyle', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_specific_goal', v_version_id, 1, 1106, 'Is there a specific goal, event, or milestone you''re training toward right now?', null, 'boolean', null, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1.5, null, null),
  ('performance_goal_description', v_version_id, 1, 1107, 'Tell me about it — what are you working toward?', null, 'free_text', null, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1, '[{"question_key":"performance_specific_goal","op":"eq","value":true}]'::jsonb, null),
  ('performance_goal_timeline', v_version_id, 1, 1108, 'How far out is that goal?', null, 'enum', '["within_a_month","one_to_three_months","three_to_six_months","six_months_plus","no_fixed_date"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'performance', 1, '[{"question_key":"performance_specific_goal","op":"eq","value":true}]'::jsonb, null),
  ('performance_past_obstacle', v_version_id, 1, 1109, 'Looking back, what''s most often gotten in the way of you performing the way you want to?', null, 'enum', '["injury_or_pain","burnout_or_overtraining","lack_of_time","lack_of_structure","motivation_dips","nerves_or_pressure","other"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_mental_composure', v_version_id, 1, 1110, 'When it really counts — a big lift, a race, a big moment at work — how focused and composed do you feel?', '1 = rattled and scattered, 5 = locked in and confident.', 'numeric', null, 'mindset', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('performance_fueling_habits', v_version_id, 1, 1111, 'How would you describe the way you fuel your body around training or big performance days?', null, 'enum', '["dialed_in","pretty_good","inconsistent","rarely_think_about_it"]'::jsonb, 'nutrition_digestion', true, true, true, 'concern_bank', 'performance', 1, null, null),
  ('healthy_aging_definition', v_version_id, 1, 1112, 'When you imagine aging well, what does that actually look like for you?', null, 'free_text', null, 'mindset', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_mobility_trend', v_version_id, 1, 1113, 'Compared to a few years ago, how would you rate your flexibility and range of motion today?', '1 = noticeably more limited, 5 = just as free as ever.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_strength_trend', v_version_id, 1, 1114, 'Have you noticed a real change in your overall strength over the past few years?', null, 'enum', '["noticeably_stronger","about_the_same","some_decline","significant_decline"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'healthy_aging', 1.5, null, null),
  ('healthy_aging_strength_area', v_version_id, 1, 1115, 'Where have you noticed that most?', 'Select any that apply.', 'multi_select', '["legs_and_hips","core","upper_body","grip_strength","overall_stamina","not_sure"]'::jsonb, 'movement_energy', true, true, true, 'concern_bank', 'healthy_aging', 1, '[{"question_key":"healthy_aging_strength_trend","op":"in","value":["some_decline","significant_decline"]}]'::jsonb, null),
  ('healthy_aging_balance_confidence', v_version_id, 1, 1116, 'How confident do you feel in your balance and stability day to day?', '1 = not confident at all, 5 = completely steady.', 'numeric', null, 'pain_structural', true, true, true, 'concern_bank', 'healthy_aging', 1.5, null, null),
  ('healthy_aging_joint_health', v_version_id, 1, 1117, 'How would you describe your joints these days — knees, hips, shoulders?', null, 'enum', '["feel_great","occasional_stiffness","regular_discomfort","significant_limitation"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_cognitive_sharpness', v_version_id, 1, 1118, 'How sharp does your memory and focus feel lately, compared to how they used to?', '1 = noticeably foggier, 5 = just as sharp as ever.', 'numeric', null, 'mindset', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_family_history', v_version_id, 1, 1119, 'Is there anything in your family''s health history that feels worth understanding better as you think about your own aging?', null, 'boolean', null, 'mindset', true, true, true, 'concern_bank', 'healthy_aging', 1.5, null, null),
  ('healthy_aging_family_history_detail', v_version_id, 1, 1120, 'What''s on your mind there?', null, 'free_text', null, 'mindset', true, true, true, 'concern_bank', 'healthy_aging', 1, '[{"question_key":"healthy_aging_family_history","op":"eq","value":true}]'::jsonb, null),
  ('healthy_aging_independence_goal', v_version_id, 1, 1121, 'Looking 10 or 20 years down the road, what do you want to still be fully able to do on your own?', 'Select any that apply.', 'multi_select', '["play_with_grandkids_or_kids","travel_easily","live_without_assistance","keep_doing_a_hobby_or_sport","work_as_long_as_i_want","other"]'::jsonb, 'lifestyle', true, true, true, 'concern_bank', 'healthy_aging', 1.5, null, null),
  ('healthy_aging_energy_trend', v_version_id, 1, 1122, 'Compared to a few years ago, how''s your overall energy and vitality?', '1 = much lower than it was, 5 = just as high as ever.', 'numeric', null, 'recovery', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_recovery_pace', v_version_id, 1, 1123, 'After a physically demanding day, how long does it usually take you to feel back to normal?', null, 'enum', '["same_day","a_day_or_two","several_days","over_a_week"]'::jsonb, 'recovery', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_daily_function_worry', v_version_id, 1, 1124, 'Is there a specific everyday movement — stairs, getting up from the floor, carrying groceries — that''s started to feel harder?', null, 'enum', '["nothing_comes_to_mind","stairs","getting_up_and_down","carrying_or_lifting","walking_long_distances","other"]'::jsonb, 'pain_structural', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_activity_level', v_version_id, 1, 1125, 'How physically active would you say you are in a normal week?', '1 = mostly sedentary, 5 = very active.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_motivation_source', v_version_id, 1, 1126, 'What''s really driving you to focus on this now?', null, 'enum', '["a_health_scare","watching_a_loved_one","wanting_to_stay_independent","general_prevention","a_specific_goal","other"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('healthy_aging_role_model', v_version_id, 1, 1127, 'Who''s someone you consider to be aging really well, and what stands out about them?', null, 'free_text', null, 'mindset', true, true, true, 'concern_bank', 'healthy_aging', 1, null, null),
  ('general_optimization_better_definition', v_version_id, 1, 1128, 'If things were meaningfully better a year from now, what would actually be different?', null, 'free_text', null, 'all', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('general_optimization_priority_area', v_version_id, 1, 1129, 'If you had to pick just one area to focus on first, what would it be?', null, 'enum', '["sleep","movement_and_energy","nutrition","stress_and_mindset","structure_and_habits","not_sure"]'::jsonb, 'all', true, true, true, 'concern_bank', 'general_optimization', 1.5, null, null),
  ('general_optimization_habit_satisfaction', v_version_id, 1, 1130, 'Overall, how satisfied are you with your day-to-day habits right now?', '1 = not satisfied at all, 5 = genuinely happy with them.', 'numeric', null, 'lifestyle', true, true, true, 'concern_bank', 'general_optimization', 1.5, null, null),
  ('general_optimization_growth_area', v_version_id, 1, 1131, 'If you''re honest with yourself, where do you already sense the biggest opportunity for growth?', null, 'enum', '["sleep","movement","nutrition","stress_management","consistency_and_follow_through","relationship_with_food_or_body","not_sure"]'::jsonb, 'all', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('general_optimization_past_success', v_version_id, 1, 1132, 'Have you successfully built a healthy habit before, even a small one?', null, 'boolean', null, 'mindset', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('general_optimization_past_success_area', v_version_id, 1, 1133, 'Where in life have you made a change like that actually stick?', 'Select any that apply.', 'multi_select', '["nutrition","movement","sleep","stress_management","a_totally_different_area"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'general_optimization', 1, '[{"question_key":"general_optimization_past_success","op":"eq","value":true}]'::jsonb, null),
  ('general_optimization_health_relationship', v_version_id, 1, 1134, 'Right now, how would you describe your relationship with your own health?', null, 'enum', '["a_partnership","a_chore","a_source_of_stress","something_i_avoid_thinking_about","pretty_good_honestly"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'general_optimization', 1, null, '[{"question_key":"primary_concern","op":"eq","value":"other","amount":1.5}]'::jsonb),
  ('general_optimization_small_win', v_version_id, 1, 1135, 'What would a small, real win in the next couple of weeks actually look like for you?', null, 'free_text', null, 'all', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('general_optimization_structure_preference', v_version_id, 1, 1136, 'Are you someone who does better with a lot of structure, or a lot of flexibility?', null, 'enum', '["clear_structure","some_structure","mostly_flexible","fully_flexible"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'general_optimization', 1.5, null, null),
  ('general_optimization_movement_frequency', v_version_id, 1, 1137, 'In a typical week, how much are you moving your body?', '1 = barely at all, 5 = very regularly.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'general_optimization', 1, null, '[{"question_key":"primary_concern","op":"eq","value":"movement","amount":1.5}]'::jsonb),
  ('general_optimization_nutrition_confidence', v_version_id, 1, 1138, 'How confident do you feel in the way you''re eating day to day?', '1 = not confident at all, 5 = very confident.', 'numeric', null, 'nutrition_digestion', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('general_optimization_stress_level', v_version_id, 1, 1139, 'How would you rate your day-to-day stress right now?', '1 = very low, 5 = very high.', 'numeric', null, 'mindset', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('general_optimization_energy_levels', v_version_id, 1, 1140, 'How would you rate your everyday energy levels lately?', '1 = running on empty, 5 = consistently energized.', 'numeric', null, 'movement_energy', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('general_optimization_biggest_barrier', v_version_id, 1, 1141, 'What usually derails you when you''re trying to build something new?', 'Select any that apply.', 'multi_select', '["time","energy","motivation","knowledge","support","consistency","other"]'::jsonb, 'lifestyle', true, true, true, 'concern_bank', 'general_optimization', 1, null, '[{"question_key":"primary_concern","op":"eq","value":"habits","amount":1.5}]'::jsonb),
  ('general_optimization_motivation_source', v_version_id, 1, 1142, 'What''s really motivating you to focus on your health right now?', null, 'enum', '["a_specific_goal","feeling_better_day_to_day","a_health_scare","someone_i_care_about","general_prevention","other"]'::jsonb, 'mindset', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('general_optimization_support_system', v_version_id, 1, 1143, 'Do you feel like you have people around you who support your health goals?', null, 'boolean', null, 'lifestyle', true, true, true, 'concern_bank', 'general_optimization', 1, null, null),
  ('shared_recovery_soreness_frequency', v_version_id, 1, 1144, 'How often do you feel overly sore or run-down after being active?', null, 'enum', '["rarely","sometimes","often","constantly"]'::jsonb, 'recovery', true, true, true, 'shared_pool', null, 1, null, null),
  ('shared_recovery_rest_days', v_version_id, 1, 1145, 'How many rest or recovery days do you usually build into your week?', null, 'enum', '["0","1","2","3+"]'::jsonb, 'recovery', true, true, true, 'shared_pool', null, 1, null, null),
  ('shared_recovery_bounce_back', v_version_id, 1, 1146, 'After a demanding day, how quickly would you say your body bounces back?', null, 'numeric', null, 'recovery', true, true, true, 'shared_pool', null, 1, null, '[{"question_key":"primary_concern","op":"in","value":["pain","performance","healthy_aging","movement"],"amount":1.5}]'::jsonb),
  ('shared_recovery_injury_history', v_version_id, 1, 1147, 'Do you have any past injuries that still affect how you move today?', null, 'boolean', null, 'recovery', true, true, true, 'shared_pool', null, 1, null, '[{"question_key":"primary_concern","op":"eq","value":"pain","amount":1.5}]'::jsonb),
  ('shared_lifestyle_routine_consistency', v_version_id, 1, 1148, 'How consistent is your daily routine, day to day?', '1 = it changes constantly, 5 = it looks about the same every day.', 'numeric', null, 'lifestyle', true, true, true, 'shared_pool', null, 1, null, null),
  ('shared_lifestyle_support_system', v_version_id, 1, 1149, 'How much support do you feel you have from people around you for your health goals?', null, 'enum', '["strong","some","little","none"]'::jsonb, 'lifestyle', true, true, true, 'shared_pool', null, 1, null, null),
  ('shared_lifestyle_time_availability', v_version_id, 1, 1150, 'On a typical day, how much time do you feel you genuinely have for yourself?', null, 'enum', '["almost_none","a_little","a_fair_amount","plenty"]'::jsonb, 'lifestyle', true, true, true, 'shared_pool', null, 1, null, null),
  ('shared_lifestyle_biggest_barrier', v_version_id, 1, 1151, 'What tends to get in the way of sticking with healthy habits?', 'Select any that apply.', 'multi_select', '["time","energy","motivation","knowledge","cost","consistency","other"]'::jsonb, 'lifestyle', true, true, true, 'shared_pool', null, 1, null, '[{"question_key":"primary_concern","op":"in","value":["weight","habits","general_optimization"],"amount":1.5}]'::jsonb),
  ('shared_mindset_self_talk', v_version_id, 1, 1152, 'When things don''t go as planned with your health, how would you describe your inner voice?', null, 'enum', '["mostly_kind","mixed","mostly_critical"]'::jsonb, 'mindset', true, true, true, 'shared_pool', null, 1, null, null),
  ('shared_mindset_optimism', v_version_id, 1, 1153, 'How hopeful do you feel about making real progress from here?', null, 'numeric', null, 'mindset', true, true, true, 'shared_pool', null, 1, null, '[{"question_key":"primary_concern","op":"in","value":["stress","general_optimization","other"],"amount":1.5}]'::jsonb),
  ('shared_mindset_past_success', v_version_id, 1, 1154, 'Have you experienced real success with a health change before, even a small one?', null, 'boolean', null, 'mindset', true, true, true, 'shared_pool', null, 1, null, null),
  ('shared_mindset_biggest_why', v_version_id, 1, 1155, 'What''s the real reason this matters to you right now?', null, 'free_text', null, 'mindset', true, true, true, 'shared_pool', null, 1, null, '[{"question_key":"primary_concern","op":"in","value":["weight","habits"],"amount":1.5}]'::jsonb)
  on conflict (question_key, question_version) do nothing;
end $$;
