-- notifications had no member-insert policy — fine when its only writer
-- was a coach publishing an assessment report (migration 39), but the
-- Proactive AI Coach (lib/ai/agents/proactive-coach.ts) now writes a
-- notification from inside the same dispatcher that already runs under
-- the *triggering member's own session* whenever a member connects or
-- syncs their own wearable (app/actions/wearables.ts) — the same
-- session-scoped-write posture ai_events/ai_insights/ai_actions already
-- support via their own member_insert_own_* policies (migration 27).
-- Without this, insertNotification's write would fail RLS silently
-- (matching every other best-effort write in this codebase) and a
-- member-triggered proactive message would simply never appear, only
-- ones generated by the service-role daily cron would.
create policy member_insert_own_notifications on notifications
  for insert
  with check (member_id = auth.uid());
