/**
 * Internal placeholder exercise catalog — architecture demonstration only.
 * A small, hand-authored set (two per session section, plus two strength
 * variations) exists purely so the provider abstraction
 * (lib/movement/providers/) and the decision engine
 * (lib/movement/rules/engine.ts) have real data to operate on end to end.
 *
 * This is explicitly NOT a real exercise library. When a real one is
 * integrated (Exercise.com, Physitrack, our own video library, a custom
 * API), it becomes a new MovementExerciseProvider implementation reading
 * from that source instead of this file — nothing that imports the
 * provider interface changes. See lib/movement/providers/registry.ts.
 */

import type { MovementExercise } from '@mef/shared-types-contracts';

export const MOVEMENT_EXERCISE_CATALOG: MovementExercise[] = [
  {
    exercise_id: 'prep_general_warmup',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'General Movement Warm-Up',
    category: 'preparation',
    movement_pattern: 'general_warmup',
    equipment: ['none'],
    primary_muscles: ['full_body'],
    secondary_muscles: [],
    difficulty: 'beginner',
    contraindications: [],
    coaching_cues: ['Move at an easy, conversational pace', 'Let your breathing set the rhythm'],
    common_mistakes: ['Rushing through it', 'Holding your breath'],
    default_sets: 1,
    default_reps: '90s',
    default_tempo: null,
    default_rest_seconds: 0,
    estimated_duration_seconds: 90,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'March in place, swinging your arms naturally.',
      'Add gentle arm circles, forward and back.',
      'Roll your shoulders and rotate your ankles.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'prep_joint_mobility_flow',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Joint-by-Joint Mobility Flow',
    category: 'preparation',
    movement_pattern: 'general_warmup',
    equipment: ['none'],
    primary_muscles: ['full_body'],
    secondary_muscles: [],
    difficulty: 'beginner',
    contraindications: [],
    coaching_cues: ['Work from ankles up to neck', 'Small, controlled circles — no forcing range'],
    common_mistakes: ['Skipping joints that feel fine', 'Moving too fast to feel anything'],
    default_sets: 1,
    default_reps: '8 each direction',
    default_tempo: null,
    default_rest_seconds: 0,
    estimated_duration_seconds: 120,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Circle each ankle, then each wrist.',
      'Rotate hips and shoulders through a comfortable range.',
      'Finish with gentle neck rotations.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'breathing_diaphragmatic',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Diaphragmatic Breathing',
    category: 'breathing',
    movement_pattern: 'breath',
    equipment: ['none'],
    primary_muscles: ['diaphragm'],
    secondary_muscles: ['intercostals'],
    difficulty: 'beginner',
    contraindications: [],
    coaching_cues: ['Expand your belly, not your chest', 'Exhale longer than you inhale'],
    common_mistakes: ['Breathing into the chest only', 'Rushing the exhale'],
    default_sets: 1,
    default_reps: '10 breaths',
    default_tempo: '4-0-6-0',
    default_rest_seconds: 0,
    estimated_duration_seconds: 100,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Lie down or sit tall, one hand on your belly.',
      'Inhale through your nose, feeling your belly rise.',
      'Exhale slowly through your mouth, feeling your belly fall.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'breathing_box',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Box Breathing',
    category: 'breathing',
    movement_pattern: 'breath',
    equipment: ['none'],
    primary_muscles: ['diaphragm'],
    secondary_muscles: [],
    difficulty: 'beginner',
    contraindications: [],
    coaching_cues: ['Keep the four counts even', 'Stay relaxed through the holds'],
    common_mistakes: ['Tensing the shoulders during the hold', 'Uneven counts'],
    default_sets: 1,
    default_reps: '6 rounds',
    default_tempo: '4-4-4-4',
    default_rest_seconds: 0,
    estimated_duration_seconds: 100,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Inhale for 4 counts.',
      'Hold for 4 counts.',
      'Exhale for 4 counts, then hold empty for 4 counts.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'mobility_hip_flexor_stretch',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Half-Kneeling Hip Flexor Stretch',
    category: 'mobility',
    movement_pattern: 'hip_hinge',
    equipment: ['mat'],
    primary_muscles: ['hip_flexors'],
    secondary_muscles: ['quadriceps'],
    difficulty: 'beginner',
    contraindications: ['acute_hip_pain', 'acute_knee_pain'],
    coaching_cues: ['Tuck the pelvis slightly under', 'Keep the torso tall, not leaning forward'],
    common_mistakes: ['Arching the lower back', 'Leaning the torso instead of shifting the hip'],
    default_sets: 2,
    default_reps: '30s each side',
    default_tempo: null,
    default_rest_seconds: 15,
    estimated_duration_seconds: 150,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Kneel on one knee, other foot planted in front.',
      'Gently shift your hips forward until you feel a stretch in front of the back hip.',
      'Hold, breathing normally, then switch sides.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'mobility_thoracic_rotation',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Open-Book Thoracic Rotation',
    category: 'mobility',
    movement_pattern: 'rotation',
    equipment: ['mat'],
    primary_muscles: ['thoracic_spine'],
    secondary_muscles: ['obliques'],
    difficulty: 'beginner',
    contraindications: ['acute_low_back_pain'],
    coaching_cues: [
      'Rotate from the mid-back, not the lower back',
      'Let your eyes follow your top hand',
    ],
    common_mistakes: ['Rotating through the hips instead of the spine', 'Rushing the movement'],
    default_sets: 2,
    default_reps: '8 each side',
    default_tempo: '2-1-2-0',
    default_rest_seconds: 20,
    estimated_duration_seconds: 150,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Lie on your side, knees stacked and bent to 90 degrees.',
      'Reach your top arm across your body, then open it toward the ceiling and floor behind you.',
      'Follow the movement with your gaze and return with control.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'activation_glute_bridge',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Glute Bridge',
    category: 'activation',
    movement_pattern: 'hip_hinge',
    equipment: ['mat'],
    primary_muscles: ['glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    difficulty: 'beginner',
    contraindications: ['acute_low_back_pain'],
    coaching_cues: ['Squeeze the glutes at the top', 'Press through the heels'],
    common_mistakes: ['Overarching the lower back at the top', 'Pushing through the toes'],
    default_sets: 3,
    default_reps: '12',
    default_tempo: '2-1-1-0',
    default_rest_seconds: 30,
    estimated_duration_seconds: 180,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Lie on your back, knees bent, feet flat hip-width apart.',
      'Drive through your heels to lift your hips until your body forms a straight line.',
      'Lower with control and repeat.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'activation_scapular_retraction',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Band Pull-Apart',
    category: 'activation',
    movement_pattern: 'pull',
    equipment: ['resistance_band'],
    primary_muscles: ['rear_delts', 'rhomboids'],
    secondary_muscles: ['traps'],
    difficulty: 'beginner',
    contraindications: ['acute_shoulder_pain'],
    coaching_cues: ['Lead with the shoulder blades, not the hands', 'Keep the ribs down'],
    common_mistakes: ['Shrugging the shoulders up', 'Arching the back to help'],
    default_sets: 3,
    default_reps: '15',
    default_tempo: '1-1-2-0',
    default_rest_seconds: 30,
    estimated_duration_seconds: 150,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Hold a light resistance band with both hands, arms extended in front.',
      'Pull the band apart by squeezing your shoulder blades together.',
      'Return with control and repeat.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'strength_bodyweight_squat',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Bodyweight Squat',
    category: 'strength',
    movement_pattern: 'squat',
    equipment: ['none'],
    primary_muscles: ['quadriceps', 'glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    difficulty: 'intermediate',
    contraindications: ['acute_knee_pain'],
    coaching_cues: [
      'Sit back like reaching for a chair',
      'Keep the chest tall, knees tracking over toes',
    ],
    common_mistakes: ['Knees caving inward', 'Rounding the lower back at the bottom'],
    default_sets: 3,
    default_reps: '10-12',
    default_tempo: '3-1-1-0',
    default_rest_seconds: 45,
    estimated_duration_seconds: 240,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Stand with feet shoulder-width apart, toes slightly turned out.',
      'Bend your hips and knees to lower down as if sitting into a chair.',
      'Drive through your heels to stand back up.',
    ],
    easier_variation_id: 'strength_box_squat',
    harder_variation_id: 'strength_goblet_squat',
    notes: null,
  },
  {
    exercise_id: 'strength_box_squat',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Box Squat',
    category: 'strength',
    movement_pattern: 'squat',
    equipment: ['bench'],
    primary_muscles: ['quadriceps', 'glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    difficulty: 'beginner',
    contraindications: ['acute_knee_pain'],
    coaching_cues: [
      'Lightly tap the box, don’t sit fully into it',
      'Keep the shins close to vertical',
    ],
    common_mistakes: ['Plopping down onto the box', 'Losing tension at the bottom'],
    default_sets: 3,
    default_reps: '10',
    default_tempo: '3-1-1-0',
    default_rest_seconds: 45,
    estimated_duration_seconds: 240,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Stand in front of a sturdy bench or box, feet shoulder-width apart.',
      'Lower down under control until you lightly touch the box.',
      'Drive back up through your heels without fully sitting down.',
    ],
    easier_variation_id: null,
    harder_variation_id: 'strength_bodyweight_squat',
    notes: null,
  },
  {
    exercise_id: 'strength_goblet_squat',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Goblet Squat',
    category: 'strength',
    movement_pattern: 'squat',
    equipment: ['kettlebell', 'moderate_dumbbells'],
    primary_muscles: ['quadriceps', 'glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    difficulty: 'advanced',
    contraindications: ['acute_knee_pain', 'acute_shoulder_pain'],
    coaching_cues: [
      'Hold the weight close to your chest',
      'Use your elbows to gently push your knees out',
    ],
    common_mistakes: [
      'Letting the weight drift away from the chest',
      'Rounding forward at the bottom',
    ],
    default_sets: 3,
    default_reps: '8-10',
    default_tempo: '3-1-1-0',
    default_rest_seconds: 60,
    estimated_duration_seconds: 240,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Hold a kettlebell or dumbbell vertically against your chest.',
      'Squat down between your knees, keeping your torso upright.',
      'Drive through your heels to stand back up.',
    ],
    easier_variation_id: 'strength_bodyweight_squat',
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'strength_incline_pushup',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Incline Push-Up',
    category: 'strength',
    movement_pattern: 'push',
    equipment: ['bench'],
    primary_muscles: ['chest', 'triceps'],
    secondary_muscles: ['shoulders', 'core'],
    difficulty: 'beginner',
    contraindications: ['acute_shoulder_pain', 'acute_wrist_pain'],
    coaching_cues: [
      'Keep a straight line from shoulders to ankles',
      'Elbows at roughly 45 degrees from the body',
    ],
    common_mistakes: ['Sagging the hips', 'Flaring the elbows straight out to the sides'],
    default_sets: 3,
    default_reps: '10-15',
    default_tempo: '2-1-1-0',
    default_rest_seconds: 45,
    estimated_duration_seconds: 210,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Place your hands on a sturdy bench, body in a straight line.',
      'Lower your chest toward the bench with control.',
      'Push back up to the starting position.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'conditioning_step_ups',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Step-Ups',
    category: 'conditioning',
    movement_pattern: 'gait',
    equipment: ['bench'],
    primary_muscles: ['quadriceps', 'glutes'],
    secondary_muscles: ['calves'],
    difficulty: 'intermediate',
    contraindications: ['acute_knee_pain'],
    coaching_cues: ['Drive through the whole foot on the step', 'Control the descent'],
    common_mistakes: ['Pushing off the trailing leg', 'Stepping onto a surface that’s too high'],
    default_sets: 3,
    default_reps: '10 each leg',
    default_tempo: null,
    default_rest_seconds: 45,
    estimated_duration_seconds: 240,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Stand in front of a sturdy step or bench.',
      'Step up fully with one foot, standing tall at the top.',
      'Step back down with control and alternate legs.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'conditioning_marching_intervals',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Marching Intervals',
    category: 'conditioning',
    movement_pattern: 'gait',
    equipment: ['none'],
    primary_muscles: ['hip_flexors', 'core'],
    secondary_muscles: ['quadriceps'],
    difficulty: 'beginner',
    contraindications: [],
    coaching_cues: ['Drive the knees up with control', 'Keep your breathing steady'],
    common_mistakes: ['Leaning back excessively', 'Losing rhythm mid-interval'],
    default_sets: 4,
    default_reps: '30s on / 30s off',
    default_tempo: null,
    default_rest_seconds: 30,
    estimated_duration_seconds: 240,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'March in place, driving your knees up toward hip height.',
      'Keep a steady, sustainable pace for the work interval.',
      'Walk it out gently during the rest interval.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'recovery_foam_rolling',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Foam Rolling — Lower Body',
    category: 'recovery',
    movement_pattern: 'self_myofascial_release',
    equipment: ['foam_roller'],
    primary_muscles: ['quadriceps', 'calves'],
    secondary_muscles: ['hamstrings'],
    difficulty: 'beginner',
    contraindications: [],
    coaching_cues: [
      'Roll slowly, pausing on tender spots',
      'Keep breathing — don’t brace against it',
    ],
    common_mistakes: ['Rolling directly over a joint', 'Rushing across each muscle'],
    default_sets: 1,
    default_reps: '60s each area',
    default_tempo: null,
    default_rest_seconds: 0,
    estimated_duration_seconds: 240,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Place the roller under your thighs, supporting your weight with your hands.',
      'Roll slowly from just above the knee to just below the hip.',
      'Repeat on calves, pausing briefly on any tender areas.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
  {
    exercise_id: 'recovery_static_stretch_flow',
    source: 'internal_placeholder',
    external_ref: null,
    title: 'Full-Body Static Stretch Flow',
    category: 'recovery',
    movement_pattern: 'mobility',
    equipment: ['mat'],
    primary_muscles: ['full_body'],
    secondary_muscles: [],
    difficulty: 'beginner',
    contraindications: [],
    coaching_cues: ['Ease into each stretch, never bounce', 'Breathe slowly throughout'],
    common_mistakes: ['Stretching to the point of pain', 'Holding your breath'],
    default_sets: 1,
    default_reps: '30s each stretch',
    default_tempo: null,
    default_rest_seconds: 0,
    estimated_duration_seconds: 300,
    video_url: null,
    thumbnail_url: null,
    instructions: [
      'Move slowly through hamstring, hip, chest, and shoulder stretches.',
      'Hold each position at a comfortable, mild stretch.',
      'Let your exhale deepen the stretch slightly, never forcing it.',
    ],
    easier_variation_id: null,
    harder_variation_id: null,
    notes: null,
  },
];
